create or replace PACKAGE            "NVPHIEU" AS 
--VER 14
--HUYNQ: 26/3/2017
PROCEDURE NHAPMUATONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIET(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPBANBUONTRALAICHITIET(P_KY IN VARCHAR2,P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPBANBUONTRALAITONGHOP(P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_NKHAC_TONGHOP(P_LOAILYDO IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_NKHAC_CHITIET(P_LOAILYDO IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
END NVPHIEU;
/
create or replace PACKAGE BODY            "NVPHIEU" AS
--VER 14
--HUYNQ:7/6/2017
PROCEDURE NHAPMUATONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);

BEGIN
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHO, ''NULL'')  as MaCha, NVL(a.TENKHO, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON t.MAKHONHAP = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='t.MAKHONHAP AS MAKHO,c.TENKHO AS TENKHO';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG , kh.TENNCC';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMSUPPLIER kh on t.MAKHACHHANG = kh.MANCC  AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.MAKHACHHANG AS MAKHACHHANG,kh.TENNCC as TENKH';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTU , t.MACHUNGTUPK';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MACHUNGTU, ''NULL'')  as MaCha, NVL(a.MACHUNGTUPK, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' AND SUBSTR(t.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.MACHUNGTU AS MACHUNGTU,t.MACHUNGTUPK as MACHUNGTUPK';

P_SELECT:= ' ';
END;

ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
P_SELECT2:=' b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT   '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG, 
          SUM(ct.SOLUONG*ct.DONGIA) AS TIENHANG '||P_SELECT||' ,
          SUM(ct.DONGIA*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 
          SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END) as TIENCHIETKHAU  '||P_SELECT||' 
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)
'||P_TABLE_GROUPBY||'
WHERE t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||') a';
     DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATONGHOP;
PROCEDURE NHAPMUACHITIET(P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);
BEGIN
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP, c.TENKHO,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHO, ''NULL'')  as MaCha, NVL(a.TENKHO, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU  ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON t.MAKHONHAP = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='t.NGAYCHUNGTU as NGAYCHUNGTU,t.MAKHONHAP AS MAKHO,c.TENKHO AS TENKHO,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG,kh.TENNCC,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' inner join DMSUPPLIER kh on t.MAKHACHHANG = kh.MANCC  AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENNCC as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK,t.MACHUNGTU,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MACHUNGTU, ''NULL'')  as MaCha, NVL(a.MACHUNGTUPK, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' AND SUBSTR(t.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MACHUNGTUPK AS MACHUNGTUPK,t.MACHUNGTU AS MACHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;

ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT '||P_SELECT2||',
SUM(ct.SOLUONG) as SOLUONG, 
SUM(ct.SOLUONG*ct.DONGIA) AS TIENHANG ,
SUM(ct.DONGIA*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 
SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END) as TIENCHIETKHAU,
ct.DONGIA as DONGIANHAP,
b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)
'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
    order by t.NGAYCHUNGTU DESC ) a';
 DBMS_OUTPUT.put_line (QUERY_STR);     
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIET;




PROCEDURE NHAPBANBUONTRALAITONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);

BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON t.MAKHONHAP = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG , kh.TENKH';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH';

P_SELECT:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,b.GIABANBUON,b.GiaBanLeVat';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
P_SELECT2:=' b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= 'b.GIABANBUON as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT   '||P_SELECT2||',
          SUM(ct.SOLUONG) as SOLUONG, 
          SUM(ct.SOLUONG*NVL(ct.DONGIA,0)) AS TIENHANG 
          '||P_SELECT||' ,
          SUM(NVL(ct.DONGIA,0)*NVL(b.TyLeVatRa/100,0)*ct.SOLUONG) AS TIENVAT, 
          SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END) as TIENCHIETKHAU
          '||P_SELECT||' 
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)
'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||') a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPBANBUONTRALAITONGHOP;
PROCEDURE NHAPBANBUONTRALAICHITIET(P_KY IN VARCHAR2,P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:='t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG,kh.TENKH,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ,0';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 AND SUBSTR(kh.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.VON) as VON ,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG,
 SUM(ct.SOLUONG*NVL(ct.DONGIA,0)) AS TIENHANG ,
 SUM(NVL(ct.DONGIA,0)*NVL(b.TyLeVatRa/100,0)*ct.SOLUONG) AS TIENVAT,
  0 as TIENCHIETKHAU,
  ct.DONGIA as DONGIANHAP,
  b.GiaBanLeVat as GiaBanLeVat,
  SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG) END) AS VON
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT

'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI =10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
    order by t.NGAYCHUNGTU DESC ) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPBANBUONTRALAICHITIET;
PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
KY_KETTHUC NUMBER;
NAM_KETTHUC NUMBER;
P_SQL_INSERT VARCHAR(32767);
N NUMBER:=0;
BEGIN
FOR cur_period in (SELECT to_date(P_TUNGAY, 'dd/MM/yyyy') + LEVEL - 1 AS today
FROM dual
CONNECT BY LEVEL <= to_date(P_DENNGAY, 'dd/MM/yyyy') - to_date(P_TUNGAY, 'dd/MM/yyyy') + 1) LOOP
BEGIN

BEGIN--Tìm kỳ
SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE to_date(DENNGAY, 'dd/MM/yyyy') = to_date(cur_period.today, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
   EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
END;--End Tìm ky

BEGIN --Bắt đầu thực thi nhiệm vu
N:=N+1;
IF (N = 1) THEN
BEGIN -- Bản ghi đầu tiên
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON, TONDAUKYSL, TONDAUKYGT, NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONDAUKYSL, a.TONDAUKYGT, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 
		 ';

IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;   
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
ELSE
BEGIN --Vòng thứ 2 trở đi
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON,NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';

IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;   
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;           
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
END IF;
END;--Kết thúc vong 2 trở đi;

END;
        <<end_loop>>
        null;      
END LOOP;

QUERY_STR:= 'select a.mavattu as Code, 
                                    SUM(a.tondaukysl)  as OpeningBalanceQuantity,
                                    SUM(a.tondaukygt) as OpeningBalanceValue,
                                    SUM(a.nhapsl) as IncreaseQuantity, SUM(a.nhapgt) as IncreaseValue,
                                    SUM(a.xuatsl) as DecreaseQuantity, SUM(a.xuatgt) as DecreaseValue,
                                    SUM(a.tondaukysl - a.xuatsl + a.nhapsl) as ClosingQuantity, 
									SUM(a.tondaukygt - a.xuatgt + a.nhapgt) as ClosingValue
                                    from TMP_XTN_NGAY a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 
									';
QUERY_STR := QUERY_STR||' GROUP BY a.mavattu';    
OPEN XTNCOLLECTION FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END DATHANG_PHATSINH_XNT_BYDATE;
PROCEDURE BAOCAO_DCN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  

IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1 AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + NVL(g.TYLE_VAT_VAO,0)/100)) END) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCN'' '||P_PTHUCXUAT||'
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = ''DV1-CH1-K2''
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
        AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_DCN_TONGHOP;  

PROCEDURE BAOCAO_DCN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1 AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3) ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN
                     ,TO_CHAR(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                          ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0))) END) as VON
                     ,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN
                     ,TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(0) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,t.UNITCODE AS MADONVI
                          ,t.MAKHOXUAT AS MAKHOXUAT
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
                      from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCN'' '||P_PTHUCXUAT||'
left join DMVATTU b on b.MAVATTU = ct.MAHANG

left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
        AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  t.UNITCODE,t.MAKHOXUAT,'||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
  left join '||P_KY||' k on k.MAVATTU = a.MA AND k.UNITCODE = a.MADONVI AND k.MAKHO =  ''DV1-CH1-K2''
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_DCN_CHITIET;
  PROCEDURE BAOCAO_NKHAC_TONGHOP(P_LOAILYDO IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN

IF TRIM(P_LOAILYDO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MALYDOKHAC = '''||P_LOAILYDO||'''';
END IF;
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1 AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0))) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''NKHAC'' 
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
        AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_NKHAC_TONGHOP;  

PROCEDURE BAOCAO_NKHAC_CHITIET(P_LOAILYDO IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_LOAILYDO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MALYDOKHAC = '''||P_LOAILYDO||'''';
END IF;
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   


IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1 AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE,
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0))) as TIENTHUE
                      from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''NKHAC''
left join DMVATTU b on b.MAVATTU = ct.MAHANG

left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
        AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  t.UNITCODE,t.MAKHOXUAT,'||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_NKHAC_CHITIET;
END NVPHIEU;
/