create or replace PACKAGE            "XUATBAN" AS
--VER 12: HUYNQ
--23/09/2017: 
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_ISPAY IN VARCHAR2, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,P_ISPAY IN VARCHAR2, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XKHAC_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XKHAC_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCX_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCX_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);

end XUATBAN;
/
create or replace PACKAGE BODY            "XUATBAN" AS
--ver 10:HUYNQ
--Modified on: 26/10/2017: 
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_ISPAY IN VARCHAR2, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_JOIN_DKIEN VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_ISPAY) IS NOT NULL AND P_ISPAY <> 3 THEN
P_EXPRESSION := P_EXPRESSION||' AND t.TRANGTHAITHANHTOAN = '||P_ISPAY||'';
END IF;
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_XUATXU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAXUATXU IN ('||P_XUATXU||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
P_JOIN_DKIEN := 'a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MADONVINHAN' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVINHAN, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MADONVI AS Ma, c.TENDONVI AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVINHAN AS MA,t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATRA, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAITHUE AS Ma, c.LOAITHUE AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATRA AS MA, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.MA = c.MALOAITHUE  AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.MA = c.MANCC AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA , t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAXUATXU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAXUATXU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAXUATXU AS Ma, c.TENXUATXU AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAXUATXU AS MA , t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMXUATXU c ON a.MA = c.MAXUATXU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA , t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU, t.UNITCODE ';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.UNITCODE ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.UNITCODE = j.UNITCODE';
P_TABLE_GROUPBY:= '  ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU - a.VON) AS LAIBANLE, 
                     TO_CHAR(j.TIENTHE) AS TIENTHE, TO_CHAR(j.TIENCOD) AS TIENCOD, TO_CHAR(j.TIENMAT) AS TIENMAT,
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0))/(1+ NVL(b.TYLEVATRA,0) /100)) as DOANHTHU 
                          ,SUM(((NVL(b.TYLEVATRA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0)))/(1+ NVL(b.TYLEVATRA,0) /100)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.UNITCODE,0,3)
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE '''||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||') a
    --SUM CHILDREN
INNER JOIN  (SELECT '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(t.TIENTHE,0)) AS TIENTHE
                          ,SUM(NVL(t.TIENCOD,0)) AS TIENCOD
                          ,SUM(NVL(t.TIENMAT,0)) AS TIENMAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK  AND t.LOAICHUNGTU = ''XBAN''
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.UNITCODE,0,3)
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE '''||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' ) j on '||P_JOIN_DKIEN||'
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XBAN_TONGHOP;  

PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,P_ISPAY IN VARCHAR2 , cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_ISPAY) IS NOT NULL AND P_ISPAY <> 3 THEN
P_EXPRESSION := P_EXPRESSION||' AND t.TRANGTHAITHANHTOAN = '||P_ISPAY||'';
END IF;
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_XUATXU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAXUATXU IN ('||P_XUATXU||')';
END IF; 
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF; 
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.UNITCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.GROUPCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.UNITCODE AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.GROUPCODE = c.MADONVI';
END; 
ELSIF P_GROUPBY = 'MADONVINHAN' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MADONVINHAN,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MADONVINHAN AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.GROUPCODE = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,b.MAVATRA,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MALOAITHUE AS MaCha,  c.LOAITHUE AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , b.MAVATRA AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.GROUPCODE = c.MALOAITHUE AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MANCC AS MaCha, c.TENNCC AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.GROUPCODE = c.MANCC AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MAKHACHHANG,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAXUATXU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MAXUATXU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAXUATXU AS MaCha, c.TENXUATXU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAXUATXU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMXUATXU c ON a.GROUPCODE = c.MAXUATXU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU - a.VON) AS LAIBANLE, 
                     TO_CHAR(a.TIENTHE) AS TIENTHE, TO_CHAR(a.TIENCOD) AS TIENCOD, TO_CHAR(a.TIENMAT) AS TIENMAT,
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0))/(1+ NVL(b.TYLEVATRA,0) /100)) as DOANHTHU
                          ,SUM(NVL(t.TIENTHE,0)) AS TIENTHE, SUM(NVL(t.TIENCOD,0)) AS TIENCOD, SUM(NVL(t.TIENMAT,0)) AS TIENMAT
                          ,SUM(((NVL(b.TYLEVATRA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0)))/(1+ NVL(b.TYLEVATRA,0) /100)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.UNITCODE,0,3)
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE '''||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' order by t.NGAYCHUNGTU DESC) a 
    '||P_TABLE_GROUPBY;   
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_XBAN_CHITIET;

PROCEDURE BAOCAO_XKHAC_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVINHAN, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MADONVI AS Ma, c.TENDONVI AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVINHAN AS MA,t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATRA, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAITHUE AS Ma, c.LOAITHUE AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATRA AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.MA = c.MALOAITHUE';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.MA = c.MANCC AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU, t.UNITCODE ';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.UNITCODE ';
P_TABLE_GROUPBY:= '  ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.DONGIA,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0) * (NVL(g.TYGIA,0)/100 )) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XKHAC'' AND t.MALYDOKHAC = '''||P_PTHUCXUAT||'''
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.UNITCODE,0,3)
left join DMLOAITHUE g on g.MALOAITHUE = t.VAT
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE ''%'||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XKHAC_TONGHOP;  

PROCEDURE BAOCAO_XKHAC_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MADONVINHAN,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MADONVINHAN AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMDONVI c ON a.GROUPCODE = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,b.MAVATRA,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MALOAITHUE AS MaCha,  c.LOAITHUE AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich   ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , b.MAVATRA AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.GROUPCODE = c.MALOAITHUE AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.DONGIA,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0) * (NVL(g.TYGIA,0)/100 )) as TIENTHUE
                  from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XKHAC'' AND t.MALYDOKHAC = '''||P_PTHUCXUAT||'''
left join DMVATTU b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)
left join DMLOAITHUE g on g.MALOAITHUE = t.VAT
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_XKHAC_CHITIET;
PROCEDURE BAOCAO_DCX_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVINHAN, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MADONVI AS Ma, c.TENDONVI AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVINHAN AS MA,t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATRA, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAITHUE AS Ma, c.LOAITHUE AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATRA AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.MA = c.MALOAITHUE';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.MA = c.MANCC AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR(a.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU, t.UNITCODE ';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.UNITCODE ';
P_TABLE_GROUPBY:= '  ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCX'' '||P_PTHUCXUAT||'
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.UNITCODE,0,3)
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE ''%'||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_DCX_TONGHOP;  

PROCEDURE BAOCAO_DCX_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2,	P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATRA IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MADONVINHAN,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MADONVINHAN AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMDONVI c ON a.GROUPCODE = c.MADONVI ';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,b.MAVATRA,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MALOAITHUE AS MaCha,  c.LOAITHUE AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich   ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , b.MAVATRA AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAITHUE c ON a.GROUPCODE = c.MALOAITHUE AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND SUBSTR(c.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

 QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
                      from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCX'' '||P_PTHUCXUAT||'
left join DMVATTU b on b.MAVATTU = ct.MAHANG AND SUBSTR(b.UNITCODE,0,3) = SUBSTR('''||P_UNITCODE||''',0,3)

left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_DCX_CHITIET;
END XUATBAN;