create or replace PROCEDURE "BAOCAO_TONKHO_CHITIET" (P_TABLE_NAME IN VARCHAR2,P_DKIENLOC IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_UNITCODE IN VARCHAR2,P_SELECTEDVAT IN VARCHAR2,CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(5000);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(2000);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(2000);
P_TABLE_GROUPBY VARCHAR(2000);
P_COLUMNS_GROUPBY VARCHAR(2000);
P_EXPRESSION  VARCHAR(1000):= '';
P_NOTNULL VARCHAR(1000);
BEGIN
IF P_DKIENLOC = 'POSITIVE' THEN 
P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) > 0 ';
END IF;
IF P_DKIENLOC = 'NEGATIVE' THEN 
P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) < 0 ';
END IF;
IF P_DKIENLOC = 'ZERO' THEN 
P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) = 0 ';
END IF;
--  
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHO IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
--

IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha, c.TENDONVI AS TenCha, a.MA AS MADONVI, a.gia_banle_vat, a.giamuavat  ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, t.UNITCODE AS GROUPCODE, vtgc.gia_banle_vat, vtgc.giamuavat ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.GROUPCODE = c.MADONVI';
P_NOTNULL := ' AND t.UNITCODE IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHO, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha, a.UNITCODE AS MADONVI, a.gia_banle_vat, a.giamuavat ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHO AS GROUPCODE, t.UNITCODE, vtgc.gia_banle_vat, vtgc.giamuavat';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.GROUPCODE = c.MAKHO AND c.UNITCODE = a.UNITCODE';
P_NOTNULL := ' AND t.MAKHO IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha, a.UNITCODE AS MADONVI, a.gia_banle_vat, a.giamuavat ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE, t.UNITCODE, vtgc.gia_banle_vat, vtgc.giamuavat';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND c.UNITCODE =  a.UNITCODE';
P_NOTNULL := ' AND b.MANHOMVATTU IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha, a.UNITCODE AS MADONVI, a.gia_banle_vat, a.giamuavat ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE, t.UNITCODE, vtgc.gia_banle_vat, vtgc.giamuavat';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND c.UNITCODE =  a.UNITCODE';
P_NOTNULL := ' AND b.MALOAIVATTU IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MANCC AS MaCha, c.TENNCC AS TenCha, a.UNITCODE AS MADONVI, a.gia_banle_vat, a.giamuavat ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE, t.UNITCODE, vtgc.gia_banle_vat, vtgc.giamuavat';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.GROUPCODE = c.MANCC AND c.UNITCODE =  a.UNITCODE';
P_NOTNULL := ' AND b.MAKHACHHANG IS NOT NULL ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.UNITCODE, t.GIAVON, vtgc.gia_banle_vat, vtgc.giamuavat';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha, a.UNITCODE AS MADONVI, a.gia_banle_vat, a.giamuavat ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, t.UNITCODE, vtgc.gia_banle_vat, vtgc.giamuavat';
P_TABLE_GROUPBY:= ' ';
P_NOTNULL := ' AND b.MAVATTU IS NOT NULL ';
END;
END IF;
 IF P_SELECTEDVAT = '0' THEN ----Không lấy giá VAT
    QUERY_STR := 'select (a.TONCUOIKYSL) as TONCUOIKYSL,(a.TONCUOIKYGT) as TONCUOIKYGT, a.GIAVON,
    '||P_SELECT_COLUMNS_OUT_GROUPBY||'
    from (
    SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                              ,SUM(NVL(t.TONCUOIKYSL,0)) as TONCUOIKYSL
                              ,SUM(NVL(t.TONCUOIKYGT,0)) as TONCUOIKYGT
                              ,NVL(t.GIAVON,0) AS GIAVON
    from '||P_TABLE_NAME||' t
    INNER JOIN DM_VATTU b on b.MAVATTU = t.MAVATTU AND b.UNITCODE = t.UNITCODE
    inner join dm_vattu_giaca vtgc on vtgc.mavattu = t.mavattu
    WHERE
        t.UNITCODE LIKE ''%'||P_UNITCODE||'%'' 
        AND t.TONCUOIKYSL <> 0
        '||P_NOTNULL||'
        '||P_EXPRESSION||' 
        GROUP BY  '||P_COLUMNS_GROUPBY|| ' ORDER BY ' || P_COLUMNS_GROUPBY ||') a
     '||P_TABLE_GROUPBY;
ELSE
    QUERY_STR := 'select (a.TONCUOIKYSL) as TONCUOIKYSL,(a.TONCUOIKYGT) as TONCUOIKYGT, a.GIAVON,
    '||P_SELECT_COLUMNS_OUT_GROUPBY||'
    from (
    SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                              ,SUM(NVL(t.TONCUOIKYSL,0)) as TONCUOIKYSL
                              ,SUM(NVL(t.TONCUOIKYGT*(1 + (b.TYLE_VAT_VAO/100)),0)) as TONCUOIKYGT
                              ,NVL(t.GIAVON*(1 + (b.TYLE_VAT_VAO/100),0) AS GIAVON
    from '||P_TABLE_NAME||' t
    INNER JOIN DM_VATTU b on b.MAVATTU = t.MAVATTU AND b.UNITCODE = t.UNITCODE
    inner join dm_vattu_giaca vtgc on vtgc.mavattu = t.mavattu
    WHERE
        t.UNITCODE LIKE ''%'||P_UNITCODE||'%'' 
        AND t.TONCUOIKYSL <> 0
        '||P_NOTNULL||'
        '||P_EXPRESSION||' 
        GROUP BY  '||P_COLUMNS_GROUPBY|| ' ORDER BY ' || P_COLUMNS_GROUPBY ||') a
     '||P_TABLE_GROUPBY;
END IF;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_TONKHO_CHITIET;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_TONKHO_CHITIET
--------------------------------------------------------