create or replace PROCEDURE "BAOCAO_TONKHO_TONGHOP" (P_TABLE_NAME IN VARCHAR2,P_DKIENLOC IN VARCHAR2,
    P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  
    P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_UNITCODE IN VARCHAR2,P_SELECTEDVAT IN VARCHAR2, CUR  OUT SYS_REFCURSOR) AS
    QUERY_STR VARCHAR(2000);
    P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(2000);
    P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(2000);
    P_TABLE_GROUPBY VARCHAR(2000);
    P_COLUMNS_GROUPBY VARCHAR(2000);
    P_EXPRESSION  VARCHAR(2000):= '';
    P_NOTNULL  VARCHAR(1000);
BEGIN
    IF P_DKIENLOC IS NOT NULL AND P_DKIENLOC = 'POSITIVE' THEN 
    P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) > 0 ';
    END IF;
    IF P_DKIENLOC IS NOT NULL AND P_DKIENLOC = 'NEGATIVE' THEN 
    P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) < 0 ';
    END IF;
    IF P_DKIENLOC IS NOT NULL AND P_DKIENLOC = 'ZERO' THEN 
    P_EXPRESSION := P_EXPRESSION||' AND NVL(t.TONCUOIKYSL,0) = 0 ';
    END IF;
    --  
    IF TRIM(P_MAKHO) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION||' AND t.MAKHO IN ('||P_MAKHO||')';
    END IF;
    IF TRIM(P_MALOAI) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
    END IF;
    IF TRIM(P_MANHOM) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
    END IF;
    IF TRIM(P_MAVATTU) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
    END IF;    
    IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
    END IF;  
    --
    IF P_GROUPBY = 'MADONVI' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 't.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten, a.MA AS MADONVI  ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
    P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.MA = c.MADONVI';
    P_NOTNULL := ' AND t.UNITCODE IS NOT NULL ';
    END;
    ELSIF P_GROUPBY = 'MAKHO' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 't.MAKHO, t.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten, a.UNITCODE AS MADONVI ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHO AS MA,t.UNITCODE ';
    P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.MA = c.MAKHO AND c.UNITCODE = a.UNITCODE';
    P_NOTNULL := ' AND t.MAKHO IS NOT NULL ';
    END;
    ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,t.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten, a.UNITCODE AS MADONVI  ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.UNITCODE ';
    P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.MA = c.MANHOMVTU  AND c.UNITCODE = a.UNITCODE';
    P_NOTNULL := ' AND b.MANHOMVATTU IS NOT NULL ';
    END;
    ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten, a.UNITCODE AS MADONVI ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.UNITCODE ';
    P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.MA = c.MALOAIVATTU  AND c.UNITCODE = a.UNITCODE';
    P_NOTNULL := ' AND b.MALOAIVATTU IS NOT NULL ';
    END;
    ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG, t.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten, a.UNITCODE AS MADONVI ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA, t.UNITCODE ';
    P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.MA = c.MANCC  AND c.UNITCODE = a.UNITCODE';
    P_NOTNULL := ' AND b.MAKHACHHANG IS NOT NULL ';
    END;
    ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
    BEGIN
    P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU, t.UNITCODE';
    P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten, a.UNITCODE AS MADONVI ';
    P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.UNITCODE ';
    P_TABLE_GROUPBY:= '';
    P_NOTNULL := ' AND b.MAVATTU IS NOT NULL ';
    END;
    END IF;
     IF P_SELECTEDVAT = '0' THEN ----Không lấy giá VAT
         QUERY_STR := 'select (a.TONCUOIKYSL) as TONCUOIKYSL,(a.TONCUOIKYGT) as TONCUOIKYGT,
        '||P_SELECT_COLUMNS_OUT_GROUPBY||'
        from (
        SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                                  ,SUM(NVL(t.TONCUOIKYSL,0)) as TONCUOIKYSL
                                  ,SUM(NVL(t.TONCUOIKYGT,0)) as TONCUOIKYGT
        from '||P_TABLE_NAME||' t
        INNER JOIN DM_VATTU b on b.MAVATTU = t.MAVATTU  AND b.UNITCODE = t.UNITCODE
        WHERE
            t.UNITCODE  LIKE ''%'||P_UNITCODE||'%''
            AND t.TONCUOIKYSL <> 0
            '||P_NOTNULL||'
            '||P_EXPRESSION||' 
            group by  '||P_COLUMNS_GROUPBY|| ' ORDER BY ' || P_COLUMNS_GROUPBY || ') a 
         '||P_TABLE_GROUPBY;
     ELSE
        QUERY_STR := 'select (a.TONCUOIKYSL) as TONCUOIKYSL,(a.TONCUOIKYGT) as TONCUOIKYGT,
        '||P_SELECT_COLUMNS_OUT_GROUPBY||'
        from (
        SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                                  ,SUM(NVL(t.TONCUOIKYSL,0)) as TONCUOIKYSL
                                  ,SUM(NVL(t.TONCUOIKYGT*(1 + (b.TYLE_VAT_VAO/100)),0)) as TONCUOIKYGT
        from '||P_TABLE_NAME||' t
        INNER JOIN DM_VATTU b on b.MAVATTU = t.MAVATTU  AND b.UNITCODE = t.UNITCODE
        WHERE
            t.UNITCODE  LIKE ''%'||P_UNITCODE||'%''
            AND t.TONCUOIKYSL <> 0
            '||P_NOTNULL||'
            '||P_EXPRESSION||' 
            group by  '||P_COLUMNS_GROUPBY|| ' ORDER BY ' || P_COLUMNS_GROUPBY || ') a 
         '||P_TABLE_GROUPBY;
     END IF;
    
    BEGIN
    DBMS_OUTPUT.put_line (QUERY_STR);  
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
                WHEN NO_DATA_FOUND THEN
                 NULL;
                   WHEN OTHERS THEN
          NULL;
    END;
END BAOCAO_TONKHO_TONGHOP;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_TONKHO_TONGHOP
--------------------------------------------------------