create or replace PACKAGE            "KHUYENMAI" AS 
PROCEDURE KHUYENMAI_HANG_BANLE(P_NGAY IN DATE, P_CUR OUT SYS_REFCURSOR);
PROCEDURE KHUYENMAI_HANG_THEOMAHANG(P_NGAY IN DATE ,P_MAVATTU IN VARCHAR2,P_UNITCODE IN VARCHAR2,P_DATAPROMOTION OUT SYS_REFCURSOR);
END KHUYENMAI;
/
create or replace PACKAGE BODY            "KHUYENMAI" AS
PROCEDURE KHUYENMAI_HANG_BANLE(P_NGAY IN DATE, P_CUR OUT SYS_REFCURSOR) AS 
BEGIN
OPEN P_CUR FOR SELECT MACHUONGTRINH,TUNGAY,DENNGAY,GIATRIKHUYENMAI,TYLEKHUYENMAI,NOIDUNG,TRANGTHAI,MAVATTU,
  SOLUONG,MAHANG_KHUYENMAI,SOLUONG_KHUYENMAI,MAKHOKHUYENMAI,LOAIKHUYENMAI,TYLEKHUYENMAICHILDREN,HANGKMCHINH,TUGIO,DENGIO
  from V_CHUONGTRINH_KHUYENMAI 
where TO_DATE(P_NGAY, 'DD/MM/YY') 
BETWEEN TO_DATE(TUNGAY, 'DD/MM/YY') AND TO_DATE(DENNGAY, 'DD/MM/YY') AND TRANGTHAI = 10;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE ('Lỗi');
    RAISE;
END KHUYENMAI_HANG_BANLE;

PROCEDURE KHUYENMAI_HANG_THEOMAHANG(P_NGAY IN DATE ,P_MAVATTU IN VARCHAR2,P_UNITCODE IN VARCHAR2,P_DATAPROMOTION OUT SYS_REFCURSOR) AS
  SQL_QUERRY VARCHAR(32264);
BEGIN 

    SQL_QUERRY :=  'SELECT MACHUONGTRINH AS MACHUONGTRINH,TUNGAY AS TUNGAY,DENNGAY AS DENNGAY,NVL(GIATRIKHUYENMAI,0) AS GIATRIKHUYENMAI,NVL(TYLEKHUYENMAI,0) AS TYLEKHUYENMAI,NVL(TYLEBATDAU,0) AS TYLEBATDAU,NOIDUNG AS NOIDUNG,
TRANGTHAI AS TRANGTHAI,MAVATTU AS MAVATTU,NVL(SOLUONG,0) AS SOLUONG,MAHANG_KHUYENMAI AS MAHANG_KHUYENMAI,NVL(SOLUONG_KHUYENMAI,0) AS SOLUONG_KHUYENMAI,NVL(TYLEKHUYENMAICHILDREN,0) AS TYLEKHUYENMAICHILDREN,
MAKHOKHUYENMAI AS MAKHOKHUYENMAI,LOAIKHUYENMAI,TUGIO,DENGIO,NVl(HANGKMCHINH,0) AS HANGKMCHINH,NVL(GIATRIKHUYENMAICHILDREN,0) AS GIATRIKHUYENMAICHILDREN,MAHANG_KM_BUY1GET1,TENHANG_KM_BUY1GET1,SOLUONG_KM_BUY1GET1 FROM V_CHUONGTRINH_KHUYENMAI 
where TO_DATE('''||P_NGAY||''', ''DD/MM/YY'') BETWEEN TO_DATE(TUNGAY, ''DD/MM/YY'') AND TO_DATE(DENNGAY, ''DD/MM/YY'') AND TRANGTHAI = 10 AND MAVATTU = '''||P_MAVATTU||''' AND UNITCODE='''||P_UNITCODE||'''';        
BEGIN
OPEN P_DATAPROMOTION FOR SQL_QUERRY;
DBMS_OUTPUT.put_line(SQL_QUERRY);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (SQL_QUERRY  || SQLERRM);
END;
END KHUYENMAI_HANG_THEOMAHANG;

END KHUYENMAI;