create or replace PROCEDURE "BAOCAO_NKHAC_TONGHOP" (P_LOAILYDO IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2, P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, 
P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2,P_MATHUE IN VARCHAR2,
P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS

QUERY_STR VARCHAR(3000);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(3000);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(3000);
P_TABLE_GROUPBY VARCHAR(3000);
P_COLUMNS_GROUPBY VARCHAR(3000);
P_EXPRESSION  VARCHAR(3000):= '';
BEGIN

IF TRIM(P_LOAILYDO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MALYDOKHAC = '''||P_LOAILYDO||'''';
END IF;
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;
IF TRIM(P_MATHUE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_MATHUE||')';
END IF; 


IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHONHAP AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.MA = c.MAKHO AND c.UNITCODE = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.UNITCODE AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.MA = c.MADONVI AND c.MADONVI = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.MA = c.MANHOMVTU AND c.UNITCODE = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.MA = c.MALOAIVATTU AND c.UNITCODE = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.MA = c.MANCC AND c.UNITCODE = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY ='MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= ' g.MALOAITHUE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'lt.MALOAITHUE as Ma , lt.LOAITHUE as Ten';
P_TABLE_GROUPBY:= 'LEFT JOIN DM_LOAITHUE lt on lt.MALOAITHUE = a.MALOAITHUE AND lt.UNITCODE = '''||P_UNITCODE||''' ';
P_SELECT_COLUMNS_IN_GROUPBY := 'g.MALOAITHUE';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.USERNAME AS Ma, c.TENNHANVIEN AS Ten,a.UNITCODE AS MADONVI  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.I_CREATE_BY AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON a.MA = c.USERNAME AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY ='PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= ' t.NOIDUNG, t.MACHUNGTUPK ';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MACHUNGTUPK as Ma , a.NOIDUNG as Ten';
P_SELECT_COLUMNS_IN_GROUPBY := 't.NOIDUNG as NOIDUNG, t.MACHUNGTUPK as MACHUNGTUPK ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select (a.SOLUONGBAN) as SOLUONGBAN,(a.VON) as VON,(a.TIENTHUE) AS TIENTHUE,(a.DOANHTHU) AS DOANHTHU,(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, a.TIENCHIETKHAU, (a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)*NVL(ct.SOLUONG,0)) AS VON
                          ,ROUND(SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END),2) as TIENCHIETKHAU
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM((NVL(g.TYGIA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0))) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''NKHAC'' 
INNER JOIN DM_VATTU b on b.MAVATTU = ct.MAHANG
LEFT JOIN DM_LOAITHUE g on g.MALOAITHUE = ct.VAT
WHERE
    t.TRANGTHAI = 10
        AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	GROUP BY  '||P_COLUMNS_GROUPBY||' ORDER BY '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_NKHAC_TONGHOP;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_NKHAC_TONGHOP
--------------------------------------------------------