create or replace PACKAGE NVPHIEU AS 
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR);
END NVPHIEU;
/
create or replace PACKAGE BODY NVPHIEU AS
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang, 
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='NMUA' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUA;


PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHOMHANGHOA;

PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEOLOAIHANGHOA;

PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='NMUA' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHACUNGCAP;

PROCEDURE DIEUCHUYENTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='DCX' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEOHANGHOA;


PROCEDURE DIEUCHUYENTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCX' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEONHOMHANGHOA;

PROCEDURE DIEUCHUYENTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCX' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEOLOAIHANGHOA;

PROCEDURE DIEUCHUYENTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='DCX' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEONHACUNGCAP;


PROCEDURE DIEUCHUYENNHANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='DCN' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEOHANGHOA;


PROCEDURE DIEUCHUYENNHANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCN' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEONHOMHANGHOA;

PROCEDURE DIEUCHUYENNHANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCN' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEOLOAIHANGHOA;

PROCEDURE DIEUCHUYENNHANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='DCN' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEONHACUNGCAP;

PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
KY_KETTHUC NUMBER;
NAM_KETTHUC NUMBER;
P_SQL_INSERT VARCHAR(32767);
N NUMBER:=0;
BEGIN
FOR cur_period in (SELECT to_date(P_DENNGAY, 'dd/MM/yyyy') - LEVEL + 1 AS today
FROM dual
CONNECT BY LEVEL <= to_date(P_DENNGAY, 'dd/MM/yyyy') - to_date(P_TUNGAY, 'dd/MM/yyyy') + 1) LOOP
BEGIN

BEGIN--Tìm kỳ
SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE to_date(DENNGAY, 'dd/MM/yyyy') = to_date(cur_period.today, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
   EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
END;--End Tìm ky

BEGIN --Bắt đầu thực thi nhiệm vu
N:=N+1;
IF (N = 1) THEN
BEGIN -- Bản ghi đầu tiên
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON, TONDAUKYSL, TONDAUKYGT, NHAPSL, NHAPGT, XUATSL, XUATGT, TONCUOIKYSL, TONCUOIKYGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONDAUKYSL, a.TONDAUKYGT, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT, a.TONCUOIKYSL, a.TONCUOIKYGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||'  a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';

IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
ELSE
BEGIN --Vòng thứ 2 trở đi
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON,NHAPSL, NHAPGT, XUATSL, XUATGT, TONCUOIKYSL, TONCUOIKYGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, GIAVON, NHAPSL, NHAPGT, XUATSL, XUATGT, 0, 0
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;   
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
END IF;
END;--Kết thúc vong 2 trở đi;
  
END;
        <<end_loop>>
        null;      
END LOOP;

QUERY_STR:= 'select a.mavattu as Code,
                                    (SUM(a.toncuoikysl) - SUM(a.nhapsl) + SUM(a.xuatsl))  as OpeningBalanceQuantity,
                                    (SUM(a.toncuoikygt) - SUM(a.nhapgt) + SUM(a.xuatgt)) as OpeningBalanceValue,
                                    SUM(a.nhapsl) as IncreaseQuantity, SUM(a.nhapgt) as IncreaseValue,
                                    SUM(a.xuatsl) as DecreaseQuantity, SUM(a.xuatgt) as DecreaseValue,
                                    SUM(a.toncuoikysl) as ClosingQuantity, SUM(a.toncuoikygt) as ClosingValue
                                    from TMP_XTN_NGAY a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1';
QUERY_STR := QUERY_STR||' GROUP BY a.mavattu';    
OPEN XTNCOLLECTION FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END DATHANG_PHATSINH_XNT_BYDATE;

END NVPHIEU;