create or replace PACKAGE NVPHIEU AS 
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
END NVPHIEU;
/
create or replace PACKAGE BODY NVPHIEU AS
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang, 
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='NMUA' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUA;


PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHOMHANGHOA;

PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEOLOAIHANGHOA;

PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='NMUA' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHACUNGCAP;

END NVPHIEU;