create or replace PACKAGE NVPHIEU AS 
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DIEUCHUYENNHANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE XUATBANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE XUATBANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE XUATBANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR OUT SYS_REFCURSOR);
PROCEDURE XUATBANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIETTHEONHACUNGCAP(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIETTHEOLOAIHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIETTHEONHOMHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIETTHEONHOMHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHOMHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NMUACTTHEONHACUNGCAPVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEONHACUNGCAPVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOHANGCHITIET(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIETTHEOLOAIHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATHEOLOAIHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUATONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPMUACHITIET(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPBANBUONTRALAICHITIET(P_KY IN VARCHAR2,P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE NHAPBANBUONTRALAITONGHOP(P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);

END NVPHIEU;
/
--HuyNQ Modified: 20/2/2017
--NHAPMUATONGHOP & NHAPMUACHITIET
create or replace PACKAGE BODY NVPHIEU AS
PROCEDURE NHAPMUA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang, 
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='NMUA' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUA;


PROCEDURE NHAPMUATHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHOMHANGHOA;

PROCEDURE NHAPMUATHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='NMUA' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEOLOAIHANGHOA;

PROCEDURE NHAPMUATHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='NMUA' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END NHAPMUATHEONHACUNGCAP;

PROCEDURE DIEUCHUYENTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='DCX' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEOHANGHOA;


PROCEDURE DIEUCHUYENTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCX' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEONHOMHANGHOA;

PROCEDURE DIEUCHUYENTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCX' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEOLOAIHANGHOA;

PROCEDURE DIEUCHUYENTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='DCX' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENTHEONHACUNGCAP;


PROCEDURE DIEUCHUYENNHANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='DCN' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEOHANGHOA;


PROCEDURE DIEUCHUYENNHANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCN' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEONHOMHANGHOA;

PROCEDURE DIEUCHUYENNHANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='DCN' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEOLOAIHANGHOA;

PROCEDURE DIEUCHUYENNHANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='DCN' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END DIEUCHUYENNHANTHEONHACUNGCAP;
PROCEDURE XUATBANTHEOHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,b.MAVATTU as Ma, b.TENVATTU as Ten 
from (
SELECT ct.MAHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang, 
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE = ''||P_UNITCODE||''   AND t.LOAICHUNGTU ='XBAN' group by ct.MAHANG)
a left join DMVATTU b on a.MAHANG = b.MAVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END XUATBANTHEOHANGHOA;


PROCEDURE XUATBANTHEONHOMHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MANHOMVTU as Ma, n.TENNHOMVT as Ten 
from (
SELECT  b.MANHOMVATTU AS MANHOMVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='XBAN' group by  b.MANHOMVATTU)
a left join DMNHOMVATTU n on a.MANHOMVATTU = n.MANHOMVTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END XUATBANTHEONHOMHANGHOA;

PROCEDURE XUATBANTHEOLOAIHANGHOA(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang,  TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,n.MALOAIVATTU as Ma, n.TENLOAIVT as Ten 
from (
SELECT  b.MALOAIVATTU AS MALOAIVATTU, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||''  AND t.LOAICHUNGTU ='XBAN' group by  b.MALOAIVATTU)
a left join DMLOAIVATTU n on a.MALOAIVATTU = n.MALOAIVATTU;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END XUATBANTHEOLOAIHANGHOA;

PROCEDURE XUATBANTHEONHACUNGCAP(P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
 BEGIN
OPEN CUR FOR select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MAKHACHHANG) as Ma, TO_CHAR(kh.TENKH) as Ten 
from (
SELECT  t.MAKHACHHANG AS MAKHACHHANG, SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
WHERE
     t.NGAYCHUNGTU <=TO_DATE(P_DENNGAY,'DD/MM/YY')
    AND t.NGAYCHUNGTU >=TO_DATE(P_TUNGAY,'DD/MM/YY') AND t.UNITCODE = ''||P_UNITCODE||'' AND t.LOAICHUNGTU ='XBAN' group by  t.MAKHACHHANG)
a inner join DMKHACHHANG kh on a.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END XUATBANTHEONHACUNGCAP;
PROCEDURE DATHANG_PHATSINH_XNT_BYDATE(P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
KY_KETTHUC NUMBER;
NAM_KETTHUC NUMBER;
P_SQL_INSERT VARCHAR(32767);
N NUMBER:=0;
BEGIN
FOR cur_period in (SELECT to_date(P_TUNGAY, 'dd/MM/yyyy') + LEVEL - 1 AS today
FROM dual
CONNECT BY LEVEL <= to_date(P_DENNGAY, 'dd/MM/yyyy') - to_date(P_TUNGAY, 'dd/MM/yyyy') + 1) LOOP
BEGIN

BEGIN--Tìm kỳ
SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE to_date(DENNGAY, 'dd/MM/yyyy') = to_date(cur_period.today, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
   EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
END;--End Tìm ky

BEGIN --Bắt đầu thực thi nhiệm vu
N:=N+1;
IF (N = 1) THEN
BEGIN -- Bản ghi đầu tiên
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON, TONDAUKYSL, TONDAUKYGT, NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONDAUKYSL, a.TONDAUKYGT, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 
		 ';

IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;   
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
ELSE
BEGIN --Vòng thứ 2 trở đi
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON,NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';

IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;   
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;           
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
END IF;
END;--Kết thúc vong 2 trở đi;
  
END;
        <<end_loop>>
        null;      
END LOOP;

QUERY_STR:= 'select a.mavattu as Code, 
                                    SUM(a.tondaukysl)  as OpeningBalanceQuantity,
                                    SUM(a.tondaukygt) as OpeningBalanceValue,
                                    SUM(a.nhapsl) as IncreaseQuantity, SUM(a.nhapgt) as IncreaseValue,
                                    SUM(a.xuatsl) as DecreaseQuantity, SUM(a.xuatgt) as DecreaseValue,
                                    SUM(a.tondaukysl - a.xuatsl + a.nhapsl) as ClosingQuantity, 
									SUM(a.tondaukygt - a.xuatgt + a.nhapgt) as ClosingValue
                                    from TMP_XTN_NGAY a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 
									';
QUERY_STR := QUERY_STR||' GROUP BY a.mavattu';    
OPEN XTNCOLLECTION FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END DATHANG_PHATSINH_XNT_BYDATE;




PROCEDURE NHAPMUACHITIETTHEONHACUNGCAP(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION:= 'AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MAKHACHHANG) as MaCha, TO_CHAR(a.TENKH) as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon
from (
SELECT   t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by t.MAKHACHHANG,kh.TENKH,b.MAVATTU,b.TENVATTU) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIETTHEONHACUNGCAP;

PROCEDURE NHAPMUACHITIETTHEOLOAIHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION:= 'AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,TO_CHAR(a.MALOAIVATTU) as MaCha, TO_CHAR(a.TENLOAIVT) as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon
from (
SELECT   b.MALOAIVATTU AS MALOAIVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
inner join DMLOAIVATTU kh on b.MALOAIVATTU = kh.MALOAIVATTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIETTHEOLOAIHANG;

PROCEDURE NHAPMUACHITIETTHEONHOMHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION:= 'AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon
from (
SELECT   b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM((ct.SOLUONG * ct.DONGIA)) AS TienHang,SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) AS TIENCHIETKHAU,
SUM(CASE NVL(t.THANHTIENTRUOCVAT, 0) - NVL(t.TIENCHIETKHAU, 0) WHEN 0 THEN 0 ELSE (NVL(t.TIENVAT, 0)/(t.THANHTIENTRUOCVAT - t.TIENCHIETKHAU))* ((ct.SOLUONG * ct.DONGIA) - CASE NVL(t.THANHTIENTRUOCVAT, 0) WHEN 0 THEN 0 ELSE NVL(t.TIENCHIETKHAU, 0)/t.THANHTIENTRUOCVAT * (ct.SOLUONG * ct.DONGIA) END) END)  AS TIENVAT
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join DMVATTU b on b.MAVATTU = ct.MAHANG
inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIETTHEONHOMHANG;



PROCEDURE NHAPMUATHEONHOMHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha
from (
SELECT   b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MANHOMVATTU,kh.TENNHOMVT) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATHEONHOMHANGVER2;
PROCEDURE NHAPMUACHITIETTHEONHOMHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU
from (
SELECT t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat,t.NGAYCHUNGTU 
    order by t.NGAYCHUNGTU DESC ) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIETTHEONHOMHANGVER2;



PROCEDURE NHAPMUATHEONHACUNGCAPVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha
from (
SELECT   t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by t.MAKHACHHANG,kh.TENKH) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATHEONHACUNGCAPVER2;
PROCEDURE NMUACTTHEONHACUNGCAPVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   
QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu
from (
SELECT  t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by t.MAKHACHHANG,kh.TENKH,b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat,t.NGAYCHUNGTU ,0
    order by t.NGAYCHUNGTU DESC ) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NMUACTTHEONHACUNGCAPVER2;


PROCEDURE NHAPMUATHEOHANGCHITIET(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   
QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu
from (
SELECT   TO_CHAR(t.NGAYCHUNGTU,''DD/MM/YYYY'') as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat,t.NGAYCHUNGTU) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATHEOHANGCHITIET;

PROCEDURE NHAPMUATHEOHANG(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   
QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon
from (
SELECT b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat ) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATHEOHANG;


PROCEDURE NHAPMUATHEOLOAIHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha
from (
SELECT   b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMLOAIVATTU kh on b.MALOAIVATTU = kh.MALOAIVATTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MALOAIVATTU,kh.TENLOAIVT) a';
         DBMS_OUTPUT.put_line (QUERY_STR );     

OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATHEOLOAIHANGVER2;
PROCEDURE NHAPMUACHITIETTHEOLOAIHANGVER2(P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu
from (
SELECT t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU,SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GiaMua) AS TIENHANG ,SUM(b.GiaMua*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
inner join DMLOAIVATTU kh on b.MALOAIVATTU = kh.MALOAIVATTU
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU =''NMUA'' '||P_EXPRESSION||' group by b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat,t.NGAYCHUNGTU 
    order by t.NGAYCHUNGTU DESC) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIETTHEOLOAIHANGVER2;

PROCEDURE NHAPMUATONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);

BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU';
P_SELECT2:='b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU ';
P_SELECT2:=' b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG , kh.TENKH';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 ';
P_SELECT2:=' t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTU , t.MACHUNGTUPK';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MACHUNGTU, ''NULL'')  as MaCha, NVL(a.MACHUNGTUPK, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' t.MACHUNGTU AS MACHUNGTU,t.MACHUNGTUPK as MACHUNGTUPK';

P_SELECT:= ' ';
END;

ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,b.GIAMUA,b.GiaBanLeVat';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ,b.GIAMUA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT   '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*ct.DONGIA) AS TIENHANG '||P_SELECT||' ,SUM(ct.DONGIA*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU '||P_SELECT||' 
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
'||P_TABLE_GROUPBY||'
WHERE t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||') a';
     DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUATONGHOP;
PROCEDURE NHAPMUACHITIET(P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU';
P_SELECT2:='t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG,kh.TENKH,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ,0';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK,t.MACHUNGTU,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ,0';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MACHUNGTU, ''NULL'')  as MaCha, NVL(a.MACHUNGTUPK, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MACHUNGTUPK AS MACHUNGTUPK,t.MACHUNGTU AS MACHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;

ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*ct.DONGIA) AS TIENHANG ,SUM(ct.DONGIA*NVL(b.TyLeVatVao/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU,ct.DONGIA as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
    order by t.NGAYCHUNGTU DESC ) a';
 DBMS_OUTPUT.put_line (QUERY_STR);     
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIET;




PROCEDURE NHAPBANBUONTRALAITONGHOP(P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);

BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU';
P_SELECT2:='b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU ';
P_SELECT2:=' b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG , kh.TENKH';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 ';
P_SELECT2:=' t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH';

P_SELECT:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,b.GIABANBUON,b.GiaBanLeVat';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ,b.GIABANBUON as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT   '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG, SUM(ct.SOLUONG*b.GIABANBUON) AS TIENHANG '||P_SELECT||' ,SUM(b.GIABANBUON*NVL(b.TyLeVatRa/100,0)*ct.SOLUONG) AS TIENVAT, 0 as TIENCHIETKHAU '||P_SELECT||' 
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
'||P_TABLE_GROUPBY||'
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||') a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPBANBUONTRALAITONGHOP;
PROCEDURE NHAPBANBUONTRALAICHITIET(P_KY IN VARCHAR2,P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;   

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
P_SELECT2:='';

P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' inner join DMNHOMVATTu kh on b.MANHOMVATTU = kh.MANHOMVTU';
P_SELECT2:='t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG,kh.TENKH,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ,0';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' inner join DMKHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:=' t.NGAYCHUNGTU as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
END IF;


QUERY_STR:= 'select TO_CHAR(a.SOLUONG) as SoLuong,TO_CHAR(a.VON) as VON ,TO_CHAR(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, TO_CHAR(a.TIENHANG) as TienHang, TO_CHAR(a.TIENVAT) as TienVat, TO_CHAR(a.TIENCHIETKHAU) as TienChietKhau, TO_CHAR(a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT '||P_SELECT2||',SUM(ct.SOLUONG) as SOLUONG,
 SUM(ct.SOLUONG*b.GIABANBUON) AS TIENHANG ,
 SUM(b.GIABANBUON*NVL(b.TyLeVatRa/100,0)*ct.SOLUONG) AS TIENVAT,
  0 as TIENCHIETKHAU,
  ct.DONGIA as DONGIANHAP,
  b.GiaBanLeVat as GiaBanLeVat,
  SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG) END) AS VON
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT

'||P_TABLE_GROUPBY||'
WHERE
     t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
    order by t.NGAYCHUNGTU DESC ) a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPBANBUONTRALAICHITIET;
END NVPHIEU;