create or replace PROCEDURE            "FILTER_EXTERNALCODE_KIEMKE" 
(
  P_MADONVI IN VARCHAR2 ,
  P_TABLE IN VARCHAR2,
  P_MAKHO IN VARCHAR2,
  EXTERNALCODE OUT SYS_REFCURSOR
) AS
  SQL_QUERRY VARCHAR(32264);
BEGIN 
    SQL_QUERRY :=  'SELECT C.ID,C.MAVATTU,C.TENVATTU,C.MAKEHANG,C.MALOAIVATTU,C.MANHOMVATTU,C.MAKHACHHANG,C.BARCODE,D.MAKHO,
    NVL(D.TONDAUKYSL,0) AS TONDAUKYSL,NVL(D.TONDAUKYGT,0) AS TONDAUKYGT,NVL(D.NHAPSL,0) AS NHAPSL,NVL(D.NHAPGT,0) AS NHAPGT,NVL(D.XUATSL,0) AS XUATSL,NVL(D.XUATGT,0) AS XUATGT,NVL(D.TONCUOIKYSL,0) AS TONCUOIKYSL,
    NVL(D.TONCUOIKYGT,0) AS TONCUOIKYGT,NVL(D.GIAVON,0) AS GIAVON FROM
(SELECT A.ID,A.MAVATTU,A.TENVATTU,A.MAKEHANG,A.MALOAIVATTU,A.MANHOMVATTU,A.MAKHACHHANG,A.BARCODE
FROM DMVATTU A LEFT JOIN NVKIEMKECHITIET B ON A.MAVATTU = B.MAVATTU WHERE B.KEKIEMKE IS NULL) C 
INNER JOIN '||P_TABLE||' D ON C.MAVATTU = D.MAVATTU AND D.MAKHO = '''||P_MAKHO||''' AND D.UNITCODE = '''||P_MADONVI||''' AND D.TONDAUKYSL != 0';        
BEGIN
OPEN EXTERNALCODE FOR SQL_QUERRY;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (SQL_QUERRY  || SQLERRM);
END;
END FILTER_EXTERNALCODE_KIEMKE;


 
 