create or replace PROCEDURE HISTORYBUYOFCUSTOMER
(
  P_TUNGAY IN DATE,
  P_DENNGAY IN DATE,
  P_MADONVI IN VARCHAR2,
  P_MAKHACHHANG IN VARCHAR2,
  RETURN_DATA OUT SYS_REFCURSOR
) AS
  SQL_QUERRY VARCHAR(32264);
  P_WHERE VARCHAR(32264);
BEGIN

IF( P_MAKHACHHANG IS NOT NULL) THEN P_WHERE:= ' AND t.MAKHACHHANG = '''||P_MAKHACHHANG||''' ';
END IF;
SQL_QUERRY:= 'SELECT a.MA AS MA, a.TEN AS TEN, TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI, TO_CHAR(a.TIENCHIETKHAU) AS TIENCHIETKHAU,
    TO_CHAR(a.TIENVOUCHER) AS TIENVOUCHER,  TO_CHAR(a.TIENTHE) AS TIENTHE,TO_CHAR(a.TIENCOD) AS TIENCOD,TO_CHAR(a.TIENMAT) AS TIENMAT,TO_CHAR(a.TTIENCOVAT) AS TTIENCOVAT
    FROM (
    SELECT   b.MAVATTU AS MA, b.TENVATTU AS TEN,t.NGAYPHATSINH AS NGAYPHATSINH, t.MAKHACHHANG AS MaKhachHang, t.UNITCODE
                              ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                              ,SUM(NVL(ct.TIENKHUYENMAI, 0)) AS TIENKHUYENMAI
                              ,SUM(NVL(ct.TIENCHIETKHAU, 0)) AS TIENCHIETKHAU
                              ,SUM(NVL(ct.TIENVOUCHER, 0)) AS TIENVOUCHER
                              ,SUM(NVL(t.TIENTHE, 0)) AS TIENTHE
                              ,SUM(NVL(t.TIENCOD, 0)) AS TIENCOD
                              ,SUM(NVL(t.TIENMAT, 0)) AS TIENMAT
                              ,SUM(NVL(t.TTIENCOVAT, 0)) AS TTIENCOVAT
    from NVHANGGDQUAY_ASYNCCLIENT ct 
    inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
    left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.MADONVI,0,3)
    WHERE
        t.LOAIGIAODICH = 1
        AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
        AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
        '||P_WHERE||'
        group by b.MAVATTU, b.TENVATTU,  b.MAKHACHHANG,t.NGAYPHATSINH,t.MAKHACHHANG,t.UNITCODE
         ORDER BY t.NGAYPHATSINH DESC
         ) a';
BEGIN
OPEN RETURN_DATA FOR SQL_QUERRY;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('ERROR' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR OTHER' || SQL_QUERRY  || SQLERRM);
END;
END HISTORYBUYOFCUSTOMER;
/