create or replace PROCEDURE            "PC_VATTU_COUNT" 
(
  P_MADONVI IN VARCHAR2 ,
  P_STRKEY IN VARCHAR2,
  P_SUBQUERY IN VARCHAR2,
  P_PAGENUMBER IN NUMBER,
  P_PAGESIZE IN NUMBER,
  P_TOTALITEM OUT NUMBER,
 cur OUT SYS_REFCURSOR
) AS 
P NUMBER;
STR_COUNT VARCHAR2(32264);
STR_QUERY VARCHAR2(32264);
BEGIN

BEGIN
STR_COUNT:= 'SELECT count(MAHANG)  FROM V_VATTU_GIABAN vt  WHERE 1=1 ';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_COUNT := STR_COUNT|| ' AND MaDonVi = '''||P_MADONVI||'''';
END IF;
IF TRIM(P_SUBQUERY) IS NOT NULL THEN
STR_COUNT := STR_COUNT || '  '||P_SUBQUERY;
END IF;
 OPEN cur FOR STR_COUNT;    
EXCEPTION WHEN OTHERS THEN 
goto countinus;
END;
<<countinus>>
NULL;
END PC_VATTU_COUNT;
/
create or replace PROCEDURE            "PC_VATTU_SEARCH" 
(
  P_MADONVI IN VARCHAR2 ,
  P_STRKEY IN VARCHAR2,
  P_SUBQUERY IN VARCHAR2,
 cur OUT SYS_REFCURSOR
) AS 
STR_QUERY VARCHAR2(32264);
BEGIN

STR_QUERY:=  'SELECT * FROM V_VATTU_GIABAN WHERE 1=1';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_QUERY:= STR_QUERY|| ' AND MaDonVi = '''||P_MADONVI||'''';
END IF;
IF TRIM(P_SUBQUERY) IS NOT NULL THEN
STR_QUERY := STR_QUERY || '  '||P_SUBQUERY;
END IF;
        DBMS_OUTPUT.PUT_LINE(STR_QUERY);
        OPEN cur FOR STR_QUERY;    
        EXCEPTION WHEN OTHERS THEN COMMIT;
END PC_VATTU_SEARCH;
/
create or replace PROCEDURE            "PC_VATTU_SEARCH_PAGING" 
(
  P_MADONVI IN VARCHAR2 ,
  P_STRKEY IN VARCHAR2,
  P_SUBQUERY IN VARCHAR2,
  P_PAGENUMBER IN NUMBER,
  P_PAGESIZE IN NUMBER,
  P_TOTALITEM OUT NUMBER,
  
 cur OUT SYS_REFCURSOR
) AS 
STR_COUNT VARCHAR2(32264);
STR_QUERY VARCHAR2(32264);
BEGIN

STR_QUERY:=  'SELECT vt.*  FROM V_VATTU_GIABAN vt  WHERE 1=1 ';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_QUERY:= STR_QUERY|| ' AND MaDonVi = '''||P_MADONVI||'''';
END IF;
IF TRIM(P_SUBQUERY) IS NOT NULL THEN
STR_QUERY := STR_QUERY || '  '||P_SUBQUERY;
END IF;

BEGIN
STR_COUNT:= 'SELECT count(MAHANG) INTO P_TOTALITEM  FROM V_VATTU_GIABAN vt  WHERE 1=1 ';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_COUNT:= STR_COUNT|| ' AND MaDonVi = '''||P_MADONVI||'''';
END IF;
IF TRIM(P_SUBQUERY) IS NOT NULL THEN
STR_COUNT := STR_COUNT || '  '||P_SUBQUERY;
END IF;
execute immediate STR_COUNT;
EXCEPTION WHEN OTHERS THEN 
goto countinus;
END;
<<countinus>>
STR_QUERY:= 'SELECT * FROM
(
    SELECT a.*, rownum r__
    FROM
    (
        '||STR_QUERY||'
    ) a
    WHERE rownum < (('||P_PAGENUMBER||' * '||P_PAGESIZE||') + 1 )
)
WHERE r__ >= ((('||P_PAGENUMBER||'-1) * '||P_PAGESIZE||') + 1)';

        DBMS_OUTPUT.PUT_LINE(STR_QUERY);
        OPEN cur FOR STR_QUERY;    
        EXCEPTION WHEN OTHERS THEN COMMIT;
END PC_VATTU_SEARCH_PAGING;
/
create or replace PROCEDURE            "PC_VATTU_SEARCH_SYNC" 
(
  P_MADONVI IN VARCHAR2 ,
  P_STRKEY IN VARCHAR2
, cur OUT SYS_REFCURSOR
) AS 
STR_QUERY VARCHAR2(32264);
BEGIN

STR_QUERY:=  'SELECT * FROM V_VATTU_GIABAN WHERE I_STATE=50';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_QUERY:= STR_QUERY|| ' AND MaDonVi = '''||P_MADONVI||'''';
END IF;

        DBMS_OUTPUT.PUT_LINE(STR_QUERY);
        OPEN cur FOR STR_QUERY;    
        EXCEPTION WHEN OTHERS THEN COMMIT;
END PC_VATTU_SEARCH_SYNC;
/

 
 
 
 