create or replace PROCEDURE            "PC_VATTU_COUNT" 
(
  P_MADONVI IN VARCHAR2 ,
  P_STRKEY IN VARCHAR2,
  P_SUBQUERY IN VARCHAR2,
  P_PAGENUMBER IN NUMBER,
  P_PAGESIZE IN NUMBER,
  P_TOTALITEM OUT NUMBER,
 cur OUT SYS_REFCURSOR
) AS 
P NUMBER;
STR_COUNT VARCHAR2(32264);
STR_QUERY VARCHAR2(32264);
BEGIN

BEGIN
STR_COUNT:= 'SELECT count(MAHANG)  FROM V_VATTU_GIABAN vt  WHERE 1=1 ';
IF TRIM(P_MADONVI) IS NOT NULL THEN
STR_COUNT := STR_COUNT|| ' AND MaDonVi LIKE '''||P_MADONVI||'%''';
END IF;
IF TRIM(P_SUBQUERY) IS NOT NULL THEN
STR_COUNT := STR_COUNT || '  '||P_SUBQUERY;
END IF;
 OPEN cur FOR STR_COUNT;    
EXCEPTION WHEN OTHERS THEN 
goto countinus;
END;
<<countinus>>
NULL;
END PC_VATTU_COUNT;

 