create or replace PROCEDURE SEARCH_MERCHANDISE
(
  P_MADONVI IN VARCHAR2,
  STR_KEY IN VARCHAR2,
  RETURN_DATA OUT SYS_REFCURSOR
) AS
  SQL_QUERRY VARCHAR(32264);
BEGIN 
IF(REGEXP_INSTR(STR_KEY, '[[:digit:]]') > 1 OR IS_NUMBER(STR_KEY) = 1) THEN 
    SQL_QUERRY :=  'SELECT a.MAVATTU,a.TENVATTU FROM DMVATTU a WHERE UPPER(a.MAVATTU) LIKE ''%'||UPPER(STR_KEY)||'%'' AND SUBSTR(a.UNITCODE,0,3) =  SUBSTR('''||P_MADONVI||''',0,3) AND ROWNUM <= 10';    
ELSE
    SQL_QUERRY :=  'SELECT a.MAVATTU,a.TENVATTU FROM DMVATTU a WHERE UPPER(a.TENVATTU) LIKE ''%'||UPPER(STR_KEY)||'%'' AND SUBSTR(a.UNITCODE,0,3) =  SUBSTR('''||P_MADONVI||''',0,3) AND ROWNUM <= 10';
END IF;
BEGIN
DBMS_OUTPUT.put_line ('TEST:' || SQL_QUERRY);
OPEN RETURN_DATA FOR SQL_QUERRY;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('ERROR' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR OTHER' || SQL_QUERRY  || SQLERRM);
END;
END SEARCH_MERCHANDISE;
/