create or replace PROCEDURE SEARCH_CUSTOMER 
(
  P_MADONVI IN VARCHAR2,
  STR_KEY IN VARCHAR2,
  RETURN_DATA OUT SYS_REFCURSOR
) AS
  SQL_QUERRY VARCHAR(32264);
BEGIN 
IF(INSTR(STR_KEY,'KH') > 0 AND IS_NUMBER(STR_KEY) = 0) THEN 
    SQL_QUERRY :=  'SELECT * FROM DMKHACHHANG a WHERE UPPER(a.MAKH) LIKE '''||UPPER(STR_KEY)||'%'' AND SUBSTR(a.UNITCODE,0,3) =  SUBSTR('''||P_MADONVI||''',0,3)';    
ELSIF(IS_NUMBER(STR_KEY) = 1) THEN 
    SQL_QUERRY :=  'SELECT * FROM DMKHACHHANG a WHERE a.DIENTHOAI LIKE '''||STR_KEY||'%'' AND SUBSTR(a.UNITCODE,0,3) =  SUBSTR('''||P_MADONVI||''',0,3)';
ELSE 
     SQL_QUERRY :=  'SELECT * FROM DMKHACHHANG a WHERE UPPER(a.TENKH) LIKE N''%'||UPPER(STR_KEY)||'%'' AND SUBSTR(a.UNITCODE,0,3) =  SUBSTR('''||P_MADONVI||''',0,3)';
END IF;
BEGIN
DBMS_OUTPUT.put_line ('TEST:' || SQL_QUERRY);
OPEN RETURN_DATA FOR SQL_QUERRY;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('ERROR' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR OTHER' || SQL_QUERRY  || SQLERRM);
END;
END SEARCH_CUSTOMER;