  CREATE TABLESPACE "TBNETERP" DATAFILE 
  'C:\oraclexe\app\oracle\oradata\XE\TBNETERP.ora' SIZE 1G
  AUTOEXTEND ON NEXT 65536 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 524288 DEFAULT NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
  
  create user TBNETERP
  identified by "TBNETERP"
  default tablespace TBNETERP
  temporary tablespace TEMP
  profile DEFAULT;
  
grant connect to TBNETERP;
grant dba to TBNETERP;
grant delete_catalog_role to TBNETERP;
grant execute_catalog_role to TBNETERP;
grant exp_full_database to TBNETERP;
grant gather_system_statistics to TBNETERP;
grant hs_admin_role to TBNETERP;
grant imp_full_database to TBNETERP;
grant javadebugpriv to TBNETERP;
grant javasyspriv to TBNETERP;
grant java_admin to TBNETERP;
grant java_deploy to TBNETERP;
grant logstdby_administrator to TBNETERP;
grant mgmt_user to TBNETERP;
grant oem_monitor to TBNETERP;
grant olap_dba to TBNETERP;
grant olap_user to TBNETERP;
grant scheduler_admin to TBNETERP;
grant select_catalog_role to TBNETERP;
-- Grant/Revoke system privileges 
grant administer any sql tuning set to TBNETERP;
grant administer database trigger to TBNETERP;
grant administer sql tuning set to TBNETERP;
grant advisor to TBNETERP;
grant alter any cluster to TBNETERP;
grant alter any dimension to TBNETERP;
grant alter any index to TBNETERP;
grant alter any indextype to TBNETERP;
grant alter any library to TBNETERP;
grant alter any materialized view to TBNETERP;
grant alter any outline to TBNETERP;
grant alter any procedure to TBNETERP;
grant alter any role to TBNETERP;
grant alter any sequence to TBNETERP;
grant alter any sql profile to TBNETERP;
grant alter any table to TBNETERP;
grant alter any trigger to TBNETERP;
grant alter any type to TBNETERP;
grant alter database to TBNETERP;
grant alter profile to TBNETERP;
grant alter resource cost to TBNETERP;
grant alter rollback segment to TBNETERP;
grant alter session to TBNETERP;
grant alter system to TBNETERP;
grant alter tablespace to TBNETERP;
grant alter user to TBNETERP;
grant analyze any to TBNETERP;
grant analyze any dictionary to TBNETERP;
grant audit any to TBNETERP;
grant audit system to TBNETERP;
grant backup any table to TBNETERP;
grant change notification to TBNETERP;
grant comment any table to TBNETERP;
grant create any cluster to TBNETERP;
grant create any context to TBNETERP;
grant create any dimension to TBNETERP;
grant create any directory to TBNETERP;
grant create any index to TBNETERP;
grant create any indextype to TBNETERP;
grant create any job to TBNETERP;
grant create any library to TBNETERP;
grant create any materialized view to TBNETERP;
grant create any operator to TBNETERP;
grant create any outline to TBNETERP;
grant create any procedure to TBNETERP;
grant create any sequence to TBNETERP;
grant create any sql profile to TBNETERP;
grant create any synonym to TBNETERP;
grant create any table to TBNETERP;
grant create any trigger to TBNETERP;
grant create any type to TBNETERP;
grant create any view to TBNETERP;
grant create cluster to TBNETERP;
grant create database link to TBNETERP;
grant create dimension to TBNETERP;
grant create external job to TBNETERP;
grant create indextype to TBNETERP;
grant create job to TBNETERP;
grant create library to TBNETERP;
grant create materialized view to TBNETERP;
grant create operator to TBNETERP;
grant create procedure to TBNETERP;
grant create profile to TBNETERP;
grant create public database link to TBNETERP;
grant create public synonym to TBNETERP;
grant create role to TBNETERP;
grant create rollback segment to TBNETERP;
grant create sequence to TBNETERP;
grant create session to TBNETERP;
grant create synonym to TBNETERP;
grant create table to TBNETERP;
grant create tablespace to TBNETERP;
grant create trigger to TBNETERP;
grant create type to TBNETERP;
grant create user to TBNETERP;
grant create view to TBNETERP;
grant debug any procedure to TBNETERP;
grant debug connect session to TBNETERP;
grant drop any cluster to TBNETERP;
grant drop any context to TBNETERP;
grant drop any dimension to TBNETERP;
grant drop any directory to TBNETERP;
grant drop any index to TBNETERP;
grant drop any indextype to TBNETERP;
grant drop any library to TBNETERP;
grant drop any materialized view to TBNETERP;
grant drop any operator to TBNETERP;
grant drop any outline to TBNETERP;
grant drop any procedure to TBNETERP;
grant drop any role to TBNETERP;
grant drop any sequence to TBNETERP;
grant drop any sql profile to TBNETERP;
grant drop any synonym to TBNETERP;
grant drop any table to TBNETERP;
grant drop any trigger to TBNETERP;
grant drop any type to TBNETERP;
grant drop any view to TBNETERP;
grant drop profile to TBNETERP;
grant drop public database link to TBNETERP;
grant drop public synonym to TBNETERP;
grant drop rollback segment to TBNETERP;
grant drop tablespace to TBNETERP;
grant drop user to TBNETERP;
grant execute any class to TBNETERP;
grant execute any indextype to TBNETERP;
grant execute any library to TBNETERP;
grant execute any operator to TBNETERP;
grant execute any procedure to TBNETERP;
grant execute any program to TBNETERP;
grant execute any type to TBNETERP;
grant export full database to TBNETERP;
grant flashback any table to TBNETERP;
grant force any transaction to TBNETERP;
grant force transaction to TBNETERP;
grant select any dictionary to TBNETERP;
grant select any table to TBNETERP;
grant select any transaction to TBNETERP;
grant unlimited tablespace to TBNETERP;