create or replace package BAOCAO is

  -- Author  : ADMINISTRATOR
  -- Created : 25/11/2016 10:32:03 AM
  -- Purpose : Báo cáo
  
 PROCEDURE  TONGHOP_PHIEUNHAPKHO(P_SOPHIEUS IN NVARCHAR2, P_LOAIHANGS IN NVARCHAR2, P_NHOMHANGS IN NVARCHAR2,P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_RESULT OUT SYS_REFCURSOR);

end BAOCAO;
create or replace package body BAOCAO is
 PROCEDURE  TONGHOP_PHIEUNHAPKHO(P_SOPHIEUS IN NVARCHAR2, P_LOAIHANGS IN NVARCHAR2, P_NHOMHANGS IN NVARCHAR2,P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_RESULT OUT SYS_REFCURSOR) IS
   STR_QUERY VARCHAR(9300);
   STR_ADD_SOPHIEU VARCHAR(3000);
   STR_ADD_LOAIHANGS VARCHAR(3000);
   STR_ADD_NHOMHANGS VARCHAR(3000);
   STR_ADD_TUNGAY VARCHAR(100);
   STR_ADD_DENNGAY VARCHAR(100);
   STR_BETWEEN VARCHAR(100);
   BEGIN
        IF P_LOAIHANGS <> '' OR P_LOAIHANGS IS NOT NULL THEN
         STR_ADD_LOAIHANGS:='MALOAIHANG IN('''||P_LOAIHANGS||''')';
     END IF;

     IF P_NHOMHANGS <> '' OR P_NHOMHANGS IS NOT NULL THEN
         STR_ADD_NHOMHANGS:='MANHOMHANG IN('''||P_NHOMHANGS||''')';
     END IF;
     IF P_SOPHIEUS <> '' OR P_SOPHIEUS IS NOT NULL THEN
         STR_ADD_SOPHIEU:='MACHUNGTUPK IN('''||P_SOPHIEUS||''')';
       END IF;
     IF P_TUNGAY IS NOT NULL THEN
       STR_ADD_TUNGAY:= 'NGAYCHUNGTU >= '''||P_TUNGAY||'''';
     END IF;
     IF P_DENNGAY IS NOT NULL THEN
       STR_ADD_DENNGAY:= 'NGAYCHUNGTU <= '''||P_DENNGAY||'''';
     END IF;

     IF (TRIM(STR_ADD_TUNGAY) IS NOT NULL) AND (TRIM(STR_ADD_DENNGAY) IS NOT NULL) THEN

       STR_BETWEEN:= STR_ADD_TUNGAY || ' AND ' || STR_ADD_DENNGAY;
       ELSIF TRIM(STR_ADD_TUNGAY) IS NOT NULL THEN
         STR_BETWEEN:= STR_ADD_TUNGAY;
       ELSE
         STR_BETWEEN:= STR_ADD_DENNGAY;
     END IF;
     STR_QUERY:='SELECT MAHANG, TENHANG, SOLUONG, DONVITINH, DONGIA, THANHTIEN FROM VATTUCHUNGTUCHITIET A INNER JOIN VATTUCHUNGTU B ON A.MACHUNGTUPK = B.MACHUNGTUPK WHERE 1=1 ';
         IF TRIM(STR_ADD_SOPHIEU) IS NOT NULL THEN
           STR_QUERY:= STR_QUERY || ' AND ' ||STR_ADD_SOPHIEU;
          END IF;
         IF TRIM(STR_ADD_NHOMHANGS) IS NOT NULL THEN
           STR_QUERY:= STR_QUERY || ' AND ' ||STR_ADD_NHOMHANGS;
          END IF;
         IF TRIM(STR_ADD_LOAIHANGS) IS NOT NULL THEN
           STR_QUERY:= STR_QUERY || ' AND ' ||STR_ADD_LOAIHANGS;
          END IF;
          IF TRIM(STR_BETWEEN) IS NOT NULL THEN
          STR_QUERY:= STR_QUERY || ' AND ' ||STR_BETWEEN;
          END IF;
              DBMS_OUTPUT.PUT_LINE(STR_QUERY);
       OPEN P_RESULT FOR STR_QUERY;
       EXCEPTION WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('Lỗi: '||STR_QUERY);
   END TONGHOP_PHIEUNHAPKHO;
end BAOCAO;
/
