create or replace PACKAGE TONKHO AS 
PROCEDURE BAOCAO_TONKHO_THEOKHO(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_TONKHO_THEOLOAI(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_TONKHO_THEONHOM(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_TONKHO_THEOMAVATTU(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR);
END TONKHO;


CREATE OR REPLACE
PACKAGE BODY TONKHO AS

  PROCEDURE BAOCAO_TONKHO_THEOKHO(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR) AS
  QUERY_STR VARCHAR(32767);
  BEGIN

QUERY_STR:= 'select a.makho as Code,
                                    SUM(a.toncuoikysl) as ClosingQuantity, SUM(a.toncuoikygt) as ClosingValue
                                    from '||P_TABLENAME||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 and a.unitcode ='''||P_UNITCODE||'''';
                                    
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN

QUERY_STR := QUERY_STR||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;  
QUERY_STR := QUERY_STR||' GROUP BY a.makho';         
OPEN XTNCOLLECTION FOR QUERY_STR;                                    
                                    
END BAOCAO_TONKHO_THEOKHO;
  PROCEDURE BAOCAO_TONKHO_THEOLOAI(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR) AS
  QUERY_STR VARCHAR(32767);
  BEGIN

QUERY_STR:= 'select b.maloaivattu as Code,
                                    SUM(a.toncuoikysl) as ClosingQuantity, SUM(a.toncuoikygt) as ClosingValue
                                    from '||P_TABLENAME||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 and a.unitcode ='''||P_UNITCODE||'''';
                                    
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN

QUERY_STR := QUERY_STR||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;  
QUERY_STR := QUERY_STR||' GROUP BY b.maloaivattu';         
OPEN XTNCOLLECTION FOR QUERY_STR;                                    
                                    
END BAOCAO_TONKHO_THEOLOAI;

  PROCEDURE BAOCAO_TONKHO_THEONHOM(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR) AS
  QUERY_STR VARCHAR(32767);
  BEGIN

QUERY_STR:= 'select b.manhomvattu as Code,
                                    SUM(a.toncuoikysl) as ClosingQuantity, SUM(a.toncuoikygt) as ClosingValue
                                    from '||P_TABLENAME||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 and a.unitcode ='''||P_UNITCODE||'''';
                                    
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN

QUERY_STR := QUERY_STR||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;  
QUERY_STR := QUERY_STR||' GROUP BY b.manhomvattu';         
OPEN XTNCOLLECTION FOR QUERY_STR;                                    
                                    
END BAOCAO_TONKHO_THEONHOM;

  PROCEDURE BAOCAO_TONKHO_THEOMAVATTU(P_TABLENAME IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_UNITCODE  IN VARCHAR2, XTNCOLLECTION  OUT SYS_REFCURSOR) AS
  QUERY_STR VARCHAR(32767);
  BEGIN

QUERY_STR:= 'select b.mavattu as Code,
                                    SUM(a.toncuoikysl) as ClosingQuantity, SUM(a.toncuoikygt) as ClosingValue
                                    from '||P_TABLENAME||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1';
                                    
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN

QUERY_STR := QUERY_STR||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
QUERY_STR := QUERY_STR||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;  
QUERY_STR := QUERY_STR||' GROUP BY b.mavattu';         
OPEN XTNCOLLECTION FOR QUERY_STR;                                    
                                    
END BAOCAO_TONKHO_THEOMAVATTU;

END TONKHO;