CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TMP_XTN_NGAY" 
   (	    "UNITCODE" NVARCHAR2(20),"MAKHO" NVARCHAR2(50),"MAVATTU" NVARCHAR2(50),
    "GIAVON" NUMBER(17,4) DEFAULT 0,
  "TONDAUKYSL" NUMBER(17,4) DEFAULT 0,
  "TONDAUKYGT" NUMBER(17,4) DEFAULT 0,
  "NHAPSL" NUMBER(17,4) DEFAULT 0,
    "NHAPGT" NUMBER(17,4) DEFAULT 0,
    "XUATSL" NUMBER(17,4) DEFAULT 0,
    "XUATGT" NUMBER(17,4) DEFAULT 0,
  "TONCUOIKYSL" NUMBER(17,4) DEFAULT 0, 
  "TONCUOIKYGT" NUMBER(17,4) DEFAULT 0
   ) ON COMMIT DELETE ROWS ;
   /
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TBNETERP"."VIEW_VATTUGD_XNT" ("ID", "UNITCODE", "TRANGTHAI", "LOAICHUNGTU", "NGAYCHUNGTU", "MAVATTU", "MAKHOXUAT", "MAKHONHAP", "MADONVINHAN", "MADONVIXUAT", "SOLUONG", "DONGIA", "THANHTIEN", "NGUOITAO", "MAMAYBAN") AS 
  SELECT VATTUCHUNGTU.ID, UNITCODE,
	   TRANGTHAI,
       LOAICHUNGTU,
       TO_DATE(NGAYDUYETPHIEU,'DD/MM/YY') AS NGAYCHUNGTU,
	   VATTUCHUNGTUCHITIET.MAHANG as MAVATTU,
       MAKHOXUAT,
       MAKHONHAP,
       MADONVINHAN,
       MADONVIXUAT,
       SOLUONG,
       DONGIA,
       THANHTIEN,
	   I_CREATE_BY AS NGUOITAO,
	   TO_NCHAR('') AS MAMAYBAN
  FROM VATTUCHUNGTU
       INNER JOIN VATTUCHUNGTUCHITIET
          ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
          WHERE TRANGTHAI=10
UNION ALL
SELECT a.ID AS ID, TO_NCHAR('DV1-CH1') AS UNITCODE,
	   10 AS TRANGTHAI,
       TO_NCHAR(LOAIGIAODICH) AS LOAICHUNGTU,
       TO_DATE(a.NGAYPHATSINH,'DD/MM/YY') AS NGAYCHUNGTU,
	   ct.MAVATTU AS MAVATTU,
       TO_NCHAR('DV1-CH1-K2') AS MAKHOXUAT,
       TO_NCHAR('DV1-CH1-K2') AS MAKHONHAP,
       TO_NCHAR('DV1-CH1') as MADONVINHAN,
       TO_NCHAR('DV1-CH1') as MADONVIXUAT,
       ct.SOLUONG AS SOLUONG,
       ct.GIABANLECOVAT/(1 + VATBAN/100) DONGIA,
       ct.TTIENCOVAT AS THANHTIEN,
        TO_NCHAR(a.NGUOITAO) AS NGUOITAO,
	   TO_NCHAR(a.MAQUAYBAN) AS MAMAYBAN
  FROM NVGDQUAY_ASYNCCLIENT a
       INNER JOIN NVHANGGDQUAY_ASYNCCLIENT ct
          ON (a.MAGIAODICHQUAYPK = ct.MAGDQUAYPK)
  UNION ALL
SELECT kkct.ID AS ID, TO_NCHAR(kkct.MADONVI) AS UNITCODE,kk.TRANGTHAI AS TRANGTHAI,
    TO_NCHAR(SUBSTR(kk.MAPHIEUKIEMKE,0,4)) AS LOAICHUNGTU, TO_DATE(kk.NGAYDUYETPHIEU,'DD/MM/YY') AS NGAYCHUNGTU,
    kkct.MAVATTU AS MAVATTU, TO_NCHAR(kkct.KHOKIEMKE) AS MAKHOXUAT, TO_NCHAR(kk.KHOKIEMKE) AS MAKHONHAP,
    TO_NCHAR(kkct.MADONVI) AS MADONVINHAN, TO_NCHAR(kkct.MADONVI) AS MADONVIXUAT,
    kkct.SOLUONGCHENHLECH AS SOLUONG, kkct.GIAVON AS DONGIA, kkct.TIENCHENHLECH AS THANHTIEN,
    TO_NCHAR(kk.NGUOITAO) AS NGUOITAO, TO_NCHAR('KEKIEMKE') AS MAMAYBAN
    FROM NVKIEMKE kk INNER JOIN NVKIEMKECHITIET kkct 
    ON (kk.MAPHIEUKIEMKE = kkct.MAPHIEUKIEMKE);
		  /
create or replace PACKAGE "XNT" AS 
--------------------------
--Version: 11
--Create by: Dao Viet Duong
--Edit: Nguyen Quang Huy: Update Gia Von
--UpdateDate: 15h20m: 13-03-2017
--------------------------
PROCEDURE XNT_CREATE_TABLE_TONKY(P_TABLENAME_KYTRUOC IN VARCHAR2,P_TABLENAME IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_NAM IN NUMBER,P_KY IN NUMBER);
PROCEDURE XNT_KHOASO(P_TABLENAME_KYTRUOC IN VARCHAR2,P_TABLENAME IN VARCHAR2, P_UNITCODE IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER);
PROCEDURE XNT_TANG_TONKY(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE);
PROCEDURE XNT_GIAM_TONKY(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE);
PROCEDURE XNT_TANG_TONKY_KIEMKE(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE );
PROCEDURE XNT_GIAM_TONKY_KIEMKE(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE);
PROCEDURE UPDATE_GIAVON_AM(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER);
PROCEDURE XNT_TANG_PHIEU(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2);
PROCEDURE XNT_GIAM_PHIEU(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2);
PROCEDURE BAOCAO_XNT_TONGHOP(P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XNT_CHITIET(P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);  
PROCEDURE CAPNHAT_GIAVON_QUAYGIAODICH(P_TABLENAME IN VARCHAR, P_UNITCODE  IN VARCHAR2, P_NGAYPHATSINH IN DATE);
PROCEDURE XNT_TANGPHIEU_KIEMKE(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2);
PROCEDURE XNT_GIAMPHIEU_KIEMKE(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2);
END XNT;


 /
create or replace PACKAGE BODY  "XNT" AS
--------------------------
--Version: 12
--Create by: Dao Viet Duong
--Edit: Nguyen Quang Huy: Update GIA VON VATTUCHUNGTUCHITIET
--UpdateDate: 17H: 16-03-2017
--------------------------

PROCEDURE XNT_CREATE_TABLE_TONKY(P_TABLENAME_KYTRUOC IN VARCHAR2, P_TABLENAME  IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_NAM  IN NUMBER,P_KY  IN NUMBER) IS
   P_SQL  VARCHAR2(32767);  
   P_SQL_INSERT  VARCHAR2(32767);  
   P_SQL_DELETE VARCHAR2(32767);  
   N_COUNT NUMBER(17,4):=0;
   BEGIN
    P_SQL := 'CREATE TABLE '||P_TABLENAME||'(
    "UNITCODE" NVARCHAR2(20), "NAM" NVARCHAR2(50),"KY" NVARCHAR2(200),"MAKHO" NVARCHAR2(50),"MAVATTU" NVARCHAR2(50),
    "GIAVON" NUMBER(17,4) DEFAULT 0,
  "TONDAUKYSL" NUMBER(17,4) DEFAULT 0,
  "TONDAUKYGT" NUMBER(17,4) DEFAULT 0,
  "NHAPSL" NUMBER(17,4) DEFAULT 0,
    "NHAPGT" NUMBER(17,4) DEFAULT 0,
    "XUATSL" NUMBER(17,4) DEFAULT 0,
    "XUATGT" NUMBER(17,4) DEFAULT 0,
  "TONCUOIKYSL" NUMBER(17,4) DEFAULT 0, 
  "TONCUOIKYGT" NUMBER(17,4) DEFAULT 0
 ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )';

   P_SQL_INSERT :=       'INSERT INTO '||P_TABLENAME||' a
(a.UNITCODE, a.NAM, a.KY, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONCUOIKYGT, a.TONCUOIKYSL, a.TONDAUKYGT, a.TONDAUKYSL)
SELECT UNITCODE, '||P_NAM||', '||P_KY||', MAKHO, MAVATTU, GIAVON, TONCUOIKYGT, TONCUOIKYSL, TONCUOIKYGT, TONCUOIKYSL FROM '||P_TABLENAME_KYTRUOC||' b WHERE b.UNITCODE = '''|| P_UNITCODE ||'''';
IF TRIM(P_TABLENAME_KYTRUOC) IS NULL THEN
 
 P_SQL_INSERT := 'DECLARE CURSOR KHO_Table IS SELECT MAKHO FROM DMKHO WHERE UNITCODE=''' || P_UNITCODE || ''';
        BEGIN FOR KHO_Entiy IN KHO_Table LOOP
         BEGIN 
            INSERT INTO '|| P_TABLENAME ||'(UNITCODE,NAM,KY,MAKHO,MAVATTU) 
             SELECT '''|| P_UNITCODE ||''' AS UNITCODE,'||P_NAM||' AS NAM,'||P_KY||' AS KY,KHO_Entiy.MAKHO AS MAKHO,MAVATTU FROM DMVATTU;
          END;
         END LOOP;
        END;';
        END IF;
  BEGIN
    SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME);
    EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
  END;
  IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN
        DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT);
        EXECUTE IMMEDIATE P_SQL;    
    END;
    END IF;  
	BEGIN
	P_SQL_DELETE:='DELETE FROM '||P_TABLENAME||' WHERE UNITCODE=''' || P_UNITCODE || '''';
	EXECUTE IMMEDIATE P_SQL_DELETE;   
	EXECUTE IMMEDIATE P_SQL_INSERT;   
	END;
	 
END XNT_CREATE_TABLE_TONKY;


PROCEDURE XNT_TANG_TONKY(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE ) IS
    N_SQL_INSERT VARCHAR(32767);
	STR_IF_REFUND VARCHAR(32767);
BEGIN
	STR_IF_REFUND := 'SELECT MAVATTU,MAKHONHAP,UNITCODE,SUM(SOLUONG) AS SOLUONG,SUM(SOLUONG*DONGIA) AS NHAPGT FROM VIEW_VATTUGD_XNT V WHERE 
    UNITCODE='''||P_MADONVI||''' AND 
    LOAICHUNGTU='''||P_MANHOMPTNX||''' AND TRANGTHAI=10
    AND NGAYCHUNGTU <=TO_DATE('''|| P_DENNGAY ||''',''DD/MM/YY'')
    AND NGAYCHUNGTU >=TO_DATE('''|| P_TUNGAY ||''',''DD/MM/YY'')
    GROUP BY MAVATTU,MAKHONHAP,UNITCODE ;';
	IF P_MANHOMPTNX = '2' THEN
	BEGIN
	STR_IF_REFUND := 'SELECT B.MAVATTU, B.MAKHONHAP, B.UNITCODE,B.SOLUONG AS SOLUONG, 
	CASE  WHEN P.GIAVON =  0 THEN NVL(G.GIAMUA, 0)*B.SOLUONG 
	ELSE P.GIAVON*B.SOLUONG END AS NHAPGT FROM
    (SELECT MAVATTU, MAKHONHAP, UNITCODE, SUM(SOLUONG) AS SOLUONG, SUM(DONGIA*SOLUONG) AS NHAPGT FROM
    VIEW_VATTUGD_XNT WHERE 
    LOAICHUNGTU='''||P_MANHOMPTNX||''' AND TRANGTHAI=10
    AND NGAYCHUNGTU <=TO_DATE('''|| P_DENNGAY ||''',''DD/MM/YY'')
    AND NGAYCHUNGTU >=TO_DATE('''|| P_TUNGAY ||''',''DD/MM/YY'')
    GROUP BY MAVATTU,MAKHONHAP,UNITCODE) B
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHONHAP = P.MAKHO AND B.UNITCODE = P.UNITCODE 
	LEFT JOIN DM_VATTU_GIACA G ON B.MAVATTU = G.MAVATTU AND B.UNITCODE = G.MADONVI ;
	';
	END;
	END IF;
  N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS 
	'||STR_IF_REFUND||'
   
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHONHAP AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHONHAP AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
     
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      NHAPSL=NHAPSL+VT_INDEX.SOLUONG, 
	  NHAPGT=NHAPGT+VT_INDEX.NHAPGT, 
	  TONCUOIKYSL=TONCUOIKYSL+VT_INDEX.SOLUONG, 
	  TONCUOIKYGT=TONCUOIKYGT+VT_INDEX.NHAPGT,
	  GIAVON = 
    CASE (TONCUOIKYSL+VT_INDEX.SOLUONG) 
    WHEN 0 THEN NVL((SELECT GIAMUA FROM DM_VATTU_GIACA WHERE MAVATTU = VT_INDEX.MAVATTU AND MADONVI =VT_INDEX.UNITCODE), 0)
    ELSE ( ABS(NVL(TONCUOIKYGT, 0))+ ABS(NVL(VT_INDEX.NHAPGT, 0)) )/( ABS(NVL(TONCUOIKYSL, 0)) + ABS(NVL(VT_INDEX.SOLUONG, 0)) ) END
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHONHAP; 
        COMMIT;
    END;
  
    END LOOP; 
    END;';
    
        --DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);
END XNT_TANG_TONKY;
---------------------------------------------------

---------------------------------------------------
PROCEDURE XNT_GIAM_TONKY(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE ) IS
    N_SQL_INSERT VARCHAR(32767);
  BEGIN
    N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS    
	 SELECT B.MAVATTU, B.MAKHOXUAT, B.UNITCODE,B.SOLUONG AS SOLUONG,
	 CASE  WHEN P.GIAVON =  0 THEN NVL(G.GIAMUA, 0)*B.SOLUONG 
	 ELSE P.GIAVON*B.SOLUONG END AS XUATGT FROM
    (SELECT MAVATTU, MAKHOXUAT, UNITCODE, SUM(SOLUONG) AS SOLUONG, SUM(DONGIA*SOLUONG) AS XUATGT FROM
    VIEW_VATTUGD_XNT WHERE 
    LOAICHUNGTU='''||P_MANHOMPTNX||''' AND TRANGTHAI=10
    AND NGAYCHUNGTU <=TO_DATE('''|| P_DENNGAY ||''',''DD/MM/YY'')
    AND NGAYCHUNGTU >=TO_DATE('''|| P_TUNGAY ||''',''DD/MM/YY'')
    GROUP BY MAVATTU,MAKHOXUAT,UNITCODE) B
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHOXUAT = P.MAKHO AND B.UNITCODE = P.UNITCODE 
	LEFT JOIN DM_VATTU_GIACA G ON B.MAVATTU = G.MAVATTU AND B.UNITCODE = G.MADONVI;
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHOXUAT AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHOXUAT AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      XUATSL=NVL(XUATSL,0)+NVL(VT_INDEX.SOLUONG,0), XUATGT=NVL(XUATGT,0)+NVL(VT_INDEX.XUATGT,0), TONCUOIKYSL=NVL(TONCUOIKYSL,0)-NVL(VT_INDEX.SOLUONG,0) ,TONCUOIKYGT=NVL(TONCUOIKYGT,0)-NVL(VT_INDEX.XUATGT,0)
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHOXUAT;      
        COMMIT;
    END;
    END LOOP; 
    END;';
        DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN COMMIT;
  END XNT_GIAM_TONKY;
  
   PROCEDURE XNT_TANG_TONKY_KIEMKE(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE ) IS
    N_SQL_INSERT VARCHAR(32767);
	STR_IF_REFUND VARCHAR(32767);
BEGIN
	STR_IF_REFUND := 'SELECT MAVATTU,MAKHONHAP,UNITCODE,SUM(ABS(SOLUONG)) AS SOLUONG,SUM(ABS(SOLUONG)*DONGIA) AS NHAPGT FROM VIEW_VATTUGD_XNT V WHERE 
    UNITCODE='''||P_MADONVI||''' AND 
    LOAICHUNGTU='''||P_MANHOMPTNX||''' AND TRANGTHAI=10
    AND SOLUONG < 0 AND NGAYCHUNGTU <=TO_DATE('''|| P_DENNGAY ||''',''DD/MM/YY'')
    AND NGAYCHUNGTU >=TO_DATE('''|| P_TUNGAY ||''',''DD/MM/YY'')
    GROUP BY MAVATTU,MAKHONHAP,UNITCODE ;';
    
  N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS 
	'||STR_IF_REFUND||'
   
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHONHAP AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHONHAP AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
     
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      NHAPSL=NHAPSL+VT_INDEX.SOLUONG, 
	  NHAPGT=NHAPGT+VT_INDEX.NHAPGT, 
	  TONCUOIKYSL=TONCUOIKYSL+VT_INDEX.SOLUONG, 
	  TONCUOIKYGT=TONCUOIKYGT+VT_INDEX.NHAPGT,
	  GIAVON = 
    CASE (TONCUOIKYSL+VT_INDEX.SOLUONG) 
    WHEN 0 THEN NVL((SELECT GIAMUA FROM DM_VATTU_GIACA WHERE MAVATTU = VT_INDEX.MAVATTU AND MADONVI =VT_INDEX.UNITCODE), 0)
    ELSE ( ABS(NVL(TONCUOIKYGT, 0))+ ABS(NVL(VT_INDEX.NHAPGT, 0)) )/( ABS(NVL(TONCUOIKYSL, 0)) + ABS(NVL(VT_INDEX.SOLUONG, 0)) ) END
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHONHAP; 
        COMMIT;
    END;
    END LOOP; 
    END;';
        DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);
END XNT_TANG_TONKY_KIEMKE;
  
  
PROCEDURE XNT_GIAM_TONKY_KIEMKE(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_MANHOMPTNX IN VARCHAR2,P_TUNGAY DATE,P_DENNGAY DATE ) IS
    N_SQL_INSERT VARCHAR(32767);
  BEGIN
    N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS    
	 SELECT B.MAVATTU, B.MAKHOXUAT, B.UNITCODE,ABS(B.SOLUONG) AS SOLUONG,
	 CASE  WHEN P.GIAVON =  0 THEN NVL(G.GIAMUA, 0)*ABS(B.SOLUONG) 
	 ELSE P.GIAVON*ABS(B.SOLUONG) END AS XUATGT FROM
    (SELECT MAVATTU, MAKHOXUAT, UNITCODE, SUM(ABS(SOLUONG)) AS SOLUONG, SUM(DONGIA*ABS(SOLUONG)) AS XUATGT FROM
    VIEW_VATTUGD_XNT WHERE 
    LOAICHUNGTU='''||P_MANHOMPTNX||''' AND TRANGTHAI=10
    AND SOLUONG > 0 AND NGAYCHUNGTU <=TO_DATE('''|| P_DENNGAY ||''',''DD/MM/YY'')
    AND NGAYCHUNGTU >=TO_DATE('''|| P_TUNGAY ||''',''DD/MM/YY'')
    GROUP BY MAVATTU,MAKHOXUAT,UNITCODE) B
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHOXUAT = P.MAKHO AND B.UNITCODE = P.UNITCODE 
	LEFT JOIN DM_VATTU_GIACA G ON B.MAVATTU = G.MAVATTU AND B.UNITCODE = G.MADONVI;
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHOXUAT AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHOXUAT AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      XUATSL=XUATSL+VT_INDEX.SOLUONG, XUATGT=XUATGT+VT_INDEX.XUATGT, TONCUOIKYSL=TONCUOIKYSL-VT_INDEX.SOLUONG,TONCUOIKYGT=TONCUOIKYGT-VT_INDEX.XUATGT
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHOXUAT;      
        COMMIT;
    END;
    END LOOP; 
    END;';
        --DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN COMMIT;
  END XNT_GIAM_TONKY_KIEMKE;
  
  PROCEDURE XNT_KHOASO(P_TABLENAME_KYTRUOC IN VARCHAR2,P_TABLENAME IN VARCHAR2, P_UNITCODE IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER)IS
    P_TUNGAY DATE;
    P_DENNGAY DATE;
    N_COUNT NUMBER;
    BEGIN
      SELECT TO_DATE(TUNGAY,'DD/MM/YY') AS TUNGAY,TO_DATE(DENNGAY,'DD/MM/YY') AS DENNGAY  INTO P_TUNGAY,P_DENNGAY FROM DMKYKETOAN WHERE KY=P_KY AND NAM=P_NAM AND UNITCODE=P_UNITCODE;
      SELECT COUNT(*) INTO N_COUNT FROM DMTHEODOITIENTRINH WHERE PROCESSCODE = 'KHOASO' AND UNITCODE = P_UNITCODE;
      IF N_COUNT = 0 THEN
      INSERT INTO DMTHEODOITIENTRINH (ID, PROCESSCODE, DESCRIPTION, STATE, UNITCODE) VALUES (SYS_GUID(), 'KHOASO', 'TIẾN TRÌNH KHÓA SỔ', 0, P_UNITCODE);
      END IF;
      UPDATE DMTHEODOITIENTRINH SET
      STATE = 20 -- IS RUNNING
      WHERE PROCESSCODE = 'KHOASO' AND UNITCODE = P_UNITCODE;
      BEGIN
        XNT_CREATE_TABLE_TONKY(P_TABLENAME_KYTRUOC,P_TABLENAME, P_UNITCODE, P_NAM, P_KY);     
        XNT_TANG_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, '2',P_TUNGAY,P_DENNGAY);
        XNT_TANG_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'NMUA',P_TUNGAY,P_DENNGAY);
        XNT_TANG_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'NHBANTL',P_TUNGAY,P_DENNGAY);
        XNT_TANG_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'DCN',P_TUNGAY,P_DENNGAY);
        XNT_TANG_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'NKHAC',P_TUNGAY,P_DENNGAY);
        XNT_TANG_TONKY_KIEMKE(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'N_KK',P_TUNGAY,P_DENNGAY);
        --update gia von am by PHAMTUANANH
        -- xuat
        XNT_GIAM_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, '1',P_TUNGAY,P_DENNGAY);
        XNT_GIAM_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'XBAN',P_TUNGAY,P_DENNGAY);
		    XNT_GIAM_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'XBANLE',P_TUNGAY,P_DENNGAY);
		    XNT_GIAM_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'XKHAC',P_TUNGAY,P_DENNGAY);
        XNT_GIAM_TONKY(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'DCX',P_TUNGAY,P_DENNGAY);
        XNT_GIAM_TONKY_KIEMKE(P_TABLENAME, P_UNITCODE, P_NAM, P_KY, 'N_KK',P_TUNGAY,P_DENNGAY);
    
    UPDATE_TONCUOIKYSL(P_TABLENAME,P_UNITCODE,P_NAM,P_KY);
      UPDATE DMTHEODOITIENTRINH SET
      STATE = 0 -- IS COMPLETE
      WHERE PROCESSCODE = 'KHOASO' AND UNITCODE = P_UNITCODE;   
      END;
    
      END XNT_KHOASO;

---------------------------------------------
PROCEDURE UPDATE_TONCUOIKYSL(P_TABLENAME IN VARCHAR2, P_MADONVI IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER) IS
  N_SQL_UPDATE VARCHAR(32767);
	STR_IF_REFUND VARCHAR(32767);
BEGIN
	STR_IF_REFUND := 'SELECT UNITCODE,NAM,KY,MAKHO,MAVATTU,GIAVON,TONDAUKYSL,TONDAUKYGT,NHAPSL
  ,NHAPGT,XUATSL,XUATGT,TONCUOIKYSL,TONCUOIKYGT FROM '||P_TABLENAME||' WHERE 
    UNITCODE='''||P_MADONVI||'''
    AND KY = '''||P_KY||'''
    AND TONCUOIKYSL = 0 AND TONCUOIKYGT <> 0
    GROUP BY UNITCODE,NAM,KY,MAKHO,MAVATTU,GIAVON,TONDAUKYSL,TONDAUKYGT,NHAPSL,NHAPGT,XUATSL,XUATGT,TONCUOIKYSL,TONCUOIKYGT;';
    N_SQL_UPDATE:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR TONCUOIBANG0 IS '||STR_IF_REFUND||'
  BEGIN FOR VT_INDEX IN TONCUOIBANG0 LOOP  
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
        TONCUOIKYGT = 0 WHERE UNITCODE =VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHO;
            COMMIT;
        END;
    END LOOP; 
    END;';
        DBMS_OUTPUT.PUT_LINE(N_SQL_UPDATE);        
      EXECUTE IMMEDIATE N_SQL_UPDATE;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);
END UPDATE_TONCUOIKYSL;
---------------------------------------------

PROCEDURE BAOCAO_XNT_TONGHOP(P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
KY_KETTHUC NUMBER;
NAM_KETTHUC NUMBER;
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION VARCHAR(3232);
P_SQL_INSERT VARCHAR(32767);
N NUMBER:= 0;
BEGIN
FOR cur_period in (SELECT to_date(P_TUNGAY, 'dd/MM/yyyy') + LEVEL - 1 AS today
FROM dual
CONNECT BY LEVEL <= to_date(P_DENNGAY, 'dd/MM/yyyy') - to_date(P_TUNGAY, 'dd/MM/yyyy') + 1) LOOP
BEGIN

BEGIN--Tìm kỳ
SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE to_date(DENNGAY, 'dd/MM/yyyy') = to_date(cur_period.today, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
   EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
END;--End Tìm ky

BEGIN --Bắt đầu thực thi nhiệm vu
N:=N+1;
IF (N = 1) THEN
BEGIN -- Bản ghi đầu tiên
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON, TONDAUKYSL, TONDAUKYGT, NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONDAUKYSL, a.TONDAUKYGT, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 
		 ';
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;   
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
ELSE
BEGIN --Vòng thứ 2 trở đi
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON,NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAVATTU IN ('||P_MAVATTU||')';
END IF;     
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;           
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
END IF;
END;--Kết thúc vong 2 trở đi;
  
END;
        <<end_loop>>
        null;      
END LOOP;
IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKHO AS Code, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MANHOMVTU, c.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' c.MANHOMVTU AS Code, c.TENNHOMVT AS Ten ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON b.MANHOMVATTU = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MALOAIVATTU, c.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' c.MALOAIVATTU AS Code, c.TENLOAIVT AS Ten ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON b.MALOAIVATTU = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKH, c.TENKH';
P_SELECT_COLUMNS_GROUPBY:= ' c.MAKH AS Code, c.TENKH AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON b.MAKHACHHANG = c.MAKH ';
P_EXPRESSION:= ' AND c.LOAIKHACHHANG = 1';
  IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
  P_EXPRESSION := P_EXPRESSION || ' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||') ';
  END IF;
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU';
P_SELECT_COLUMNS_GROUPBY:= ' b.MAVATTU AS Code, b.TENVATTU AS Ten ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;
QUERY_STR:= 'select '||P_SELECT_COLUMNS_GROUPBY||', 
                                    SUM(a.tondaukysl)  as OpeningBalanceQuantity,
                                    SUM(a.tondaukygt) as OpeningBalanceValue,
                                    SUM(a.nhapsl) as IncreaseQuantity, SUM(a.nhapgt) as IncreaseValue,
                                    SUM(a.xuatsl) as DecreaseQuantity, SUM(a.xuatgt) as DecreaseValue,
                                    SUM(a.tondaukysl - a.xuatsl + a.nhapsl) as ClosingQuantity, 
                                    SUM(a.tondaukygt - a.xuatgt + a.nhapgt) as ClosingValue
                                    from TMP_XTN_NGAY a 
                                    left join dmvattu b on a.Mavattu = b.mavattu 
                                    '||P_TABLE_GROUPBY||'
                                    WHERE 1=1 
									'||P_EXPRESSION||'
									and (a.tondaukysl * a.tondaukysl) + (a.nhapsl * a.nhapsl) + (a.xuatsl * a.xuatsl) + (a.toncuoikysl* a.toncuoikysl) > 0 ';
QUERY_STR := QUERY_STR||' GROUP BY '||P_COLUMNS_GROUPBY;    
BEGIN
OPEN XTNCOLLECTION FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);
END;
END BAOCAO_XNT_TONGHOP;


PROCEDURE BAOCAO_XNT_CHITIET(P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
KY_KETTHUC NUMBER;
NAM_KETTHUC NUMBER;
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION VARCHAR(3232);
P_SQL_INSERT VARCHAR(32767);
N NUMBER:=0;
BEGIN
FOR cur_period in (SELECT to_date(P_TUNGAY, 'dd/MM/yyyy') + LEVEL - 1 AS today
FROM dual
CONNECT BY LEVEL <= to_date(P_DENNGAY, 'dd/MM/yyyy') - to_date(P_TUNGAY, 'dd/MM/yyyy') + 1) LOOP
BEGIN

BEGIN--Tìm kỳ
SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE to_date(DENNGAY, 'dd/MM/yyyy') = to_date(cur_period.today, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
   EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
END;--End Tìm ky

BEGIN --Bắt đầu thực thi nhiệm vu
N:=N+1;
IF (N = 1) THEN
BEGIN -- Bản ghi đầu tiên
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON, TONDAUKYSL, TONDAUKYGT, NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.TONDAUKYSL, a.TONDAUKYGT, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1 ';
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAVATTU IN ('||P_MAVATTU||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
ELSE
BEGIN --Vòng thứ 2 trở đi
 P_SQL_INSERT := 'INSERT INTO TMP_XTN_NGAY
         (UNITCODE, MAKHO, MAVATTU, GIAVON,NHAPSL, NHAPGT, XUATSL, XUATGT)
         SELECT a.UNITCODE, a.MAKHO, a.MAVATTU, a.GIAVON, a.NHAPSL, a.NHAPGT, a.XUATSL, a.XUATGT
         FROM XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' a  left join dmvattu b on a.Mavattu = b.mavattu WHERE 1=1';
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAKHO IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND a.MAVATTU IN ('||P_MAVATTU||')';
END IF; 
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_SQL_INSERT := P_SQL_INSERT||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
execute IMMEDIATE P_SQL_INSERT;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
               goto end_loop;
               WHEN OTHERS THEN
               goto end_loop;
END;
END IF;
END;--Kết thúc vong 2 trở đi;
  
END;
        <<end_loop>>
        null;      
END LOOP;




IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKHO, c.TENKHO, b.MAVATTU, b.TENVATTU,b.BARCODE';
P_SELECT_COLUMNS_GROUPBY:= ' b.MAVATTU AS Code, b.TENVATTU as TenVT,b.BARCODE as BARCODE, c.MAKHO as CodeNCC, c.TENKHO AS Ten ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MAKHO = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MANHOMVTU, c.TENNHOMVT, b.MAVATTU, b.TENVATTU,b.BARCODE';
P_SELECT_COLUMNS_GROUPBY:= ' b.MAVATTU AS Code, b.TENVATTU as TenVT,b.BARCODE as BARCODE, c.MANHOMVTU as CodeNCC, c.TENNHOMVT AS Ten ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON b.MANHOMVATTU = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MALOAIVATTU, c.TENLOAIVT, b.MAVATTU, b.TENVATTU,b.BARCODE';
P_SELECT_COLUMNS_GROUPBY:= ' b.MAVATTU AS Code, b.TENVATTU as TenVT,b.BARCODE as BARCODE, c.MALOAIVATTU as CodeNCC, c.TENLOAIVT AS Ten ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON b.MALOAIVATTU = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'c.MAKH, c.TENKH, b.MAVATTU, b.TENVATTU,b.BARCODE';
P_SELECT_COLUMNS_GROUPBY := ' b.MAVATTU AS Code, b.TENVATTU as TenVT,b.BARCODE as BARCODE,c.MAKH as CodeNCC, c.TENKH AS Ten';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON b.MAKHACHHANG = c.MAKH ';
P_EXPRESSION:= ' AND c.LOAIKHACHHANG = 1';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,b.MAKHACHHANG';
P_SELECT_COLUMNS_GROUPBY:= ' b.MAVATTU AS Code,  b.TENVATTU AS TenVT,(SELECT TENKH FROM DMKHACHHANG WHERE b.MAKHACHHANG=DMKHACHHANG.MAKH) AS Ten,b.BARCODE AS BARCODE,b.MAKHACHHANG AS CodeNCC';
P_TABLE_GROUPBY:= '';
END;
END IF;

QUERY_STR:= 'select '||P_SELECT_COLUMNS_GROUPBY||',
                                    SUM(a.tondaukysl)  as OpeningBalanceQuantity,
                                    SUM(a.tondaukygt) as OpeningBalanceValue,
                                    SUM(a.nhapsl) as IncreaseQuantity, SUM(a.nhapgt) as IncreaseValue,
                                    SUM(a.xuatsl) as DecreaseQuantity, SUM(a.xuatgt) as DecreaseValue,
                                    SUM(a.tondaukysl - a.xuatsl + a.nhapsl) as ClosingQuantity, 
                              SUM(a.tondaukygt - a.xuatgt + a.nhapgt) as ClosingValue
                                    from TMP_XTN_NGAY a 
                                    left join DMVATTU b on a.Mavattu = b.mavattu
                                    '||P_TABLE_GROUPBY||'
                                    WHERE 1=1  and (a.tondaukysl * a.tondaukysl) + (a.nhapsl * a.nhapsl) + (a.xuatsl * a.xuatsl) + (a.toncuoikysl* a.toncuoikysl)  > 0 
									'||P_EXPRESSION||'
                                    GROUP BY '||P_COLUMNS_GROUPBY;
--QUERY_STR := QUERY_STR||' GROUP BY a.mavattu'; 
DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
OPEN cur FOR QUERY_STR;
 --DBMS_OUTPUT.put_line (QUERY_STR);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;
END BAOCAO_XNT_CHITIET;


PROCEDURE XNT_GIAM_PHIEU(P_TABLENAME IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2 ) IS
    N_SQL_INSERT VARCHAR(32767);
  BEGIN
  N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS 
	SELECT B.MAVATTU, B.MAKHOXUAT, B.UNITCODE, B.SOLUONG, 
	CASE  WHEN P.GIAVON =  0 THEN NVL(G.GIAMUA, 0)*B.SOLUONG 
	ELSE P.GIAVON*B.SOLUONG END AS XUATGT from 
    (SELECT MAVATTU, MAKHOXUAT, UNITCODE, SUM(SOLUONG) AS SOLUONG, SUM(DONGIA*SOLUONG) AS XUATGT 
    FROM VIEW_VATTUGD_XNT WHERE  
    ID='''||P_ID||''' GROUP BY MAVATTU, MAKHOXUAT, UNITCODE)  B 
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHOXUAT = P.MAKHO AND B.UNITCODE = P.UNITCODE 
   	LEFT JOIN DM_VATTU_GIACA G ON B.MAVATTU = G.MAVATTU AND B.UNITCODE = G.MADONVI ;
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHOXUAT AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHOXUAT AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      XUATSL=NVL(XUATSL,0)+VT_INDEX.SOLUONG, XUATGT=NVL(XUATGT,0)+VT_INDEX.XUATGT, TONCUOIKYSL=NVL(TONCUOIKYSL,0)-VT_INDEX.SOLUONG,TONCUOIKYGT=NVL(TONCUOIKYGT,0)-VT_INDEX.XUATGT
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHOXUAT;      
        COMMIT;
    END;
  
    END LOOP; 
    END;';
    DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN  DBMS_OUTPUT.PUT_LINE(SQLERRM);        
  END XNT_GIAM_PHIEU;
  PROCEDURE XNT_TANG_PHIEU(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2 ) IS
    N_SQL_INSERT VARCHAR(32767);    
	N_LOAICHUNGTU VARCHAR(100);  
	STR_IF_REFUND VARCHAR(32767);
BEGIN
SELECT LOAICHUNGTU INTO N_LOAICHUNGTU FROM VIEW_VATTUGD_XNT WHERE ID = P_ID AND ROWNUM = 1;
	STR_IF_REFUND:= 'SELECT MAVATTU,MAKHONHAP,UNITCODE,SUM(SOLUONG) AS SOLUONG,SUM(SOLUONG*DONGIA) AS NHAPGT FROM VIEW_VATTUGD_XNT V WHERE 
    ID='''||P_ID||'''     
    GROUP BY MAVATTU,MAKHONHAP,UNITCODE;';
	IF N_LOAICHUNGTU = '2' THEN
	BEGIN
	STR_IF_REFUND := 'SELECT B.MAVATTU, B.MAKHONHAP, B.UNITCODE, B.SOLUONG, CASE  WHEN P.TONCUOIKYSL =  0 THEN NVL(G.GIAMUA, 0)*B.SOLUONG  WHEN (P.TONDAUKYSL + P.NHAPSL) IS NULL THEN NVL(G.GIAMUA, 0)*B.SOLUONG  ELSE ABS(B.SOLUONG*((P.TONDAUKYGT + P.NHAPGT)/(P.TONDAUKYSL + P.NHAPSL))) END AS NHAPGT from 
    (SELECT MAVATTU, MAKHONHAP, UNITCODE, SUM(SOLUONG) AS SOLUONG, SUM(DONGIA*SOLUONG) AS NHAPGT 
    FROM VIEW_VATTUGD_XNT WHERE  
    ID='''||P_ID||''' GROUP BY MAVATTU, MAKHONHAP, UNITCODE)  B 
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHONHAP = P.MAKHO AND B.UNITCODE = P.UNITCODE 
		LEFT JOIN DM_VATTU_GIACA G ON B.MAVATTU = G.MAVATTU AND B.UNITCODE = G.MADONVI ;';
	END;
	END IF;
    N_SQL_INSERT :='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_VATTUGD IS '||STR_IF_REFUND||'
   
  BEGIN FOR VT_INDEX IN NHAP_VATTUGD LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU=VT_INDEX.MAVATTU AND  MAKHO=VT_INDEX.MAKHONHAP AND UNITCODE=VT_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT VT_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,VT_INDEX.MAKHONHAP AS MAKHO,VT_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=VT_INDEX.UNITCODE AND MAVATTU=VT_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
     
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      NHAPSL=NHAPSL+VT_INDEX.SOLUONG, 
	  NHAPGT=NHAPGT+VT_INDEX.NHAPGT, 
	  TONCUOIKYSL= TONCUOIKYSL+VT_INDEX.SOLUONG, 
	  TONCUOIKYGT=TONCUOIKYGT+VT_INDEX.NHAPGT,
	  GIAVON = 
    CASE (TONCUOIKYSL+VT_INDEX.SOLUONG) 
    WHEN 0 THEN 
    NVL((SELECT GIAMUA FROM DM_VATTU_GIACA 
    WHERE MAVATTU = VT_INDEX.MAVATTU AND MADONVI =VT_INDEX.UNITCODE), 0) 
	ELSE ABS((NVL(TONCUOIKYGT, 0) + NVL(VT_INDEX.NHAPGT, 0))/(NVL(TONCUOIKYSL, 0)+NVL(VT_INDEX.SOLUONG, 0))) END
      WHERE UNITCODE =VT_INDEX.UNITCODE AND  MAVATTU=VT_INDEX.MAVATTU AND MAKHO=VT_INDEX.MAKHONHAP; 
        COMMIT;
    END;
  
    END LOOP; 
    END;';
    
        DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);
END XNT_TANG_PHIEU;


PROCEDURE CAPNHAT_GIAVON_QUAYGIAODICH(P_TABLENAME IN VARCHAR, P_UNITCODE  IN VARCHAR2, P_NGAYPHATSINH IN DATE) IS
P_UPDATE_STR VARCHAR(3232);
P_UPDATE_GV_XNT VARCHAR(3232);
P_UPDATE_GV_VTCT VARCHAR(3232);
N_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(*) INTO N_COUNT FROM DMTHEODOITIENTRINH WHERE PROCESSCODE = 'CAPNHATGIAVON' AND UNITCODE = P_UNITCODE;
      IF N_COUNT = 0 THEN
      INSERT INTO DMTHEODOITIENTRINH (ID, PROCESSCODE, DESCRIPTION, STATE, UNITCODE) VALUES (SYS_GUID(), 'CAPNHATGIAVON', 'TIẾN TRÌNH CẬP NHẬT GIÁ VỐN', 0, P_UNITCODE);
      END IF;
      UPDATE DMTHEODOITIENTRINH SET
      STATE = 20 -- IS RUNNING
      WHERE PROCESSCODE = 'CAPNHATGIAVON' AND UNITCODE = P_UNITCODE;
P_UPDATE_GV_XNT:= 
'MERGE INTO NVHANGGDQUAY_ASYNCCLIENT  a  USING
(select X.UNITCODE as UNITCODE, X.MAKHO as MAKHO, X.MAVATTU AS MAVATTU, 
AVG(X.GIAVON)  as DONGIA from '||P_TABLENAME||' X
group by X.UNITCODE, X.MAKHO, X.MAVATTU) b
ON (a.MAKHOHANG = b.MAKHO and a.MAVATTU = b.MAVATTU and a.NGAYPHATSINH = TO_DATE('''|| P_NGAYPHATSINH ||''',''DD/MM/YY'') and b.UNITCODE = '''||P_UNITCODE||''')
WHEN MATCHED THEN
  UPDATE SET a.GIAVON = CASE b.DONGIA WHEN 0 THEN 
  NVL((SELECT C.GIAMUA FROM DM_VATTU_GIACA C WHERE  C.MAVATTU = b.MAVATTU AND C.MADONVI = b.UNITCODE), 0) 
  ELSE b.DONGIA END';
P_UPDATE_GV_VTCT:=
'MERGE INTO VATTUCHUNGTUCHITIET  a  USING
(select X.UNITCODE as UNITCODE, X.MAKHO as MAKHO, X.MAVATTU AS MAVATTU, 
AVG(X.GIAVON)  as DONGIA from '||P_TABLENAME||' X
group by X.UNITCODE, X.MAKHO, X.MAVATTU) b
ON (b.MAKHO= ''DV1-CH1-K2'' 
and a.MAHANG = b.MAVATTU 
and (select t.NGAYDUYETPHIEU from VATTUCHUNGTU t where t.MACHUNGTUPK = a.MACHUNGTUPK) = TO_DATE('''|| P_NGAYPHATSINH ||''',''DD/MM/YY'') 
and b.UNITCODE = '''||P_UNITCODE||''')
WHEN MATCHED THEN
  UPDATE SET a.GIAVON = CASE b.DONGIA WHEN 0 THEN 
  NVL((SELECT C.GIAMUA FROM DM_VATTU_GIACA C WHERE  C.MAVATTU = b.MAVATTU AND C.MADONVI = b.UNITCODE), 0) 
  ELSE b.DONGIA END';
BEGIN
execute IMMEDIATE P_UPDATE_GV_XNT;
execute IMMEDIATE P_UPDATE_GV_VTCT;
DBMS_OUTPUT.put_line (P_UPDATE_STR || '---');
      UPDATE DMTHEODOITIENTRINH SET
      STATE = 0 -- IS COMPLETE
      WHERE PROCESSCODE = 'CAPNHATGIAVON' AND UNITCODE = P_UNITCODE;   
      commit;
EXCEPTION WHEN OTHERS THEN
      UPDATE DMTHEODOITIENTRINH SET
      STATE = 30 -- IS ERROR
      WHERE PROCESSCODE = 'CAPNHATGIAVON' AND UNITCODE = P_UNITCODE;  
DBMS_OUTPUT.put_line (P_UPDATE_STR);
END;

END CAPNHAT_GIAVON_QUAYGIAODICH;


PROCEDURE XNT_TANGPHIEU_KIEMKE(P_TABLENAME IN VARCHAR2, P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2 ) IS
 N_LOAICHUNGTU VARCHAR(100);
 N_SQL_INSERT VARCHAR(32767);
 N_SELECT VARCHAR(32767);
  BEGIN
  SELECT LOAICHUNGTU INTO N_LOAICHUNGTU FROM VIEW_VATTUGD_XNT WHERE ID = P_ID; --N_KK
  IF N_LOAICHUNGTU = 'N_KK' THEN
    BEGIN
    N_SELECT:= 'SELECT V.MAVATTU,V.MAKHONHAP,V.UNITCODE,V.SOLUONG AS SOLUONG,V.SOLUONG*P.GIAVON AS NHAPGT 
    FROM VIEW_VATTUGD_XNT V LEFT JOIN '||P_TABLENAME||' P ON V.UNITCODE = P.UNITCODE 
    WHERE V.ID='''||P_ID||''' AND V.MAVATTU = P.MAVATTU AND V.MAKHOXUAT = P.MAKHO AND V.UNITCODE = P.UNITCODE;';
    END;
  END IF;
   N_SQL_INSERT :='DECLARE N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR NHAP_KIEMKE IS '||N_SELECT||'
    BEGIN FOR KK_INDEX IN NHAP_KIEMKE LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE 
        MAVATTU = KK_INDEX.MAVATTU AND MAKHO=KK_INDEX.MAKHONHAP AND UNITCODE = KK_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT KK_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,KK_INDEX.MAKHONHAP AS MAKHO,KK_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=KK_INDEX.UNITCODE AND MAVATTU=KK_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      NHAPSL=NHAPSL+ABS(KK_INDEX.SOLUONG), 
	  NHAPGT=NHAPGT+ABS(KK_INDEX.NHAPGT), 
	  TONCUOIKYSL= TONCUOIKYSL+ABS(KK_INDEX.SOLUONG), 
	  TONCUOIKYGT=TONCUOIKYGT+ABS(KK_INDEX.NHAPGT),
	  GIAVON = 
    CASE (TONCUOIKYSL + ABS(KK_INDEX.SOLUONG)) 
    WHEN 0 THEN 
    NVL((SELECT GIAMUA FROM DM_VATTU_GIACA 
    WHERE MAVATTU = KK_INDEX.MAVATTU AND MADONVI = KK_INDEX.UNITCODE), 0)
    ELSE ( ABS(NVL(TONCUOIKYGT, 0))+ ABS(NVL(KK_INDEX.NHAPGT, 0)) )/( ABS(NVL(TONCUOIKYSL, 0)) + ABS(NVL(KK_INDEX.SOLUONG, 0)) ) END
      WHERE UNITCODE = KK_INDEX.UNITCODE AND  MAVATTU = KK_INDEX.MAVATTU AND MAKHO=KK_INDEX.MAKHONHAP; 
        COMMIT;
    END; 
    END LOOP; 
    END;'; 
        DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);
  END XNT_TANGPHIEU_KIEMKE;
  
  
  PROCEDURE XNT_GIAMPHIEU_KIEMKE(P_TABLENAME IN VARCHAR2,P_NAM IN VARCHAR2,P_KY IN NUMBER,P_ID IN VARCHAR2 ) IS
    N_SQL_INSERT VARCHAR(32767);
  BEGIN
  N_SQL_INSERT:='DECLARE 
    N_COUNT NUMBER :=0; P_TONDAUKYSL NUMBER :=0; P_TONDAUKYGT NUMBER :=0;
    CURSOR XUAT_KIEMKE IS 
	SELECT B.MAVATTU, B.MAKHOXUAT, B.UNITCODE, B.SOLUONG,NVL(P.GIAVON, 0)*B.SOLUONG AS XUATGT FROM 
    (SELECT MAVATTU, MAKHOXUAT, UNITCODE, SUM(SOLUONG) AS SOLUONG, SUM(DONGIA*SOLUONG) AS XUATGT 
    FROM VIEW_VATTUGD_XNT WHERE ID='''||P_ID||''' GROUP BY MAVATTU, MAKHOXUAT, UNITCODE)  B 
    LEFT JOIN '||P_TABLENAME||' P  ON  B.MAVATTU = P.MAVATTU AND B.MAKHOXUAT = P.MAKHO AND B.UNITCODE = P.UNITCODE;
  BEGIN FOR KK_INDEX IN XUAT_KIEMKE LOOP
    N_COUNT :=0;
      BEGIN 
        SELECT COUNT(*) INTO N_COUNT FROM '||P_TABLENAME||' WHERE MAVATTU=KK_INDEX.MAVATTU AND MAKHO=KK_INDEX.MAKHOXUAT AND UNITCODE=KK_INDEX.UNITCODE;      
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
    BEGIN
      IF(N_COUNT=0) THEN 
        BEGIN 
      INSERT INTO '||P_TABLENAME||' (UNITCODE,NAM,KY,MAKHO,MAVATTU) 
      SELECT KK_INDEX.UNITCODE AS UNITCODE,'|| P_NAM ||' AS NAM,'|| P_KY ||' AS KY,KK_INDEX.MAKHOXUAT AS MAKHO,KK_INDEX.MAVATTU FROM DMVATTU WHERE UNITCODE=KK_INDEX.UNITCODE AND MAVATTU=KK_INDEX.MAVATTU;
      COMMIT;
        END;
       END IF;
     END;
    
    BEGIN     
      UPDATE '||P_TABLENAME||' SET
      XUATSL=XUATSL+ABS(KK_INDEX.SOLUONG), XUATGT=XUATGT+ABS(KK_INDEX.XUATGT), TONCUOIKYSL=TONCUOIKYSL-ABS(KK_INDEX.SOLUONG),TONCUOIKYGT=TONCUOIKYGT-ABS(KK_INDEX.XUATGT)
      WHERE UNITCODE =KK_INDEX.UNITCODE AND  MAVATTU=KK_INDEX.MAVATTU AND MAKHO=KK_INDEX.MAKHOXUAT;      
        COMMIT;
    END;
  
    END LOOP; 
    END;';
    
      EXECUTE IMMEDIATE N_SQL_INSERT;
        EXCEPTION WHEN OTHERS THEN  DBMS_OUTPUT.PUT_LINE(N_SQL_INSERT);        
  END XNT_GIAMPHIEU_KIEMKE;

END XNT;