create or replace PROCEDURE BAOCAO_XNT_TEST(P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, XTNCOLLECTION  OUT SYS_REFCURSOR) 
IS
    KY_BATDAU NUMBER;
    NAM_BATDAU NUMBER;
    KY_KETTHUC NUMBER;
    NAM_KETTHUC NUMBER;
    P_SQL_INSERT VARCHAR2(32767);
    QUERY_STR VARCHAR(32767);
    RESULT_STR VARCHAR(32767);
    P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
    P_TABLE_GROUPBY VARCHAR(32767);
    P_COLUMNS_GROUPBY VARCHAR(32767);
    P_SUB_GROUPBY VARCHAR(32767);
    P_SUB_SELECT_GROUPBY VARCHAR(32767);
    P_EXPRESSION VARCHAR(32767);
    P_ORDERBY VARCHAR(32767);
BEGIN
--Lấy DỮ LIỆU 
--LẤY TOÀN BỘ DỮ LIỆU NHẬP-XUẤT
   -- NHẬP MUA
    P_SQL_INSERT := 'INSERT INTO XUATNHAPTON_TEMP (MAVATTU, MALOAIVATTU, MANHOMVATTU,MANHACUNGCAP,MAKHO,SOLUONG,DONGIA,THANHTIEN,UNITCODE, LOAICHUNGTU,NGAYCHUNGTU,NGAYDUYETPHIEU)
         SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
         (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
         (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
          VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
          VATTUCHUNGTU.MAKHONHAP AS MAKHO,
          VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
          VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
          VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
          VATTUCHUNGTU.UNITCODE AS UNITCODE,
          VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
          VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
          VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
          FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NMUA'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';        
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- ĐIỀU CHUYỂN XUẤT
            P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
                (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            --ĐIỀU CHUYỂN NHẬN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
                              (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCN'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            --XUẤT BÁN LẺ WEB
            P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XBANLE'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            --NHẬP HÀNG BÁN TRẢ LẠI
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NHBANTL'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
             --ĐIỂU CHUYỂN XUẤT BO -- LÀ TRƯỜNG HỢP CON CỦA ĐIỀU CHUYỂN XUẤT
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''DCX'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX_BO'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;

            --Xuất hủy hàng hỏng 
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATHUYHANGHONG'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND MALYDOKHAC =''X11'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;

            --XUẤT HỦY
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATHUY'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND MALYDOKHAC =''X1'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;

            --Xuất trả nhà cung cấp 
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATTRANCC'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND MALYDOKHAC =''X12'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;

           --XUẤT ĐIỀU CHỈNH
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATDIEUCHINH'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND MALYDOKHAC =''X2'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;

            --XUẤT HỦY HÀNG HỎNG -- có 2 trường hợp xuất hủy hàng hóa 1: có mã lý do là X11 và 2: mã lý do NULL
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATHUYHANGHONG'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND MALYDOKHAC IS NULL AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            ---NHẬP KHÁC ---NHẬP TRỪ TỒN ÂM --NHẬP ĐIỀU CHỈNH
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPDIEUCHINH'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NKHAC'' AND MALYDOKHAC =''N3'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            ---NHẬP KHÁC ---XỬ LÝ HÀNG ÂM
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPHANGAM'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NKHAC'' AND MALYDOKHAC =''N2'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- ĐIỀU CHUYỂN NHẬN -- có 2 trường hợp: NHẬP CHUYỂN KHO VÀ NHẬP ST THÀNH VIÊN
            -- NHẬP CHUYỂN KHO
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
             (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPCHUYENKHO'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCN'' AND VATTUCHUNGTU.MADONVIXUAT = VATTUCHUNGTU.UNITCODE AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- NHẬP ST THÀNH VIÊN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPSTTHANHVIEN'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCN'' AND VATTUCHUNGTU.MADONVIXUAT <> VATTUCHUNGTU.UNITCODE AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- ĐIỀU CHUYỂN XUẤT-- có 2 trường hợp: XUẤT CHUYỂN KHO VÀ XUẤT ST THÀNH VIÊN
            -- XUẤT CHUYỂN KHO
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
            (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATCHUYENKHO'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX'' AND VATTUCHUNGTU.MADONVINHAN = VATTUCHUNGTU.UNITCODE AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- XUẤT ST THÀNH VIÊN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATSTTHANHVIEN'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX'' AND VATTUCHUNGTU.MADONVINHAN <> VATTUCHUNGTU.UNITCODE AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -- XUẤT BÁN BUÔN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
             (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS MALOAIVATTU,
             (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) AS  MANHOMVATTU,
              VATTUCHUNGTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.DONGIA AS DONGIA,
              VATTUCHUNGTUCHITIET.THANHTIEN AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATBANBUON'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XBAN'' AND TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_WAREHOUSE||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = VATTUCHUNGTUCHITIET.MAHANG) IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
            END IF;
            -------------------------------------
            --LẤY DỮ LIỆU BÁN HÀNG --
            P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL 
            SELECT hanggdquay.MAVATTU AS MAVATTU,
                     (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = hanggdquay.MAVATTU) AS MALOAIVATTU, 
                     (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = hanggdquay.MAVATTU) AS  MANHOMVATTU,
                     (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = hanggdquay.MAVATTU) AS MANHACUNGCAP,
                     hanggdquay.MAKHOHANG AS MAKHO,
                     hanggdquay.SOLUONG AS SOLUONG,
                     hanggdquay.GIABANLECOVAT AS DONGIA,
                     hanggdquay.TTIENCOVAT AS THANHTIEN,
                     hanggdquay.MADONVI AS UNITCODE,
                     TO_NCHAR(gdquay.LOAIGIAODICH) AS LOAICHUNGTU,
                     gdquay.NGAYTAO AS NGAYCHUNGTU,
                     gdquay.NGAYPHATSINH AS NGAYDUYETPHIEU
            FROM NVGDQUAY_ASYNCCLIENT gdquay
               INNER JOIN NVHANGGDQUAY_ASYNCCLIENT hanggdquay
                  ON (gdquay.MAGIAODICHQUAYPK = hanggdquay.MAGDQUAYPK)
                  WHERE hanggdquay.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(gdquay.NGAYPHATSINH,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';  
                   IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND hanggdquay.MAKHOHANG IN ('||P_WAREHOUSE||')';
                    END IF;
                    IF TRIM(P_MALOAI) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MALOAIVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = hanggdquay.MAVATTU) IN ('||P_MALOAI||')';
                    END IF;
                    IF TRIM(P_MANHOM) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND (SELECT MANHOMVATTU FROM DMVATTU WHERE DMVATTU.MAVATTU = hanggdquay.MAVATTU) IN ('||P_MANHOM||')';
                    END IF;
                    IF TRIM(P_MAVATTU) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND hanggdquay.MAVATTU IN ('||P_MAVATTU||')';
                    END IF;
                    
            -- LẤY DỮ LIỆU NHẬP KIỂM KÊ 
            P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT kiemkechitiet.MAVATTU AS MAVATTU,
            kiemkechitiet.LOAIVATTUKK AS MALOAIVATTU,
            kiemkechitiet.NHOMVATTUKK AS MANHOMVATTU,
            (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = kiemkechitiet.MAVATTU) AS MANHACUNGCAP,
            kiemke.KHOKIEMKE AS MAKHO,
            kiemkechitiet.SOLUONGCHENHLECH AS SOLUONG,
            kiemkechitiet.GIAVON AS DONGIA,
            kiemkechitiet.TIENCHENHLECH AS THANHTIEN,
            kiemkechitiet.MADONVI AS UNITCODE,
            TO_NCHAR(''NHAPKIEMKE'') AS LOAICHUNGTU,
            kiemke.NGAYKIEMKE AS NGAYCHUNGTU,
            kiemke.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
            FROM NVKIEMKE kiemke INNER JOIN NVKIEMKECHITIET kiemkechitiet 
            ON (kiemke.MAPHIEUKIEMKE = kiemkechitiet.MAPHIEUKIEMKE)
            WHERE TRANGTHAI = 10 AND kiemkechitiet.MADONVI = '''||P_UNITCODE||''' AND kiemkechitiet.SOLUONGCHENHLECH < 0 AND TO_DATE(kiemke.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemke.KHOKIEMKE IN ('||P_WAREHOUSE||')';
                    END IF;
                    IF TRIM(P_MALOAI) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.LOAIVATTUKK  IN ('||P_MALOAI||')';
                    END IF;
                    IF TRIM(P_MANHOM) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.NHOMVATTUKK IN ('||P_MANHOM||')';
                    END IF;
                    IF TRIM(P_MAVATTU) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND  kiemkechitiet.MAVATTU IN ('||P_MAVATTU||')';  
            END IF;
         -- LẤY DỮ LIỆU XUẤT KIỂM KÊ 
         P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT kiemkechitiet.MAVATTU AS MAVATTU,
            kiemkechitiet.LOAIVATTUKK AS MALOAIVATTU,
            kiemkechitiet.NHOMVATTUKK AS MANHOMVATTU,
            (SELECT DMVATTU.MAKHACHHANG FROM DMVATTU WHERE DMVATTU.MAVATTU = kiemkechitiet.MAVATTU) AS MANHACUNGCAP,
            kiemke.KHOKIEMKE AS MAKHO,
            kiemkechitiet.SOLUONGCHENHLECH AS SOLUONG,
            kiemkechitiet.GIAVON AS DONGIA,
            kiemkechitiet.TIENCHENHLECH AS THANHTIEN,
            kiemkechitiet.MADONVI AS UNITCODE,
            TO_NCHAR(''XUATKIEMKE'') AS LOAICHUNGTU,
            kiemke.NGAYKIEMKE AS NGAYCHUNGTU,
            kiemke.NGAYDUYETPHIEU AS NGAYDUYETPHIEU
            FROM NVKIEMKE kiemke INNER JOIN NVKIEMKECHITIET kiemkechitiet 
            ON (kiemke.MAPHIEUKIEMKE = kiemkechitiet.MAPHIEUKIEMKE)
            WHERE TRANGTHAI = 10 AND kiemkechitiet.MADONVI = '''||P_UNITCODE||''' AND kiemkechitiet.SOLUONGCHENHLECH >= 0 AND TO_DATE(kiemke.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemke.KHOKIEMKE IN ('||P_WAREHOUSE||')';
                    END IF;
                    IF TRIM(P_MALOAI) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.LOAIVATTUKK  IN ('||P_MALOAI||')';
                    END IF;
                    IF TRIM(P_MANHOM) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.NHOMVATTUKK IN ('||P_MANHOM||')';
                    END IF;
                    IF TRIM(P_MAVATTU) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND  kiemkechitiet.MAVATTU IN ('||P_MAVATTU||')';  
            END IF;
            
      

        BEGIN
             --DBMS_OUTPUT.put_line(P_SQL_INSERT)
                  EXECUTE IMMEDIATE P_SQL_INSERT;

                    EXCEPTION WHEN OTHERS THEN 
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);   
        END;
                          --QUERY_STR :='SELECT * FROM XUATNHAPTON_TEMP';
                         -- OPEN XTNCOLLECTION FOR QUERY_STR;
        ---NMUA,XBANLE,NHBANTL, XUATBANBUON, ||||||
        ---XUATHUYHANGHONG,XUATHUY,XUATTRANCC,XUATDIEUCHINH,NHAPDIEUCHINH,NHAPHANGAM,1,2,KIEMKE
        QUERY_STR := '
        SELECT a.MAVATTU,a.MALOAIVATTU,a.MAKHO,a.MANHACUNGCAP,a.MANHOMVATTU,a.DONGIA,a.UNITCODE,a.NGAYCHUNGTU,a.NGAYDUYETPHIEU,
        NVL(a.XUATBANLEQUAY_SUM_SOLUONG,0) AS XBANLEQUAY_SL , NVL(a.XUATBANLEQUAY_SUM_THANHTIEN,0) AS XBANLEQUAY_GT,
        NVL(a.XUATBANLETRALAI_SUM_SOLUONG,0) AS XBANLETL_SL  , NVL(a.XUATBANLETRALAI_SUM_THANHTIEN,0) AS XBANLETL_GT,
        NVL(a.NMUA_SUM_SOLUONG,0) AS NMUA_SL , NVL(a.NMUA_SUM_THANHTIEN,0) AS NMUA_GT,
        NVL(a.NHAPKIEMKE_SUM_SOLUONG,0) AS NHAPKIEMKE_SL, NVL(a.NHAPKIEMKE_SUM_THANHTIEN,0) AS NHAPKIEMKE_GT,
        NVL(a.XUATKIEMKE_SUM_SOLUONG,0) AS XUATKIEMKE_SL, NVL(a.XUATKIEMKE_SUM_THANHTIEN,0) AS XUATKIEMKE_GT,
        NVL(a.XUATBANLE_SUM_SOLUONG,0) AS XBANLE_SL, NVL(a.XUATBANLE_SUM_THANHTIEN,0) AS XBANLE_GT,
        NVL(a.NHAPCHUYENKHO_SUM_SOLUONG,0) AS NHAPCHUYENKHO_SL, NVL(a.NHAPCHUYENKHO_SUM_THANHTIEN,0) AS NHAPCHUYENKHO_GT,
        NVL(a.NHAPSTTHANHVIEN_SUM_SOLUONG,0) AS NHAPSTTHANHVIEN_SL, NVL(a.NHAPSTTHANHVIEN_SUM_THANHTIEN,0) AS NHAPSTTHANHVIEN_GT,
        NVL(a.XUATCHUYENKHO_SUM_SOLUONG,0) AS XUATCHUYENKHO_SL, NVL(a.XUATCHUYENKHO_SUM_THANHTIEN,0) AS XUATCHUYENKHO_GT,
        NVL(a.XUATSTTHANHVIEN_SUM_SOLUONG,0) AS XUATSTTHANHVIEN_SL, NVL(a.XUATSTTHANHVIEN_SUM_THANHTIEN,0) AS XUATSTTHANHVIEN_GT,
        NVL(a.NHAPDIEUCHINH_SUM_SOLUONG,0) AS NHAPDIEUCHINH_SL, NVL(a.NHAPDIEUCHINH_SUM_THANHTIEN,0) AS NHAPDIEUCHINH_GT,
        NVL(a.XUATBANBUON_SUM_SOLUONG,0) AS XUATBANBUON_SL, NVL(a.XUATBANBUON_SUM_THANHTIEN,0) AS XUATBANBUON_GT,
        NVL(a.NHAPHANGAM_SUM_SOLUONG,0) AS NHAPHANGAM_SL, NVL(a.NHAPHANGAM_SUM_THANHTIEN,0) AS NHAPHANGAM_GT,
        NVL(a.XUATHUYHANGHONG_SUM_SOLUONG,0) AS XUATHUYHH_SL, NVL(a.XUATHUYHANGHONG_SUM_THANHTIEN,0) AS XUATHUYHH_GT,
        NVL(a.XUATHUY_SUM_SOLUONG,0) AS XUATHUY_SL, NVL(a.XUATHUY_SUM_THANHTIEN,0) AS XUATHUY_GT,
        NVL(a.XUATTRANCC_SUM_SOLUONG,0) AS XUATTRANCC_SL, NVL(a.XUATTRANCC_SUM_THANHTIEN,0) AS XUATTRANCC_GT,
        NVL(a.XUATDIEUCHINH_SUM_SOLUONG,0) AS XUATDC_SL, NVL(a.XUATDIEUCHINH_SUM_THANHTIEN,0) AS XUATDC_GT,
        NVL(a.NHAPBANTRALAI_SUM_SOLUONG,0) AS NHAPBANTL_SL, NVL(a.NHAPBANTRALAI_SUM_THANHTIEN,0) AS NHAPBANTL_GT
        FROM (
            SELECT MAVATTU, MALOAIVATTU, MANHOMVATTU,SOLUONG,DONGIA,THANHTIEN,UNITCODE,MAKHO,MANHACUNGCAP,LOAICHUNGTU,NGAYCHUNGTU,NGAYDUYETPHIEU FROM XUATNHAPTON_TEMP)
            PIVOT ( SUM(SOLUONG) AS SUM_SOLUONG, SUM(NVL(THANHTIEN,0)) as SUM_THANHTIEN
              FOR LOAICHUNGTU
              IN (''1'' AS XUATBANLEQUAY,''2'' AS XUATBANLETRALAI, ''NMUA'' AS NMUA, ''NHAPKIEMKE'' AS NHAPKIEMKE,''XUATKIEMKE'' AS XUATKIEMKE, ''NHAPCHUYENKHO'' AS NHAPCHUYENKHO, ''NHAPSTTHANHVIEN'' AS NHAPSTTHANHVIEN, ''XUATCHUYENKHO'' AS XUATCHUYENKHO, 
              ''XUATSTTHANHVIEN'' AS XUATSTTHANHVIEN, ''XBANLE'' AS XUATBANLE,''NHAPDIEUCHINH'' AS NHAPDIEUCHINH,''NHAPHANGAM'' AS NHAPHANGAM,''XUATHUYHANGHONG'' AS XUATHUYHANGHONG,''XUATHUY'' AS XUATHUY, ''XUATBANBUON'' AS XUATBANBUON,
              ''XUATTRANCC'' AS XUATTRANCC,''XUATDIEUCHINH'' AS XUATDIEUCHINH,''NHBANTL'' AS NHAPBANTRALAI)
        ) a ORDER BY a.MAVATTU,a.MALOAIVATTU,a.MANHOMVATTU,a.NGAYDUYETPHIEU';

        --Group sau khi Pivot
        QUERY_STR  :=' SELECT U.MAVATTU,U.MALOAIVATTU, U.MANHOMVATTU, U.UNITCODE,U.MAKHO,U.MANHACUNGCAP,
        SUM(U.XBANLEQUAY_SL) AS XBANLEQUAY_SL , SUM(U.XBANLEQUAY_GT) AS XBANLEQUAY_GT,
        SUM(U.XBANLETL_SL) AS XBANLETL_SL  , SUM(U.XBANLETL_GT) AS XBANLETL_GT,
        SUM(U.NMUA_SL) AS NMUA_SL , SUM(U.NMUA_GT) AS NMUA_GT,
        SUM(U.NHAPKIEMKE_SL) AS NHAPKIEMKE_SL, SUM(U.NHAPKIEMKE_GT) AS NHAPKIEMKE_GT,
        SUM(U.XUATKIEMKE_SL) AS XUATKIEMKE_SL, SUM(U.XUATKIEMKE_GT) AS XUATKIEMKE_GT,
        SUM(U.NHAPCHUYENKHO_SL) AS NHAPCHUYENKHO_SL, SUM(U.NHAPCHUYENKHO_GT) AS NHAPCHUYENKHO_GT,
        SUM(U.NHAPSTTHANHVIEN_SL) AS NHAPSTTHANHVIEN_SL, SUM(U.NHAPSTTHANHVIEN_GT) AS NHAPSTTHANHVIEN_GT,
        SUM(U.XUATCHUYENKHO_SL) AS XUATCHUYENKHO_SL, SUM(U.XUATCHUYENKHO_GT) AS XUATCHUYENKHO_GT,
        SUM(U.XUATSTTHANHVIEN_SL) AS XUATSTTHANHVIEN_SL, SUM(U.XUATSTTHANHVIEN_GT) AS XUATSTTHANHVIEN_GT,
        SUM(U.XBANLE_SL) AS XBANLE_SL, SUM(U.XBANLE_GT) AS XBANLE_GT,
        SUM(U.XUATBANBUON_SL) AS XUATBANBUON_SL, SUM(U.XUATBANBUON_GT) AS XUATBANBUON_GT,
        SUM(U.NHAPDIEUCHINH_SL) AS NHAPDIEUCHINH_SL, SUM(U.NHAPDIEUCHINH_GT) AS NHAPDIEUCHINH_GT,
        SUM(U.NHAPHANGAM_SL) AS NHAPHANGAM_SL, SUM(U.NHAPHANGAM_GT) AS NHAPHANGAM_GT,
        SUM(U.XUATHUYHH_SL) AS XUATHUYHH_SL, SUM(U.XUATHUYHH_GT) AS XUATHUYHH_GT,
        SUM(U.XUATHUY_SL) AS XUATHUY_SL, SUM(U.XUATHUY_GT) AS XUATHUY_GT,
        SUM(U.XUATTRANCC_SL) AS XUATTRANCC_SL, SUM(U.XUATTRANCC_GT) AS XUATTRANCC_GT,
        SUM(U.XUATDC_SL) AS XUATDC_SL, SUM(U.XUATDC_GT) AS XUATDC_GT,
        SUM(U.NHAPBANTL_SL) AS NHAPBANTL_SL, SUM(U.NHAPBANTL_GT) AS NHAPBANTL_GT
        FROM ('||QUERY_STR||') U 
        GROUP BY U.MAVATTU,U.MALOAIVATTU, U.MANHOMVATTU, U.UNITCODE, U.MAKHO,U.MANHACUNGCAP
        '; 

        --TÌM BẢNG XUẤT NHẬP TỒN ĐẦU KỲ
        BEGIN
        SELECT KY, NAM INTO KY_BATDAU, NAM_BATDAU FROM DMKYKETOAN WHERE TO_DATE(DENNGAY, 'dd/MM/yyyy') = TO_DATE(P_TUNGAY, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
           EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);   
        END;--End Tìm ky
                --TÌM BẢNG XUẤT NHẬP TỒN CUỐI KỲ
        BEGIN
        SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DMKYKETOAN WHERE TO_DATE(DENNGAY, 'dd/MM/yyyy') = TO_DATE(P_DENNGAY, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
           EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);   
        END;--End Tìm ky
        
        RESULT_STR := '
        SELECT A.*,E.TENVATTU, B.TONDAUKYSL,B.TONDAUKYGT,C.TONCUOIKYSL,C.TONCUOIKYGT FROM ('||QUERY_STR||') A 
        INNER JOIN XNT_'|| NAM_BATDAU ||'_KY_'||KY_BATDAU||' B ON A.MAVATTU = B.MAVATTU AND A.MAKHO = B.MAKHO AND A.UNITCODE = B.UNITCODE
        INNER JOIN XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' C ON A.MAVATTU = C.MAVATTU AND A.MAKHO = C.MAKHO AND A.UNITCODE = C.UNITCODE
        LEFT JOIN DMVATTU E ON E.MAVATTU = A.MAVATTU
        ';
          
        IF P_GROUPBY = 'MAKHO' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'D.MAKHO, F.TENKHO';
        P_SELECT_COLUMNS_GROUPBY:= 'D.MAKHO AS MAKHO, F.TENKHO AS TENKHO';
        P_TABLE_GROUPBY:= ' LEFT JOIN DMKHO F ON D.MAKHO = F.MAKHO ';
        
        P_SUB_GROUPBY:= 'X.MAKHO, X.TENKHO';
        P_SUB_SELECT_GROUPBY:= 'X.MAKHO, X.TENKHO,X.UNITCODE';
        P_ORDERBY := 'X.MAKHO, X.TENKHO';
        END;
        
        ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'D.MANHOMVATTU, F.TENNHOMVT';
        P_SELECT_COLUMNS_GROUPBY:= ' D.MANHOMVATTU AS MANHOMVATTU, F.TENNHOMVT AS TENNHOMVATTU ';
        P_TABLE_GROUPBY:= ' LEFT JOIN DMNHOMVATTU F ON D.MANHOMVATTU = F.MANHOMVTU ';
        
        P_SUB_GROUPBY:= 'X.MANHOMVATTU, X.TENNHOMVATTU';
        P_SUB_SELECT_GROUPBY:= 'X.MANHOMVATTU, X.TENNHOMVATTU,X.UNITCODE';
        P_ORDERBY := 'X.MANHOMVATTU, X.TENNHOMVATTU';
        END;

        ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'D.MALOAIVATTU, F.TENLOAIVT';
        P_SELECT_COLUMNS_GROUPBY:= ' D.MALOAIVATTU AS MALOAIVATTU, F.TENLOAIVT AS TENLOAIVATTU ';
        P_TABLE_GROUPBY:= ' LEFT JOIN DMLOAIVATTU F ON D.MALOAIVATTU = F.MALOAIVATTU ';
        
        P_SUB_GROUPBY:= 'X.MALOAIVATTU, X.TENLOAIVATTU';
        P_SUB_SELECT_GROUPBY:= 'X.MALOAIVATTU, X.TENLOAIVATTU,X.UNITCODE';
        P_ORDERBY := 'X.MALOAIVATTU, X.TENLOAIVATTU';
        END;
        
        ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'D.MANHACUNGCAP, F.TENKH';
        P_SELECT_COLUMNS_GROUPBY:= ' D.MANHACUNGCAP AS MANHACUNGCAP, F.TENKH AS TENNHACUNGCAP ';
        P_TABLE_GROUPBY:= ' LEFT JOIN DMKHACHHANG F ON D.MANHACUNGCAP = F.MAKH ';
        P_EXPRESSION:= ' AND F.LOAIKHACHHANG = 1';
        
        P_SUB_GROUPBY:= 'X.MANHACUNGCAP, X.TENNHACUNGCAP';
        P_SUB_SELECT_GROUPBY:= 'X.MANHACUNGCAP, X.TENNHACUNGCAP,X.UNITCODE';
        P_ORDERBY := 'X.MANHACUNGCAP, X.TENNHACUNGCAP';
          IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
          P_EXPRESSION := P_EXPRESSION || ' AND D.MANHACUNGCAP IN ('||P_MAKHACHHANG||') ';
          END IF;
        END;
        ELSE 
        BEGIN
        P_COLUMNS_GROUPBY:= 'D.MAVATTU,F.TENVATTU';
        P_SELECT_COLUMNS_GROUPBY:= 'D.MAVATTU AS MAVATTU,F.TENVATTU AS TENVATTU';
        P_TABLE_GROUPBY:= 'LEFT JOIN DMVATTU F ON D.MAVATTU = F.MAVATTU';
        
        P_SUB_GROUPBY:= 'X.MAVATTU,X.TENVATTU';
        P_SUB_SELECT_GROUPBY:= 'X.MAVATTU,X.TENVATTU,X.UNITCODE';
        P_ORDERBY := 'X.MAVATTU,X.TENVATTU';
        END;
        END IF;  
         
        RESULT_STR:=' SELECT '||P_SELECT_COLUMNS_GROUPBY||',D.UNITCODE,D.XBANLEQUAY_SL,D.XBANLEQUAY_GT,
         D.XBANLETL_SL, D.XBANLETL_GT,D.NMUA_SL,D.NMUA_GT,D.NHAPKIEMKE_SL,D.NHAPKIEMKE_GT,D.XUATKIEMKE_SL,D.XUATKIEMKE_GT,D.NHAPCHUYENKHO_SL,D.NHAPCHUYENKHO_GT,D.NHAPSTTHANHVIEN_SL,D.NHAPSTTHANHVIEN_GT,
         D.XUATCHUYENKHO_SL,D.XUATCHUYENKHO_GT,D.XUATSTTHANHVIEN_SL,D.XUATSTTHANHVIEN_GT,D.XBANLE_SL,D.XBANLE_GT,D.XUATBANBUON_SL,D.XUATBANBUON_GT,
         D.NHAPDIEUCHINH_SL,D.NHAPDIEUCHINH_GT,NHAPHANGAM_SL,D.NHAPHANGAM_GT,D.XUATHUYHH_SL,D.XUATHUYHH_GT,D.XUATHUY_SL,D.XUATHUY_GT,
         D.XUATTRANCC_SL,D.XUATTRANCC_GT,D.XUATDC_SL,D.XUATDC_GT,D.NHAPBANTL_SL,D.NHAPBANTL_GT,
         SUM(D.TONDAUKYSL) AS TONDAUKYSL, SUM(D.TONDAUKYGT) AS TONDAUKYGT, SUM(D.TONCUOIKYSL) AS TONCUOIKYSL, SUM(D.TONCUOIKYGT) AS TONCUOIKYGT
         FROM ('||RESULT_STR||') D '||P_TABLE_GROUPBY||'
         GROUP BY '||P_COLUMNS_GROUPBY||',D.UNITCODE,D.XBANLEQUAY_SL,D.XBANLEQUAY_GT,
         D.XBANLETL_SL, D.XBANLETL_GT,D.NMUA_SL,D.NMUA_GT,D.NHAPKIEMKE_SL,D.NHAPKIEMKE_GT,D.XUATKIEMKE_SL,D.XUATKIEMKE_GT,D.NHAPCHUYENKHO_SL,D.NHAPCHUYENKHO_GT,D.NHAPSTTHANHVIEN_SL,D.NHAPSTTHANHVIEN_GT,
         D.XUATCHUYENKHO_SL,D.XUATCHUYENKHO_GT,D.XUATSTTHANHVIEN_SL,D.XUATSTTHANHVIEN_GT,D.XBANLE_SL,D.XBANLE_GT,D.XUATBANBUON_SL,D.XUATBANBUON_GT,
         D.NHAPDIEUCHINH_SL,D.NHAPDIEUCHINH_GT,NHAPHANGAM_SL,D.NHAPHANGAM_GT,D.XUATHUYHH_SL,D.XUATHUYHH_GT,D.XUATHUY_SL,D.XUATHUY_GT,
         D.XUATTRANCC_SL,D.XUATTRANCC_GT,D.XUATDC_SL,D.XUATDC_GT,D.NHAPBANTL_SL,D.NHAPBANTL_GT
         ';
         RESULT_STR:=' SELECT '||P_SUB_GROUPBY||',X.UNITCODE,SUM(X.XBANLEQUAY_SL) AS XBANLEQUAY_SL,SUM(X.XBANLEQUAY_GT) AS XBANLEQUAY_GT,
         SUM(X.XBANLETL_SL) AS XBANLETL_SL, SUM(X.XBANLETL_GT) AS XBANLETL_GT,SUM(X.NMUA_SL) AS NMUA_SL,SUM(X.NMUA_GT) AS NMUA_GT,
         SUM(X.NHAPKIEMKE_SL) AS NHAPKIEMKE_SL,SUM(X.NHAPKIEMKE_GT) AS NHAPKIEMKE_GT,
         SUM(X.XUATKIEMKE_SL) AS XUATKIEMKE_SL,SUM(X.XUATKIEMKE_GT) AS XUATKIEMKE_GT,
         SUM(X.NHAPCHUYENKHO_SL) AS NHAPCHUYENKHO_SL,SUM(X.NHAPCHUYENKHO_GT) AS NHAPCHUYENKHO_GT,
         SUM(X.NHAPSTTHANHVIEN_SL) AS NHAPSTTHANHVIEN_SL,SUM(X.NHAPSTTHANHVIEN_GT) AS NHAPSTTHANHVIEN_GT,SUM(X.XUATCHUYENKHO_SL) AS XUATCHUYENKHO_SL,
         SUM(X.XUATCHUYENKHO_GT) AS XUATCHUYENKHO_GT,SUM(X.XUATSTTHANHVIEN_SL) AS XUATSTTHANHVIEN_SL,
         SUM(X.XUATSTTHANHVIEN_GT) AS XUATSTTHANHVIEN_GT,SUM(X.XBANLE_SL) AS XBANLE_SL,SUM(X.XBANLE_GT) AS XBANLE_GT,SUM(X.XUATBANBUON_SL) AS XUATBANBUON_SL,SUM(X.XUATBANBUON_GT) AS XUATBANBUON_GT,
         SUM(X.NHAPDIEUCHINH_SL) AS NHAPDIEUCHINH_SL,SUM(X.NHAPDIEUCHINH_GT) AS NHAPDIEUCHINH_GT,SUM(X.NHAPHANGAM_SL) AS NHAPHANGAM_SL,SUM(X.NHAPHANGAM_GT) AS NHAPHANGAM_GT,SUM(X.XUATHUYHH_SL) AS XUATHUYHH_SL,
         SUM(X.XUATHUYHH_GT) AS XUATHUYHH_GT,SUM(X.XUATHUY_SL) AS XUATHUY_SL,SUM(X.XUATHUY_GT) AS XUATHUY_GT,
         SUM(X.XUATTRANCC_SL) AS XUATTRANCC_SL,SUM(X.XUATTRANCC_GT) AS XUATTRANCC_GT,SUM(X.XUATDC_SL) AS XUATDC_SL,SUM(X.XUATDC_GT) AS XUATDC_GT,SUM(X.NHAPBANTL_SL) AS NHAPBANTL_SL,SUM(X.NHAPBANTL_GT) AS NHAPBANTL_GT,
         SUM(X.TONDAUKYSL) AS TONDAUKYSL, SUM(X.TONDAUKYGT) AS TONDAUKYGT, SUM(X.TONCUOIKYSL) AS TONCUOIKYSL, SUM(X.TONCUOIKYGT) AS TONCUOIKYGT
         FROM ('||RESULT_STR||') X 
         GROUP BY '||P_SUB_SELECT_GROUPBY||' ORDER BY '||P_ORDERBY||'';      
          BEGIN
          DBMS_OUTPUT.put_line (RESULT_STR);
                OPEN XTNCOLLECTION FOR RESULT_STR;
                EXCEPTION
                   WHEN NO_DATA_FOUND
                   THEN
                      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
                   WHEN OTHERS
                   THEN
                      DBMS_OUTPUT.put_line (RESULT_STR  || SQLERRM);
                END;
END BAOCAO_XNT_TEST;