create or replace PROCEDURE "BAOCAO_XNTNEW_CHITIET" (P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  
P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2,
P_UNITCODE  IN VARCHAR2, 
P_TUNGAY IN DATE,P_DENNGAY IN DATE,P_USERNAME IN VARCHAR2, 
XTNCOLLECTION  OUT SYS_REFCURSOR) 
IS
    KY_BATDAU NUMBER;
    NAM_BATDAU NUMBER;
    KY_KETTHUC NUMBER;
    NAM_KETTHUC NUMBER;
    P_SQL_INSERT VARCHAR2(32767);
    QUERY_STR VARCHAR(32767);
    RESULT_STR VARCHAR(32767);
    P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
    P_TABLE_GROUPBY VARCHAR(32767);
    P_COLUMNS_GROUPBY VARCHAR(32767);
    P_SUB_GROUPBY VARCHAR(32767);
    P_SUB_SELECT_GROUPBY VARCHAR(32767);
    P_EXPRESSION VARCHAR(32767);
    P_ORDERBY VARCHAR(32767);
    CUR SYS_REFCURSOR;
    CHECK_EXIST_TABLE NUMBER(18,2) := 0;
    CREATE_TABLE VARCHAR(3000);
BEGIN
    DBMS_OUTPUT.ENABLE(1000000);
     CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."XUATNHAPTON_TEMP" 
   (	"MAVATTU" NVARCHAR2(50), 
	"MALOAIVATTU" NVARCHAR2(20), 
	"MANHOMVATTU" NVARCHAR2(20), 
	"MANHACUNGCAP" NVARCHAR2(20), 
	"MAKHO" NVARCHAR2(50), 
	"SOLUONG" NUMBER(17,4) DEFAULT 0, 
	"DONGIA" NUMBER(17,4) DEFAULT 0, 
	"THANHTIEN" NUMBER(17,4) DEFAULT 0, 
	"UNITCODE" NVARCHAR2(20), 
	"LOAICHUNGTU" NVARCHAR2(20), 
	"NGAYCHUNGTU" DATE, 
	"NGAYDUYETPHIEU" DATE,
    "USERNAME" NVARCHAR2(50)
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''XUATNHAPTON_TEMP''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATE');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE XUATNHAPTON_TEMP WHERE USERNAME = '''||P_USERNAME||''' AND UNITCODE = '''||P_UNITCODE||'''';
    --NHẬP MUA, NHẬP BÁN BUÔN TRẢ LẠI
    P_SQL_INSERT := 'INSERT INTO XUATNHAPTON_TEMP (MAVATTU, MALOAIVATTU, MANHOMVATTU, MANHACUNGCAP, MAKHO, SOLUONG, DONGIA, THANHTIEN, UNITCODE, LOAICHUNGTU, NGAYCHUNGTU, NGAYDUYETPHIEU, USERNAME)
         SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
          DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
          DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
          DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
          VATTUCHUNGTU.MAKHONHAP AS MAKHO,
          VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
          VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
          VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
          VATTUCHUNGTU.UNITCODE AS UNITCODE,
          VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
          VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
          VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
          '''||P_USERNAME||''' AS USERNAME
          FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET ON VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
        WHERE VATTUCHUNGTU.LOAICHUNGTU IN (''NMUA'',''NHBANTL'') AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';        
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
        --XUẤT BÁN LẺ WEB
        P_SQL_INSERT := P_SQL_INSERT || ' UNION ALL
         SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
          DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
          DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
          DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
          VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
          VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,       
          VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
          VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
          VATTUCHUNGTU.UNITCODE AS UNITCODE,
          VATTUCHUNGTU.LOAICHUNGTU AS LOAICHUNGTU,
          VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
          VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
          '''||P_USERNAME||''' AS USERNAME
          FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET ON VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
        WHERE VATTUCHUNGTU.LOAICHUNGTU=''XBANLE'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';        
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;     

            --XUẤT HỦY
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATHUY'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND VATTUCHUNGTU.MALYDOKHAC =''X1'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

            --XUẤT TRẢ NHÀ CUNG CẤP
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATTRANCC'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND VATTUCHUNGTU.MALYDOKHAC =''X12'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

           -- XUẤT ĐIỀU CHỈNH
             P_SQL_INSERT := P_SQL_INSERT || '
          UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATDIEUCHINH'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND VATTUCHUNGTU.MALYDOKHAC =''X2'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

            --XUẤT HỦY HÀNG HỎNG- CÓ 2 TRƯỜNG HỢP XUẤT HỦY HÀNG HỎNG -  1: CÓ MÃ LÝ DO X11 VÀ  2: MÃ LÝ DO NULL
             P_SQL_INSERT := P_SQL_INSERT || '
        UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATHUYHANGHONG'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XKHAC'' AND (VATTUCHUNGTU.MALYDOKHAC IS NULL OR VATTUCHUNGTU.MALYDOKHAC = ''X11'' ) AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            ---NHẬP KHÁC -- NHẬP ĐIỀU CHỈNH
             P_SQL_INSERT := P_SQL_INSERT || '
                        UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPDIEUCHINH'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NKHAC'' AND VATTUCHUNGTU.MALYDOKHAC =''N3'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            ---NHẬP KHÁC ---NHẬP HÀNG XUẤT ÂM
             P_SQL_INSERT := P_SQL_INSERT || '
                        UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
            DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPHANGAM'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''NKHAC'' AND VATTUCHUNGTU.MALYDOKHAC =''N2'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            -- NHẬP ĐIỀU CHUYỂN NỘI BỘ -- CÓ 2 TRƯỜNG HỢP: NHẬP CHUYỂN KHO VÀ NHẬP ST THÀNH VIÊN
            -- NHẬP CHUYỂN KHO
             P_SQL_INSERT := P_SQL_INSERT || '
             UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPCHUYENKHO'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCN'' AND VATTUCHUNGTU.MADONVIXUAT = VATTUCHUNGTU.UNITCODE AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            -- NHẬP ST THÀNH VIÊN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHONHAP AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''NHAPSTTHANHVIEN'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCN'' AND VATTUCHUNGTU.MADONVIXUAT <> VATTUCHUNGTU.UNITCODE AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHONHAP IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            -- XUẤT ĐIỀU CHUYỂN NỘ BỘ-- CÓ 2 TRƯỜNG HỢP: XUẤT CHUYỂN KHO VÀ XUẤT ST THÀNH VIÊN
            -- XUẤT CHUYỂN KHO
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATCHUYENKHO'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX'' AND VATTUCHUNGTU.MADONVINHAN = VATTUCHUNGTU.UNITCODE AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            -- XUẤT ST THÀNH VIÊN
             P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATSTTHANHVIEN'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''DCX'' AND VATTUCHUNGTU.MADONVINHAN <> VATTUCHUNGTU.UNITCODE AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;
            -- XUẤT BÁN BUÔN
             P_SQL_INSERT := P_SQL_INSERT || ' UNION ALL
             SELECT VATTUCHUNGTUCHITIET.MAHANG AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              VATTUCHUNGTU.MAKHOXUAT AS MAKHO,
              VATTUCHUNGTUCHITIET.SOLUONG AS SOLUONG,
              VATTUCHUNGTUCHITIET.GIAVON AS DONGIA,
              VATTUCHUNGTUCHITIET.GIAVON * VATTUCHUNGTUCHITIET.SOLUONG AS THANHTIEN,
              VATTUCHUNGTU.UNITCODE AS UNITCODE,
              TO_NCHAR(''XUATBANBUON'') AS LOAICHUNGTU,
              VATTUCHUNGTU.NGAYCHUNGTU AS NGAYCHUNGTU,
              VATTUCHUNGTU.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
              '''||P_USERNAME||''' AS USERNAME
              FROM VATTUCHUNGTU
              INNER JOIN VATTUCHUNGTUCHITIET
              ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
              INNER JOIN DM_VATTU ON VATTUCHUNGTUCHITIET.MAHANG = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
              WHERE VATTUCHUNGTU.LOAICHUNGTU = ''XBAN'' AND VATTUCHUNGTU.TRANGTHAI = 10 AND VATTUCHUNGTU.UNITCODE = '''||P_UNITCODE||''' AND TO_DATE(VATTUCHUNGTU.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTU.MAKHOXUAT IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND VATTUCHUNGTUCHITIET.MAHANG IN ('||P_MAVATTU||')';
            END IF;    
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

            -------------------------------------
            --XUẤT BÁN LẺ - GIAO DỊCH QUẦY
            P_SQL_INSERT := P_SQL_INSERT || '
           UNION ALL
            SELECT hanggdquay.MAVATTU AS MAVATTU,
                     DM_VATTU.MALOAIVATTU AS MALOAIVATTU, 
                     DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
                     DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
                     hanggdquay.MAKHOHANG AS MAKHO,
                     hanggdquay.SOLUONG AS SOLUONG,
                     hanggdquay.GIAVON AS DONGIA,
                     hanggdquay.GIAVON * hanggdquay.SOLUONG AS THANHTIEN,
                     hanggdquay.MADONVI AS UNITCODE,
                     TO_NCHAR(gdquay.LOAIGIAODICH) AS LOAICHUNGTU,
                     gdquay.NGAYTAO AS NGAYCHUNGTU,
                     gdquay.NGAYPHATSINH AS NGAYDUYETPHIEU,
                     '''||P_USERNAME||''' AS USERNAME
            FROM NVGDQUAY_ASYNCCLIENT gdquay
               INNER JOIN NVHANGGDQUAY_ASYNCCLIENT hanggdquay
                  ON (gdquay.MAGIAODICHQUAYPK = hanggdquay.MAGDQUAYPK)
              INNER JOIN DM_VATTU ON hanggdquay.MAVATTU = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
                  WHERE hanggdquay.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(gdquay.NGAYPHATSINH,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';  
                   IF TRIM(P_MAKHO) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND hanggdquay.MAKHOHANG IN ('||P_MAKHO||')';
                    END IF;
                    IF TRIM(P_MALOAI) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
                    END IF;
                    IF TRIM(P_MANHOM) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
                    END IF;
                    IF TRIM(P_MAVATTU) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND hanggdquay.MAVATTU IN ('||P_MAVATTU||')';
                    END IF;
                    IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
                    P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
                    END IF;
            -- NHẬP KIỂM KÊ
            P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT kiemkechitiet.MAVATTU AS MAVATTU,
            kiemkechitiet.LOAIVATTUKK AS MALOAIVATTU,
            kiemkechitiet.NHOMVATTUKK AS MANHOMVATTU,
            DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
            kiemke.KHOKIEMKE AS MAKHO,
            kiemkechitiet.SOLUONGCHENHLECH AS SOLUONG,
            kiemkechitiet.GIAVON AS DONGIA,
            kiemkechitiet.SOLUONGCHENHLECH * kiemkechitiet.GIAVON AS THANHTIEN,
            kiemkechitiet.MADONVI AS UNITCODE,
            TO_NCHAR(''NHAPKIEMKE'') AS LOAICHUNGTU,
            kiemke.NGAYKIEMKE AS NGAYCHUNGTU,
            kiemke.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
            '''||P_USERNAME||''' AS USERNAME
            FROM NVKIEMKE kiemke INNER JOIN NVKIEMKECHITIET kiemkechitiet 
            ON (kiemke.MAPHIEUKIEMKE = kiemkechitiet.MAPHIEUKIEMKE)
              INNER JOIN DM_VATTU ON kiemkechitiet.MAVATTU = DM_VATTU.MAVATTU  AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
            WHERE kiemke.TRANGTHAI = 10 AND kiemkechitiet.MADONVI = '''||P_UNITCODE||''' AND kiemkechitiet.SOLUONGCHENHLECH < 0 AND TO_DATE(kiemke.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemke.KHOKIEMKE IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.LOAIVATTUKK  IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.NHOMVATTUKK IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND  kiemkechitiet.MAVATTU IN ('||P_MAVATTU||')';  
            END IF;
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

         -- XUẤT KIỂM KÊ
         P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT kiemkechitiet.MAVATTU AS MAVATTU,
            kiemkechitiet.LOAIVATTUKK AS MALOAIVATTU,
            kiemkechitiet.NHOMVATTUKK AS MANHOMVATTU,
            DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
            kiemke.KHOKIEMKE AS MAKHO,
            kiemkechitiet.SOLUONGCHENHLECH AS SOLUONG,
            kiemkechitiet.GIAVON AS DONGIA,
            kiemkechitiet.SOLUONGCHENHLECH * kiemkechitiet.GIAVON AS THANHTIEN,
            kiemkechitiet.MADONVI AS UNITCODE,
            TO_NCHAR(''XUATKIEMKE'') AS LOAICHUNGTU,
            kiemke.NGAYKIEMKE AS NGAYCHUNGTU,
            kiemke.NGAYDUYETPHIEU AS NGAYDUYETPHIEU,
            '''||P_USERNAME||''' AS USERNAME
            FROM NVKIEMKE kiemke INNER JOIN NVKIEMKECHITIET kiemkechitiet 
            ON (kiemke.MAPHIEUKIEMKE = kiemkechitiet.MAPHIEUKIEMKE)
            INNER JOIN DM_VATTU ON kiemkechitiet.MAVATTU = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
            WHERE kiemke.TRANGTHAI = 10 AND kiemkechitiet.MADONVI = '''||P_UNITCODE||''' AND kiemkechitiet.SOLUONGCHENHLECH >= 0 AND TO_DATE(kiemke.NGAYDUYETPHIEU,''DD/MM/YY'') BETWEEN TO_DATE('''||P_TUNGAY||''', ''DD/MM/YY'') AND TO_DATE('''||P_DENNGAY||''', ''DD/MM/YY'')';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemke.KHOKIEMKE IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.LOAIVATTUKK  IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND kiemkechitiet.NHOMVATTUKK IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND  kiemkechitiet.MAVATTU IN ('||P_MAVATTU||')'; 
            END IF;
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;

        -- GET KY, NAM CUA BANG XNT DAU KY
        BEGIN
        SELECT KY, NAM INTO KY_BATDAU, NAM_BATDAU FROM DM_KYKETOAN WHERE TO_DATE(DENNGAY, 'dd/MM/yyyy') = TO_DATE(P_TUNGAY, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
           EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);   
        END;--End 
         --LAY TON DAU KY TRONG BANG XNT
         P_SQL_INSERT := P_SQL_INSERT || '
            UNION ALL
            SELECT TDK.MAVATTU AS MAVATTU,
              DM_VATTU.MALOAIVATTU AS MALOAIVATTU,
              DM_VATTU.MANHOMVATTU AS  MANHOMVATTU,
              DM_VATTU.MAKHACHHANG AS MANHACUNGCAP,
              TDK.MAKHO AS MAKHO,
              TDK.TONDAUKYSL AS SOLUONG,
              TDK.GIAVON AS DONGIA,
              TDK.TONDAUKYSL * TDK.GIAVON AS THANHTIEN,
              TDK.UNITCODE AS UNITCODE,
              TO_NCHAR(''TONDAUKY'') AS LOAICHUNGTU,
              TO_DATE('''||P_TUNGAY||''',''dd/MM/yyyy'') AS NGAYCHUNGTU,
              TO_DATE('''||P_TUNGAY||''',''dd/MM/yyyy'') AS NGAYDUYETPHIEU,
               '''||P_USERNAME||''' AS USERNAME
            FROM XNT_'||NAM_BATDAU||'_KY_'||KY_BATDAU||' TDK 
            INNER JOIN DM_VATTU ON TDK.MAVATTU = DM_VATTU.MAVATTU AND DM_VATTU.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
            WHERE TDK.UNITCODE = '''||P_UNITCODE||''' AND TDK.TONDAUKYSL <> 0 ';
            IF TRIM(P_MAKHO) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND TDK.MAKHO IN ('||P_MAKHO||')';
            END IF;
            IF TRIM(P_MALOAI) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MALOAIVATTU IN ('||P_MALOAI||')';
            END IF;
            IF TRIM(P_MANHOM) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MANHOMVATTU IN ('||P_MANHOM||')';
            END IF;
            IF TRIM(P_MAVATTU) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND TDK.MAVATTU IN ('||P_MAVATTU||')';
            END IF;
            IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
            P_SQL_INSERT := P_SQL_INSERT||' AND DM_VATTU.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
            END IF;


        BEGIN
            --DBMS_OUTPUT.put_line(P_SQL_INSERT);
            EXECUTE IMMEDIATE P_SQL_INSERT;
            EXCEPTION WHEN OTHERS THEN  
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT || SQLERRM);   
        END;

                          --QUERY_STR :='SELECT * FROM XUATNHAPTON_TEMP';
                         -- OPEN XTNCOLLECTION FOR QUERY_STR;
        ---NMUA,XBANLE,NHBANTL, XUATBANBUON, ||||||
        ---XUATHUYHANGHONG,XUATHUY,XUATTRANCC,XUATDIEUCHINH,NHAPDIEUCHINH,NHAPHANGAM,1,2,KIEMKE
        --XUATNHAPTON_TEMP (MAVATTU, MALOAIVATTU, MANHOMVATTU,MANHACUNGCAP,MAKHO,SOLUONG,DONGIA,THANHTIEN,UNITCODE, LOAICHUNGTU,NGAYCHUNGTU,NGAYDUYETPHIEU)
        QUERY_STR := '
        SELECT a.MAVATTU,a.MALOAIVATTU,a.MAKHO,a.MANHACUNGCAP,a.MANHOMVATTU,a.DONGIA,a.UNITCODE,a.NGAYCHUNGTU,a.NGAYDUYETPHIEU,
        NVL(a.XUATBANLEQUAY_SUM_SOLUONG,0) AS XBANLEQUAY_SL , NVL(a.XUATBANLEQUAY_SUM_THANHTIEN,0) AS XBANLEQUAY_GT,
        NVL(a.XUATBANLETRALAI_SUM_SOLUONG,0) AS XBANLETL_SL  , NVL(a.XUATBANLETRALAI_SUM_THANHTIEN,0) AS XBANLETL_GT,
        NVL(a.NMUA_SUM_SOLUONG,0) AS NMUA_SL , NVL(a.NMUA_SUM_THANHTIEN,0) AS NMUA_GT,
        NVL(a.NHAPKIEMKE_SUM_SOLUONG,0) AS NHAPKIEMKE_SL, NVL(a.NHAPKIEMKE_SUM_THANHTIEN,0) AS NHAPKIEMKE_GT,
        NVL(a.XUATKIEMKE_SUM_SOLUONG,0) AS XUATKIEMKE_SL, NVL(a.XUATKIEMKE_SUM_THANHTIEN,0) AS XUATKIEMKE_GT,
        NVL(a.XUATBANLE_SUM_SOLUONG,0) AS XBANLE_SL, NVL(a.XUATBANLE_SUM_THANHTIEN,0) AS XBANLE_GT,
        NVL(a.NHAPCHUYENKHO_SUM_SOLUONG,0) AS NHAPCHUYENKHO_SL, NVL(a.NHAPCHUYENKHO_SUM_THANHTIEN,0) AS NHAPCHUYENKHO_GT,
        NVL(a.NHAPSTTHANHVIEN_SUM_SOLUONG,0) AS NHAPSTTHANHVIEN_SL, NVL(a.NHAPSTTHANHVIEN_SUM_THANHTIEN,0) AS NHAPSTTHANHVIEN_GT,
        NVL(a.XUATCHUYENKHO_SUM_SOLUONG,0) AS XUATCHUYENKHO_SL, NVL(a.XUATCHUYENKHO_SUM_THANHTIEN,0) AS XUATCHUYENKHO_GT,
        NVL(a.XUATSTTHANHVIEN_SUM_SOLUONG,0) AS XUATSTTHANHVIEN_SL, NVL(a.XUATSTTHANHVIEN_SUM_THANHTIEN,0) AS XUATSTTHANHVIEN_GT,
        NVL(a.NHAPDIEUCHINH_SUM_SOLUONG,0) AS NHAPDIEUCHINH_SL, NVL(a.NHAPDIEUCHINH_SUM_THANHTIEN,0) AS NHAPDIEUCHINH_GT,
        NVL(a.XUATBANBUON_SUM_SOLUONG,0) AS XUATBANBUON_SL, NVL(a.XUATBANBUON_SUM_THANHTIEN,0) AS XUATBANBUON_GT,
        NVL(a.NHAPHANGAM_SUM_SOLUONG,0) AS NHAPHANGAM_SL, NVL(a.NHAPHANGAM_SUM_THANHTIEN,0) AS NHAPHANGAM_GT,
        NVL(a.XUATHUYHANGHONG_SUM_SOLUONG,0) AS XUATHUYHH_SL, NVL(a.XUATHUYHANGHONG_SUM_THANHTIEN,0) AS XUATHUYHH_GT,
        NVL(a.XUATHUY_SUM_SOLUONG,0) AS XUATHUY_SL, NVL(a.XUATHUY_SUM_THANHTIEN,0) AS XUATHUY_GT,
        NVL(a.XUATTRANCC_SUM_SOLUONG,0) AS XUATTRANCC_SL, NVL(a.XUATTRANCC_SUM_THANHTIEN,0) AS XUATTRANCC_GT,
        NVL(a.XUATDIEUCHINH_SUM_SOLUONG,0) AS XUATDC_SL, NVL(a.XUATDIEUCHINH_SUM_THANHTIEN,0) AS XUATDC_GT,
        NVL(a.NHBANTL_SUM_SOLUONG,0) AS NHAPBANTL_SL, NVL(a.NHBANTL_SUM_THANHTIEN,0) AS NHAPBANTL_GT,
        NVL(a.TONDAUKY_SUM_SOLUONG,0) AS TONDAUKY_SL, NVL(a.TONDAUKY_SUM_THANHTIEN,0) AS TONDAUKY_GT
        FROM (
            SELECT MAVATTU, MALOAIVATTU, MANHOMVATTU,SOLUONG, DONGIA,THANHTIEN,UNITCODE,MAKHO,MANHACUNGCAP,LOAICHUNGTU,NGAYCHUNGTU,NGAYDUYETPHIEU FROM XUATNHAPTON_TEMP)
            PIVOT ( SUM(SOLUONG) AS SUM_SOLUONG, SUM(NVL(THANHTIEN,0)) as SUM_THANHTIEN
              FOR LOAICHUNGTU
              IN (''1'' AS XUATBANLEQUAY,''2'' AS XUATBANLETRALAI, ''NMUA'' AS NMUA, ''NHAPKIEMKE'' AS NHAPKIEMKE,''XUATKIEMKE'' AS XUATKIEMKE, ''NHAPCHUYENKHO'' AS NHAPCHUYENKHO, ''NHAPSTTHANHVIEN'' AS NHAPSTTHANHVIEN, ''XUATCHUYENKHO'' AS XUATCHUYENKHO, 
              ''XUATSTTHANHVIEN'' AS XUATSTTHANHVIEN, ''XBANLE'' AS XUATBANLE,''NHAPDIEUCHINH'' AS NHAPDIEUCHINH,''NHAPHANGAM'' AS NHAPHANGAM,''XUATHUYHANGHONG'' AS XUATHUYHANGHONG,''XUATHUY'' AS XUATHUY, ''XUATBANBUON'' AS XUATBANBUON,
              ''XUATTRANCC'' AS XUATTRANCC,''XUATDIEUCHINH'' AS XUATDIEUCHINH,''NHBANTL'' AS NHBANTL,''TONDAUKY'' AS TONDAUKY)
        ) a ORDER BY a.MAVATTU,a.MALOAIVATTU,a.MANHOMVATTU,a.NGAYDUYETPHIEU';



        --Group sau khi Pivot
        QUERY_STR  :=' SELECT U.MAVATTU,U.MALOAIVATTU, U.MANHOMVATTU, U.UNITCODE,U.MAKHO,U.MANHACUNGCAP,
        SUM(U.XBANLEQUAY_SL) AS XBANLEQUAY_SL , SUM(U.XBANLEQUAY_GT) AS XBANLEQUAY_GT,
        SUM(U.XBANLETL_SL) AS XBANLETL_SL  , SUM(U.XBANLETL_GT) AS XBANLETL_GT,
        SUM(U.NMUA_SL) AS NMUA_SL , SUM(U.NMUA_GT) AS NMUA_GT,
        SUM(U.NHAPKIEMKE_SL) AS NHAPKIEMKE_SL, SUM(U.NHAPKIEMKE_GT) AS NHAPKIEMKE_GT,
        SUM(U.XUATKIEMKE_SL) AS XUATKIEMKE_SL, SUM(U.XUATKIEMKE_GT) AS XUATKIEMKE_GT,
        SUM(U.NHAPCHUYENKHO_SL) AS NHAPCHUYENKHO_SL, SUM(U.NHAPCHUYENKHO_GT) AS NHAPCHUYENKHO_GT,
        SUM(U.NHAPSTTHANHVIEN_SL) AS NHAPSTTHANHVIEN_SL, SUM(U.NHAPSTTHANHVIEN_GT) AS NHAPSTTHANHVIEN_GT,
        SUM(U.XUATCHUYENKHO_SL) AS XUATCHUYENKHO_SL, SUM(U.XUATCHUYENKHO_GT) AS XUATCHUYENKHO_GT,
        SUM(U.XUATSTTHANHVIEN_SL) AS XUATSTTHANHVIEN_SL, SUM(U.XUATSTTHANHVIEN_GT) AS XUATSTTHANHVIEN_GT,
        SUM(U.XBANLE_SL) AS XBANLE_SL, SUM(U.XBANLE_GT) AS XBANLE_GT,
        SUM(U.XUATBANBUON_SL) AS XUATBANBUON_SL, SUM(U.XUATBANBUON_GT) AS XUATBANBUON_GT,
        SUM(U.NHAPDIEUCHINH_SL) AS NHAPDIEUCHINH_SL, SUM(U.NHAPDIEUCHINH_GT) AS NHAPDIEUCHINH_GT,
        SUM(U.NHAPHANGAM_SL) AS NHAPHANGAM_SL, SUM(U.NHAPHANGAM_GT) AS NHAPHANGAM_GT,
        SUM(U.XUATHUYHH_SL) AS XUATHUYHH_SL, SUM(U.XUATHUYHH_GT) AS XUATHUYHH_GT,
        SUM(U.XUATHUY_SL) AS XUATHUY_SL, SUM(U.XUATHUY_GT) AS XUATHUY_GT,
        SUM(U.XUATTRANCC_SL) AS XUATTRANCC_SL, SUM(U.XUATTRANCC_GT) AS XUATTRANCC_GT,
        SUM(U.XUATDC_SL) AS XUATDC_SL, SUM(U.XUATDC_GT) AS XUATDC_GT,
        SUM(U.NHAPBANTL_SL) AS NHAPBANTL_SL, SUM(U.NHAPBANTL_GT) AS NHAPBANTL_GT,
        SUM(U.TONDAUKY_SL) AS TONDAUKY_SL, SUM(U.TONDAUKY_GT) AS TONDAUKY_GT
        FROM ('||QUERY_STR||') U 
        GROUP BY U.MAVATTU,U.MALOAIVATTU, U.MANHOMVATTU, U.UNITCODE, U.MAKHO,U.MANHACUNGCAP
        '; 


        --TÌM BẢNG XUẤT NHẬP TỒN CUỐI KỲ
        BEGIN

        SELECT KY, NAM INTO KY_KETTHUC, NAM_KETTHUC FROM DM_KYKETOAN WHERE TO_DATE(DENNGAY, 'dd/MM/yyyy') = TO_DATE(P_DENNGAY, 'dd/MM/yyyy') AND UNITCODE = P_UNITCODE AND TRANGTHAI = 10;
           EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);   
        END;--End TÌM KỲ
        RESULT_STR := '
        SELECT H.MAVATTU,H.MALOAIVATTU, H.MANHOMVATTU, H.UNITCODE,H.MAKHO,H.MANHACUNGCAP,
        NVL(H.XBANLEQUAY_SL,0) AS XBANLEQUAY_SL, NVL(H.XBANLEQUAY_GT,0) AS XBANLEQUAY_GT,
        NVL(H.XBANLETL_SL,0) AS XBANLETL_SL , NVL(H.XBANLETL_GT,0) AS XBANLETL_GT,
        NVL(H.NMUA_SL,0) AS NMUA_SL, NVL(H.NMUA_GT,0) AS NMUA_GT,
        NVL(H.NHAPKIEMKE_SL,0) AS NHAPKIEMKE_SL, NVL(H.NHAPKIEMKE_GT,0) AS NHAPKIEMKE_GT,
        NVL(H.XUATKIEMKE_SL,0) AS XUATKIEMKE_SL, NVL(H.XUATKIEMKE_GT,0) AS XUATKIEMKE_GT ,
        NVL(H.NHAPCHUYENKHO_SL,0) AS NHAPCHUYENKHO_SL, NVL(H.NHAPCHUYENKHO_GT,0) AS NHAPCHUYENKHO_GT,
        NVL(H.NHAPSTTHANHVIEN_SL,0) AS NHAPSTTHANHVIEN_SL, NVL(H.NHAPSTTHANHVIEN_GT,0) AS NHAPSTTHANHVIEN_GT,
        NVL(H.XUATCHUYENKHO_SL,0) AS XUATCHUYENKHO_SL, NVL(H.XUATCHUYENKHO_GT,0) AS XUATCHUYENKHO_GT,
        NVL(H.XUATSTTHANHVIEN_SL,0) AS XUATSTTHANHVIEN_SL, NVL(H.XUATSTTHANHVIEN_GT,0) AS XUATSTTHANHVIEN_GT,
        NVL(H.XBANLE_SL,0) AS XBANLE_SL, NVL(H.XBANLE_GT,0) AS XBANLE_GT,
        NVL(H.XUATBANBUON_SL,0) AS XUATBANBUON_SL, NVL(H.XUATBANBUON_GT,0) AS XUATBANBUON_GT,
        NVL(H.NHAPDIEUCHINH_SL,0) AS NHAPDIEUCHINH_SL, NVL(H.NHAPDIEUCHINH_GT,0) AS NHAPDIEUCHINH_GT,
        NVL(H.NHAPHANGAM_SL,0) AS NHAPHANGAM_SL, NVL(H.NHAPHANGAM_GT,0) AS NHAPHANGAM_GT,
        NVL(H.XUATHUYHH_SL,0) AS XUATHUYHH_SL, NVL(H.XUATHUYHH_GT,0) AS XUATHUYHH_GT,
        NVL(H.XUATHUY_SL,0) AS XUATHUY_SL, NVL(H.XUATHUY_GT,0) AS XUATHUY_GT,
        NVL(H.XUATTRANCC_SL,0) AS XUATTRANCC_SL, NVL(H.XUATTRANCC_GT,0) AS XUATTRANCC_GT,
        NVL(H.XUATDC_SL,0) AS XUATDC_SL, NVL(H.XUATDC_GT,0) AS XUATDC_GT,
        NVL(H.NHAPBANTL_SL,0) AS NHAPBANTL_SL, NVL(H.NHAPBANTL_GT,0) AS NHAPBANTL_GT,
        NVL(H.TONDAUKY_SL,0) AS TONDAUKY_SL,NVL(H.TONDAUKY_GT,0) AS TONDAUKY_GT,NVL(C.TONCUOIKYSL,0) AS TONCUOIKY_SL,NVL(C.TONCUOIKYGT,0) AS TONCUOIKY_GT
        FROM ('||QUERY_STR||') H 
        LEFT JOIN XNT_'|| NAM_KETTHUC ||'_KY_'||KY_KETTHUC||' C ON H.MAVATTU = C.MAVATTU AND H.MAKHO = C.MAKHO AND H.UNITCODE = C.UNITCODE 
        ';
        --START RETURN RESULT...
        IF P_GROUPBY = 'MAKHO' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'X.MAKHO, F.TENKHO,X.MAVATTU,G.TENVATTU';
        P_SELECT_COLUMNS_GROUPBY:= 'X.MAKHO AS MACHA, F.TENKHO AS TENCHA,X.MAVATTU AS MACON, G.TENVATTU AS TENCON';
        P_TABLE_GROUPBY:= ' LEFT JOIN DM_KHO F ON X.MAKHO = F.MAKHO AND F.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%'' ';
        P_ORDERBY := 'X.MAKHO, F.TENKHO,X.MAVATTU,G.TENVATTU';
        END;

        ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'X.MANHOMVATTU, F.TENNHOMVT,X.MAVATTU,G.TENVATTU';
        P_SELECT_COLUMNS_GROUPBY:= ' X.MANHOMVATTU AS MACHA, F.TENNHOMVT AS TENCHA,X.MAVATTU AS MACON, G.TENVATTU AS TENCON';
        P_TABLE_GROUPBY:= ' LEFT JOIN DM_NHOMVATTU F ON X.MANHOMVATTU = F.MANHOMVTU AND F.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%'' ';
        P_ORDERBY := 'X.MANHOMVATTU, F.TENNHOMVT,X.MAVATTU,G.TENVATTU';
        END;

        ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
        BEGIN
        P_COLUMNS_GROUPBY:= 'X.MALOAIVATTU, F.TENLOAIVT,X.MAVATTU,G.TENVATTU';
        P_SELECT_COLUMNS_GROUPBY:= ' X.MALOAIVATTU AS MACHA, F.TENLOAIVT AS TENCHA,X.MAVATTU AS MACON, G.TENVATTU AS TENCON';
        P_TABLE_GROUPBY:= ' LEFT JOIN DM_LOAIVATTU F ON X.MALOAIVATTU = F.MALOAIVATTU AND F.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%'' ';
        P_ORDERBY := 'X.MALOAIVATTU, F.TENLOAIVT,X.MAVATTU,G.TENVATTU';
        END;

        ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
        BEGIN
        P_SELECT_COLUMNS_GROUPBY:= 'X.MANHACUNGCAP AS MACHA,F.TENKH AS TENCHA,X.MAVATTU AS TENCON, G.TENVATTU AS TENCON';
        P_TABLE_GROUPBY:= 'LEFT JOIN DM_KHACHHANG F ON X.MANHACUNGCAP = F.MAKH AND F.LOAIKHACHHANG =1 AND F.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%'' ';   
        P_COLUMNS_GROUPBY:= 'X.MANHACUNGCAP,F.TENKH,X.MAVATTU,G.TENVATTU';
        P_ORDERBY := 'X.MANHACUNGCAP,F.TENKH,X.MAVATTU,G.TENVATTU';
        END;
        ELSE 
        BEGIN
        P_COLUMNS_GROUPBY:= 'X.MAVATTU,G.TENVATTU';
        P_SELECT_COLUMNS_GROUPBY:= 'X.MAVATTU AS MACHA,G.TENVATTU AS TENCHA,X.MAVATTU AS MACON,G.TENVATTU AS TENCON';
        P_TABLE_GROUPBY:= '';   
        P_ORDERBY := 'X.MAVATTU,G.TENVATTU';
        END;
        END IF;  

         RESULT_STR:=' SELECT '||P_SELECT_COLUMNS_GROUPBY||',SUM(X.XBANLEQUAY_SL) AS XBANLEQUAY_SL,SUM(X.XBANLEQUAY_GT) AS XBANLEQUAY_GT,
         SUM(X.XBANLETL_SL) AS XBANLETL_SL, SUM(X.XBANLETL_GT) AS XBANLETL_GT,SUM(X.NMUA_SL) AS NMUA_SL,SUM(X.NMUA_GT) AS NMUA_GT,
         SUM(X.NHAPKIEMKE_SL) AS NHAPKIEMKE_SL,SUM(X.NHAPKIEMKE_GT) AS NHAPKIEMKE_GT,
         SUM(X.XUATKIEMKE_SL) AS XUATKIEMKE_SL,SUM(X.XUATKIEMKE_GT) AS XUATKIEMKE_GT,
         SUM(X.NHAPCHUYENKHO_SL) AS NHAPCHUYENKHO_SL,SUM(X.NHAPCHUYENKHO_GT) AS NHAPCHUYENKHO_GT,
         SUM(X.NHAPSTTHANHVIEN_SL) AS NHAPSTTHANHVIEN_SL,SUM(X.NHAPSTTHANHVIEN_GT) AS NHAPSTTHANHVIEN_GT,SUM(X.XUATCHUYENKHO_SL) AS XUATCHUYENKHO_SL,
         SUM(X.XUATCHUYENKHO_GT) AS XUATCHUYENKHO_GT,SUM(X.XUATSTTHANHVIEN_SL) AS XUATSTTHANHVIEN_SL,
         SUM(X.XUATSTTHANHVIEN_GT) AS XUATSTTHANHVIEN_GT,SUM(X.XBANLE_SL) AS XBANLE_SL,SUM(X.XBANLE_GT) AS XBANLE_GT,SUM(X.XUATBANBUON_SL) AS XUATBANBUON_SL,SUM(X.XUATBANBUON_GT) AS XUATBANBUON_GT,
         SUM(X.NHAPDIEUCHINH_SL) AS NHAPDIEUCHINH_SL,SUM(X.NHAPDIEUCHINH_GT) AS NHAPDIEUCHINH_GT,SUM(X.NHAPHANGAM_SL) AS NHAPHANGAM_SL,SUM(X.NHAPHANGAM_GT) AS NHAPHANGAM_GT,SUM(X.XUATHUYHH_SL) AS XUATHUYHH_SL,
         SUM(X.XUATHUYHH_GT) AS XUATHUYHH_GT,SUM(X.XUATHUY_SL) AS XUATHUY_SL,SUM(X.XUATHUY_GT) AS XUATHUY_GT,
         SUM(X.XUATTRANCC_SL) AS XUATTRANCC_SL,SUM(X.XUATTRANCC_GT) AS XUATTRANCC_GT,SUM(X.XUATDC_SL) AS XUATDC_SL,SUM(X.XUATDC_GT) AS XUATDC_GT,SUM(X.NHAPBANTL_SL) AS NHAPBANTL_SL,SUM(X.NHAPBANTL_GT) AS NHAPBANTL_GT,
         SUM(X.TONDAUKY_SL) AS TONDAUKY_SL, SUM(X.TONDAUKY_GT) AS TONDAUKY_GT, SUM(X.TONCUOIKY_SL) AS TONCUOIKY_SL, SUM(X.TONCUOIKY_GT) AS TONCUOIKY_GT
         FROM ('||RESULT_STR||') X  
         LEFT JOIN DM_VATTU G ON X.MAVATTU = G.MAVATTU AND G.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
         '||P_TABLE_GROUPBY||'
         GROUP BY '||P_COLUMNS_GROUPBY||' ORDER BY '||P_ORDERBY||'';      
          BEGIN
                --DBMS_OUTPUT.put_line (RESULT_STR);
                OPEN XTNCOLLECTION FOR RESULT_STR;
                EXCEPTION
                   WHEN NO_DATA_FOUND
                   THEN
                      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
                   WHEN OTHERS
                   THEN
                      DBMS_OUTPUT.put_line (RESULT_STR  || SQLERRM);
         END;
END BAOCAO_XNTNEW_CHITIET;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_XNTNEW_CHITIET
--------------------------------------------------------