create or replace PACKAGE XUATBAN AS
--VER3 : HUYNQ
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XBAN_CHITIET_THEOHH(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
end XUATBAN;
/
create or replace PACKAGE BODY XUATBAN AS
--ver 4:HUYNQ
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  

IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.TONGBAN - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + g.TYLE_VAT_VAO/100)) END) AS VON
                          ,SUM(NVL(ct.TIENGIAMGIA,0)) AS TIENKHUYENMAI
                          ,SUM((ct.SOLUONG * ct.DONGIA - NVL(ct.TIENGIAMGIA,0))/(1+ g.TYLE_VAT_RA /100)) as DOANHTHU 
                          ,SUM(ct.THANHTIEN ) as TONGBAN
                          ,SUM(((g.TYLE_VAT_RA / 100)*(ct.SOLUONG *ct.DONGIA - NVL(ct.TIENGIAMGIA,0)))/(1+ g.TYLE_VAT_RA /100)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XBAN_TONGHOP;  

PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,  b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN , b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.TONGBAN - a.VON) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + g.TYLE_VAT_VAO/100)) END) AS VON
                          ,SUM(NVL(ct.TIENGIAMGIA,0)) AS TIENKHUYENMAI
                          ,SUM((ct.SOLUONG * ct.DONGIA - NVL(ct.TIENGIAMGIA,0))/(1+ g.TYLE_VAT_RA /100)) as DOANHTHU 
                          ,SUM(ct.THANHTIEN ) as TONGBAN
                          ,SUM(((g.TYLE_VAT_RA / 100)*(ct.SOLUONG *ct.DONGIA - NVL(ct.TIENGIAMGIA,0)))/(1+ g.TYLE_VAT_RA /100)) as TIENTHUE
                          from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_XBAN_CHITIET;

PROCEDURE BAOCAO_XBAN_CHITIET_THEOHH(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);

  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.TONGBAN - a.VON) AS LAIBANLE, a.MACHUNGTUPK as MaCon, TO_CHAR(a.NGAYCHUNGTU) as TenCon,a.MAVATTU as MaCha, a.TENVATTU as TenCha 
  from (
  SELECT  b.MAVATTU AS MAVATTU, b.TENVATTU AS TENVATTU, t.MACHUNGTUPK AS MACHUNGTUPK, t.NGAYCHUNGTU AS NGAYCHUNGTU
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + g.TYLE_VAT_VAO/100)) END) AS VON
                          ,SUM(NVL(ct.TIENGIAMGIA,0)) AS TIENKHUYENMAI
                          ,SUM((ct.SOLUONG * ct.DONGIA - NVL(ct.TIENGIAMGIA,0))/(1+ g.TYLE_VAT_RA /100)) as DOANHTHU 
                          ,SUM(ct.THANHTIEN ) as TONGBAN
                          ,SUM(((g.TYLE_VAT_RA / 100)*(ct.SOLUONG *ct.DONGIA - NVL(ct.TIENGIAMGIA,0)))/(1+ g.TYLE_VAT_RA /100)) as TIENTHUE
            from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	  '||P_EXPRESSION||' group by  b.MAVATTU, b.TENVATTU,t.MACHUNGTUPK, t.NGAYCHUNGTU
    order by t.NGAYCHUNGTU DESC) a';
 DBMS_OUTPUT.put_line (QUERY_STR );    
 OPEN cur FOR QUERY_STR; 
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);  

  END BAOCAO_XBAN_CHITIET_THEOHH;

END XUATBAN;