create or replace PACKAGE XUATBAN AS
--VER 9: HUYNQ
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XKHAC_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_XKHAC_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCX_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_DCX_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);

end XUATBAN;
/
create or replace PACKAGE BODY XUATBAN AS
--ver 9:HUYNQ
--Modified on: 21/3/2017: THEOGIAODICH
PROCEDURE BAOCAO_XBAN_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
  
IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 2';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.TONGBAN - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,SUM(NVL(ct.TIENGIAMGIA,0)) AS TIENKHUYENMAI
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0) - NVL(ct.TIENGIAMGIA,0))/(1+ NVL(g.TYLE_VAT_RA,0) /100)) as DOANHTHU 
                          ,SUM(NVL(ct.THANHTIEN,0) ) as TONGBAN
                          ,SUM(((NVL(g.TYLE_VAT_RA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0) - NVL(ct.TIENGIAMGIA,0)))/(1+ NVL(g.TYLE_VAT_RA,0) /100)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XBAN_TONGHOP;  

PROCEDURE BAOCAO_XBAN_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_MAKHACHHANG IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  


IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 2';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.TONGBAN - a.VON) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0)) AS VON
                          ,SUM(NVL(ct.TIENGIAMGIA,0)) AS TIENKHUYENMAI
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0) - NVL(ct.TIENGIAMGIA,0))/(1+ NVL(g.TYLE_VAT_RA,0) /100)) as DOANHTHU 
                          ,SUM(NVL(ct.THANHTIEN,0) ) as TONGBAN
                          ,SUM(((NVL(g.TYLE_VAT_RA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0) - NVL(ct.TIENGIAMGIA,0)))/(1+ NVL(g.TYLE_VAT_RA,0) /100)) as TIENTHUE
                          from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_XBAN_CHITIET;

PROCEDURE BAOCAO_XKHAC_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  

IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + NVL(g.TYLE_VAT_VAO,0)/100)) END) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XKHAC'' AND t.MALYDOKHAC = '''||P_PTHUCXUAT||'''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XKHAC_TONGHOP;  

PROCEDURE BAOCAO_XKHAC_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE, c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE , b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,NVL(ct.DONGIA,0) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
                  from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XKHAC'' AND t.MALYDOKHAC = '''||P_PTHUCXUAT||'''
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  ct.DONGIA,'||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_XKHAC_CHITIET;
PROCEDURE BAOCAO_DCX_TONGHOP(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  

IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.MA = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,SUM(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                                ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) 
                                * ct.SOLUONG * (1 + NVL(g.TYLE_VAT_VAO,0)/100)) END) AS VON
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCX'' '||P_PTHUCXUAT||'
left join DMVATTU b on b.MAVATTU = ct.MAHANG
left join '||P_KY||' k on k.MAVATTU = ct.MAHANG AND k.UNITCODE = t.UNITCODE AND k.MAKHO = t.MAKHOXUAT
left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_DCX_TONGHOP;  

PROCEDURE BAOCAO_DCX_CHITIET(P_KY IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCXUAT IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MAKHOHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,b.MANHOMVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' left join DMKHACHHANG c ON a.GROUPCODE = c.MAKH AND c.LOAIKHACHHANG = 1';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.LOAICHUNGTU, t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.LOAICHUNGTU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK,t.LOAICHUNGTU AS LOAICHUNGTU ,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU, b.BARCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon, a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN , b.BARCODE AS BARCODE,t.NGAYCHUNGTU';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

  QUERY_STR:= 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN
                     ,TO_CHAR(CASE (NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0)) WHEN 0 THEN 0
                          ELSE ((NVL(k.TONDAUKYGT,0) + NVL(k.NHAPGT,0))/(NVL(k.TONDAUKYSL,0) + NVL(k.NHAPSL,0))) END) as VON
                     ,TO_CHAR(a.TIENTHUE) AS TIENTHUE,TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.DOANHTHU + a.TIENTHUE) AS TONGBAN
                     ,TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(0) AS LAIBANLE, 
  '||P_SELECT_COLUMNS_OUT_GROUPBY||'
  from (
  SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,t.UNITCODE AS MADONVI
                          ,t.MAKHOXUAT AS MAKHOXUAT
                          ,0 AS TIENKHUYENMAI
                          ,SUM(ct.SOLUONG * ct.DONGIA) as DOANHTHU 
                          ,SUM((NVL(g.TYLE_VAT_VAO,0) / 100)*(ct.SOLUONG *ct.DONGIA)) as TIENTHUE
                      from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCX'' '||P_PTHUCXUAT||'
left join DMVATTU b on b.MAVATTU = ct.MAHANG

left join DM_VATTU_GIACA g on g.MAVATTU = ct.MAHANG AND g.MADONVI = t.UNITCODE
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  t.UNITCODE,t.MAKHOXUAT,'||P_COLUMNS_GROUPBY||'
  order by t.NGAYCHUNGTU DESC) a
  left join '||P_KY||' k on k.MAVATTU = a.MA AND k.UNITCODE = a.MADONVI AND k.MAKHO = a.MAKHOXUAT
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_DCX_CHITIET;
END XUATBAN;