create or replace PACKAGE            "GIAODICHQUAY" AS
PROCEDURE BAOCAO_GIAODICHQUAY(P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_MADONVI IN NVARCHAR2,P_MAMAYBAN IN VARCHAR2,P_MANGUOITAO IN VARCHAR2,XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_QUAYGD_TONGHOP(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_QUAYGD_CHITIET(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_BLETRALAI_TONGHOP(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2,P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR);
PROCEDURE BAOCAO_BLETRALAI_CHITIET(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2,P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR);
end GIAODICHQUAY;

/
create or replace PACKAGE BODY            "GIAODICHQUAY" AS
--Author: HUYNQ
--Edit by: HuyNQ. update date : 26/10/2017
-- 
PROCEDURE BAOCAO_GIAODICHQUAY(P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_MADONVI IN NVARCHAR2,P_MAMAYBAN IN VARCHAR2,P_MANGUOITAO IN VARCHAR2,XTNCOLLECTION OUT SYS_REFCURSOR) IS
      P_SQL_CLEAR  VARCHAR2(32767);
      P_SQL_INSERT_BAN  VARCHAR2(32767);
      P_SQL_INSERT_BANBUON  VARCHAR2(32767);
      QUERY_STR  VARCHAR2(32767);
      P_SQL_INSERT_TRA_LAI VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767):='';
      DK_GROUPBY VARCHAR2(32767):= '';
      BEGIN

            IF TRIM(P_MAMAYBAN) IS NOT NULL THEN
           DK_WHERE := DK_WHERE || ' AND MAQUAYBAN IN ('''||P_MAMAYBAN||''')';
           DK_GROUPBY := DK_GROUPBY || ',MAQUAYBAN';
           END IF;
           IF TRIM(P_MANGUOITAO) IS NOT NULL THEN
           DK_WHERE := DK_WHERE || ' AND MANGUOITAO IN ('''||P_MANGUOITAO||''')';
           DK_GROUPBY := DK_GROUPBY || ',MANGUOITAO';
           END IF;

         P_SQL_CLEAR:= 'DELETE FROM TEMP_GDQ';
          P_SQL_INSERT_BAN := 'INSERT INTO TEMP_GDQ a(a.MADONVI,a.MANGUOITAO,a.MAQUAYBAN,a.NGUOITAO,a.TONGBAN,a.STT_TEMP)
              (SELECT TO_NCHAR(MADONVI) AS MADONVI,
                TO_NCHAR(MANGUOITAO) AS MANGUOITAO,
                TO_NCHAR(MAQUAYBAN) AS MAQUAYBAN,
                TO_NCHAR(NGUOITAO) AS NGUOITAO, 
                SUM(TTIENCOVAT) AS TONGBAN,1
                            FROM V_GDQUAY_HANGQUAY 
                            WHERE MADONVI LIKE '''||P_MADONVI||'%'' AND LOAIGIAODICH = 1 AND NGAYPHATSINH >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND  NGAYPHATSINH <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')  '||DK_WHERE||'
                            group by MADONVI,NGUOITAO,MANGUOITAO,MAQUAYBAN )';
           P_SQL_INSERT_BANBUON := 'INSERT INTO TEMP_GDQ a(a.MADONVI,a.MANGUOITAO,a.MAQUAYBAN,a.NGUOITAO,a.TONGBAN,a.STT_TEMP)
           (SELECT TO_NCHAR(UNITCODE) AS MADONVI,
                TO_NCHAR(NGUOITAO) AS MANGUOITAO,
                TO_NCHAR(''QUAYBANBUON'') AS MAQUAYBAN, 
                '''' AS NGUOITAO,
                SUM(THANHTIEN) AS TONGBAN,1
              FROM VIEW_VATTUGD_XNT
          WHERE  UNITCODE LIKE '''||P_MADONVI||'%'' 
          AND NGAYCHUNGTU >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
          AND NGAYCHUNGTU <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')
          AND TRANGTHAI = 10 AND LOAICHUNGTU=''XBAN'' 
          GROUP BY UNITCODE,NGUOITAO)';
            P_SQL_INSERT_TRA_LAI := 'UPDATE  TEMP_GDQ a SET TONGTRALAI =(SELECT sum(ttiencovat) as TONGTRALAI
                                    FROM V_GDQUAY_HANGQUAY 
                                    WHERE MADONVI LIKE '''||P_MADONVI||'%'' AND LOAIGIAODICH = 2 AND NGAYPHATSINH >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                                    AND NGAYPHATSINH <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND MAQUAYBAN = a.MAQUAYBAN AND MANGUOITAO = a.MANGUOITAO
                                    group by MADONVI,MANGUOITAO,MAQUAYBAN)'; 
           QUERY_STR := 'SELECT * FROM TEMP_GDQ';     
       BEGIN
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_BAN);
            DBMS_OUTPUT.PUT_LINE('------------------');
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_BANBUON);
            DBMS_OUTPUT.PUT_LINE('------------------');
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_TRA_LAI); 
            EXECUTE IMMEDIATE P_SQL_CLEAR;
            EXECUTE IMMEDIATE P_SQL_INSERT_BAN;
            EXECUTE IMMEDIATE P_SQL_INSERT_BANBUON;
            EXECUTE IMMEDIATE P_SQL_INSERT_TRA_LAI;
            OPEN XTNCOLLECTION FOR QUERY_STR;
       END;
  END BAOCAO_GIAODICHQUAY;
PROCEDURE BAOCAO_QUAYGD_TONGHOP(P_GROUPBY IN VARCHAR2,P_MAKHO IN VARCHAR2,P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_JOIN_DKIEN VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAKHOHANG IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_XUATXU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAXUATXU IN ('||P_XUATXU||')';
END IF;
IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVI AS MA ';
P_JOIN_DKIEN := 'a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.MAKHOHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.MAKHOHANG AS MA,t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU  AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= '  left join DMKHACHHANG c ON a.MA = c.MAKH AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAGIAODICH, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'TO_CHAR(a.MA) AS Ma, TO_CHAR(a.TEN) AS Ten,TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 't.MAGIAODICH AS MA, t.NGAYPHATSINH AS TEN, t.MADONVI AS MADONVI ';
P_TABLE_GROUPBY:= ' ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.MADONVI = j.MADONVI AND a.TEN = j.TEN';
END;
ELSIF P_GROUPBY = 'MAXUATXU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAXUATXU, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAXUATXU AS Ma, c.TENXUATXU AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAXUATXU as MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMXUATXU c ON a.MA = c.MAXUATXU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.MADONVI AS MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA AND a.TEN = j.TEN';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.MADONVI ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VONCHUAVAT) as VONCHUAVAT,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENCHIETKHAU) AS TIENCHIETKHAU, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.LAIBANLE) AS LAIBANLE,
                     TO_CHAR(j.TIENTHE) AS TIENTHE, TO_CHAR(j.TIENCOD) AS TIENCOD, TO_CHAR(j.TIENMAT) AS TIENMAT, TO_CHAR(a.TIENVOUCHER) AS TIENVOUCHER,
                     '||P_SELECT_COLUMNS_OUT_GROUPBY||'
from 
(SELECT '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VONCHUAVAT
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS VON
                          ,SUM(NVL(ct.TIENCHIETKHAU, 0)) AS TIENCHIETKHAU
                          ,SUM(NVL(ct.TIENKHUYENMAI, 0)) AS TIENKHUYENMAI
                          ,SUM(NVL(ct.TIENVOUCHER, 0)) AS TIENVOUCHER
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100) ) as DOANHTHU 
                          ,SUM( NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0)) as TONGBAN
                          ,SUM((NVL(ct.VATBAN,0) / 100) * ((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0)- NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100)) ) as TIENTHUE
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0) - NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS LAIBANLE 
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 1
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' ) a
--SUM CHILDREN
INNER JOIN  (SELECT '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(t.TIENTHE,0)) AS TIENTHE
                          ,SUM(NVL(t.TIENCOD,0)) AS TIENCOD
                          ,SUM(NVL(t.TIENMAT,0)) AS TIENMAT
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.UNITCODE,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 1
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' ) j on '||P_JOIN_DKIEN||'
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_QUAYGD_TONGHOP;

PROCEDURE BAOCAO_QUAYGD_CHITIET(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAKHOHANG IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_XUATXU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAXUATXU IN ('||P_XUATXU||')';
END IF;

IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich , c.MADONVI AS MaCha, c.TENDONVI AS TenCha, TO_CHAR(a.GROUPCODE) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, t.NGAYPHATSINH AS NGAYPHATSINH , t.MADONVI AS GROUPCODE ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.GROUPCODE = c.MADONVI ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, ct.MAKHOHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich , c.MAKHO AS MaCha, c.TENKHO AS TenCha, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, t.NGAYPHATSINH AS NGAYPHATSINH , ct.MAKHOHANG  AS GROUPCODE, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, b.MANHOMVATTU,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN , b.MANHOMVATTU AS GROUPCODE, t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, b.MALOAIVATTU,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE,a.MA AS MaCon, a.TEN AS TenCon,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MALOAIVATTU AS GROUPCODE,t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU,  b.MAKHACHHANG,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, c.MANCC AS MaCha, c.TENNCC AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MAKHACHHANG AS GROUPCODE,t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.GROUPCODE = c.MANCC AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE,b.MAVATTU, b.TENVATTU,t.MAGIAODICH,t.NGAYPHATSINH,t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE,a.MAVATTU AS MaCon, a.TENVATTU AS TenCon,  a.MAGIAODICH AS MaCha, a.NGAYPHATSINH AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich,TO_CHAR(a.MADONVI) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MAVATTU, b.TENVATTU AS TENVATTU, t.MAGIAODICH AS MAGIAODICH,t.NGAYPHATSINH AS NGAYPHATSINH,t.MADONVI AS MADONVI';
P_TABLE_GROUPBY:= ' ';
END;
ELSIF P_GROUPBY = 'MAXUATXU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, b.MAXUATXU,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE,a.MA AS MaCon, a.TEN AS TenCon,c.MAXUATXU AS MaCha, c.TENXUATXU AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MAXUATXU AS GROUPCODE,t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMXUATXU c ON a.GROUPCODE = c.MAXUATXU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon,  a.MA AS MaCha, a.TEN AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE,b.MAVATTU AS MA, b.TENVATTU AS TEN ,t.NGAYPHATSINH AS NGAYPHATSINH,t.MADONVI AS MADONVI';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VONCHUAVAT) as VONCHUAVAT,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI, TO_CHAR(a.TIENCHIETKHAU) AS TIENCHIETKHAU,TO_CHAR(a.LAIBANLE) AS LAIBANLE,
                     TO_CHAR(a.TIENVOUCHER) AS TIENVOUCHER,
                     '||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VONCHUAVAT
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS VON
                          ,SUM(NVL(ct.TIENKHUYENMAI, 0)) AS TIENKHUYENMAI
                          ,SUM(NVL(ct.TIENCHIETKHAU, 0)) AS TIENCHIETKHAU
                          ,SUM(NVL(ct.TIENVOUCHER, 0)) AS TIENVOUCHER
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100) ) as DOANHTHU 
                          ,SUM( NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) as TONGBAN
                          ,SUM((NVL(ct.VATBAN,0) / 100) * ((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100)) ) as TIENTHUE
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0) - NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS LAIBANLE 
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.UNITCODE,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 1
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
      '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
     ORDER BY t.NGAYPHATSINH DESC) a	  
	  '||P_TABLE_GROUPBY;
 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_QUAYGD_CHITIET;

PROCEDURE BAOCAO_BLETRALAI_TONGHOP(P_GROUPBY IN VARCHAR2,P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_JOIN_DKIEN VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAKHOHANG IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  

IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVI AS MA ';
P_JOIN_DKIEN := 'a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.MA = c.MADONVI ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.MAKHOHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.MAKHOHANG AS MA,t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.MA = c.MAKHO AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.MA = c.MANHOMVTU  AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.MA = c.MALOAIVATTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.MADONVI AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA, t.MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA';
P_TABLE_GROUPBY:= '  left join DMKHACHHANG c ON a.MA = c.MAKH AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3)';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAGIAODICH, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'TO_CHAR(a.MA) AS Ma, TO_CHAR(a.TEN) AS Ten,TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 't.MAGIAODICH AS MA, t.NGAYPHATSINH AS TEN, t.MADONVI AS MADONVI ';
P_TABLE_GROUPBY:= ' ';
P_JOIN_DKIEN := 'a.MA = j.MA AND a.MADONVI = j.MADONVI AND a.TEN = j.TEN';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.MADONVI AS MADONVI ';
P_JOIN_DKIEN := 'a.MADONVI = j.MADONVI AND a.MA = j.MA AND a.TEN = j.TEN';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.MADONVI ';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VONCHUAVAT) as VONCHUAVAT,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENCHIETKHAU) AS TIENCHIETKHAU, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.LAIBANLE) AS LAIBANLE,
                     TO_CHAR(j.TIENTHE) AS TIENTHE, TO_CHAR(j.TIENCOD) AS TIENCOD, TO_CHAR(j.TIENMAT) AS TIENMAT, TO_CHAR(a.TIENVOUCHER) AS TIENVOUCHER,
                     '||P_SELECT_COLUMNS_OUT_GROUPBY||'
from 
(SELECT '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VONCHUAVAT
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS VON
                          ,SUM(NVL(ct.TIENCHIETKHAU, 0)) AS TIENCHIETKHAU
                          ,SUM(NVL(ct.TIENKHUYENMAI, 0)) AS TIENKHUYENMAI
                          ,SUM(NVL(ct.TIENVOUCHER, 0)) AS TIENVOUCHER
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100) ) as DOANHTHU 
                          ,SUM( NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0)) as TONGBAN
                          ,SUM((NVL(ct.VATBAN,0) / 100) * ((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0)- NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100)) ) as TIENTHUE
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENCHIETKHAU, 0) - NVL(ct.TIENVOUCHER, 0) - NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS LAIBANLE 
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.MADONVI,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 2
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' ) a
--SUM CHILDREN
INNER JOIN  (SELECT '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(t.TIENTHE,0)) AS TIENTHE
                          ,SUM(NVL(t.TIENCOD,0)) AS TIENCOD
                          ,SUM(NVL(t.TIENMAT,0)) AS TIENMAT
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.UNITCODE,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 2
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||' ) j on '||P_JOIN_DKIEN||'
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_BLETRALAI_TONGHOP;

PROCEDURE BAOCAO_BLETRALAI_CHITIET(P_GROUPBY IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAKHOHANG IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  


IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich , c.MADONVI AS MaCha, c.TENDONVI AS TenCha, TO_CHAR(a.GROUPCODE) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, t.NGAYPHATSINH AS NGAYPHATSINH , t.MADONVI AS GROUPCODE ';
P_TABLE_GROUPBY:= ' left join SYS_DONVI c ON a.GROUPCODE = c.MADONVI ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, ct.MAKHOHANG, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich , c.MAKHO AS MaCha, c.TENKHO AS TenCha, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, t.NGAYPHATSINH AS NGAYPHATSINH , ct.MAKHOHANG  AS GROUPCODE, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMKHO c ON a.GROUPCODE = c.MAKHO AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, b.MANHOMVATTU,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN , b.MANHOMVATTU AS GROUPCODE, t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMNHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, b.MALOAIVATTU,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE,a.MA AS MaCon, a.TEN AS TenCon,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MALOAIVATTU AS GROUPCODE,t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMLOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU,  b.MAKHACHHANG,t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon, c.MANCC AS MaCha, c.TENNCC AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE, b.MAVATTU AS MA, b.TENVATTU AS TEN, b.MAKHACHHANG AS GROUPCODE,t.NGAYPHATSINH AS NGAYPHATSINH, t.MADONVI';
P_TABLE_GROUPBY:= ' left join DMSUPPLIER c ON a.GROUPCODE = c.MANCC AND SUBSTR(a.MADONVI,0,3)= SUBSTR(c.UNITCODE,0,3) ';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE,b.MAVATTU, b.TENVATTU,t.MAGIAODICH,t.NGAYPHATSINH,t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE,a.MAVATTU AS MaCon, a.TENVATTU AS TenCon,  a.MAGIAODICH AS MaCha, a.NGAYPHATSINH AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich,TO_CHAR(a.MADONVI) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.BARCODE AS BARCODE, b.MAVATTU AS MAVATTU, b.TENVATTU AS TENVATTU, t.MAGIAODICH AS MAGIAODICH,t.NGAYPHATSINH AS NGAYPHATSINH,t.MADONVI AS MADONVI';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.BARCODE, b.MAVATTU, b.TENVATTU, t.NGAYPHATSINH, t.MADONVI';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.BARCODE AS BARCODE, a.MA AS MaCon, a.TEN AS TenCon,  a.MA AS MaCha, a.TEN AS TenCha,TO_CHAR(a.NGAYPHATSINH) AS NgayGiaoDich, TO_CHAR(a.MADONVI) AS MADONVI';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.BARCODE AS BARCODE,b.MAVATTU AS MA, b.TENVATTU AS TEN ,t.NGAYPHATSINH AS NGAYPHATSINH,t.MADONVI AS MADONVI';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select TO_CHAR(a.SOLUONGBAN) as SOLUONGBAN,TO_CHAR(a.VONCHUAVAT) as VONCHUAVAT,TO_CHAR(a.VON) as VON,TO_CHAR(a.TIENTHUE) AS TIENTHUE,
                     TO_CHAR(a.DOANHTHU) AS DOANHTHU,TO_CHAR(a.TONGBAN) AS TONGBAN, TO_CHAR(a.TIENKHUYENMAI) AS TIENKHUYENMAI,TO_CHAR(a.LAIBANLE) AS LAIBANLE,
                     TO_CHAR(a.TIENVOUCHER) AS TIENVOUCHER, TO_CHAR(a.TIENCHIETKHAU) AS TIENCHIETKHAU,
                     '||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VONCHUAVAT
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS VON
                          ,SUM(NVL(ct.TIENKHUYENMAI, 0)) AS TIENKHUYENMAI
                          ,SUM(NVL(ct.TIENCHIETKHAU, 0)) AS TIENCHIETKHAU
                          ,SUM(NVL(ct.TIENVOUCHER, 0)) AS TIENVOUCHER
                          ,SUM((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100) ) as DOANHTHU 
                          ,SUM( NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) as TONGBAN
                          ,SUM((NVL(ct.VATBAN,0) / 100) * ((NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0)) / (1+ NVL(ct.VATBAN,0) / 100)) ) as TIENTHUE
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.GIABANLECOVAT,0) - NVL(ct.TIENKHUYENMAI, 0) - NVL(ct.TIENVOUCHER, 0) - NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0) * (1 + NVL(b.TYLEVATVAO,0)/100)) AS LAIBANLE 
from NVHANGGDQUAY_ASYNCCLIENT ct 
inner join NVGDQUAY_ASYNCCLIENT t on t.MAGIAODICHQUAYPK = ct.MAGDQUAYPK 
left join V_VATTU_GIABAN b on b.MAVATTU = ct.MAVATTU AND SUBSTR(b.UNITCODE,0,3)= SUBSTR(t.MADONVI,0,3)
WHERE
    t.LOAIGIAODICH = 2
    AND t.MADONVI LIKE '''||P_UNITCODE||'%''
    AND t.NGAYPHATSINH <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYPHATSINH >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
      '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||'
     ORDER BY t.NGAYPHATSINH DESC) a	  
	  '||P_TABLE_GROUPBY;

 DBMS_OUTPUT.put_line (QUERY_STR );    
  OPEN cur FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     

  END BAOCAO_BLETRALAI_CHITIET;

END GIAODICHQUAY;