create or replace PROCEDURE            "BAOCAO_CNKH_CHITIET" (P_UNITCODE IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,  cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
SUB_QUERY_STR VARCHAR(32767);
P_EXPRESSION VARCHAR(32767):= '';
INSERT_STR VARCHAR(32767);
SUB_INSERT_STR VARCHAR(32767);
CREATE_TABLE VARCHAR(32767);
CHECK_EXIST_TABLE NUMBER;
CN_CUR SYS_REFCURSOR;
SUB_CUR SYS_REFCURSOR;
I_MAKHACHHANG VARCHAR(20);
I_UNITCODE VARCHAR(20);
I_AMMOUNT NUMBER(18,2) :=0;
I_PAYBEFORE NUMBER(18,2) :=0;
I_BORROWBEFORE NUMBER(18,2) :=0;
C_MACHUNGTU VARCHAR2(50);
C_LOAICHUNGTU VARCHAR2(20);
C_NGAYCT DATE;
C_MAKHACHHANG VARCHAR2(50);
C_UNITCODE VARCHAR2(20);
C_PAYNOW NUMBER(18,2);
C_BORROW_NOW NUMBER(18,2);
I_STT NUMBER(18,2) :=0;
BEGIN
--QUERY FOR KILL SESSION

 --SELECT INST_ID,SID,SERIAL# FROM gv$session WHERE SID = (SELECT SID FROM v$lock WHERE TYPE = 'TO' AND ID1
 --= (SELECT OBJECT_ID FROM DBA_OBJECTS WHERE OBJECT_NAME = 'TEMP_CONGNO'));
 --ALTER SYSTEM KILL SESSION 'sid,serial#,@inst_id';

    --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TEMP_CONGNO" 
   (	
   "STT" NUMBER(18,2) DEFAULT 0,
   "UNITCODE" NVARCHAR2(20), 
	"MAKHACHHANG" NVARCHAR2(20), 
	"MANHACUNGCAP" NVARCHAR2(20), 
	"NGAYCT" DATE, 
	"MACHUNGTU" NVARCHAR2(50), 
    "LOAICHUNGTU" NVARCHAR2(20),
	"TIENTHU" NUMBER(18,2) DEFAULT 0, 
	"TIENBAN" NUMBER(18,2) DEFAULT 0, 
	"TIENNO" NUMBER(18,2) DEFAULT 0
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''TEMP_CONGNO''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM TEMP_CONGNO';
   --BEGIN...
    IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
        P_EXPRESSION := P_EXPRESSION || 'AND u.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
    END IF;
    --GET ALL MAKHACHHANG, UNITCODE
    I_STT :=0;
    QUERY_STR := 'SELECT DISTINCT u.MAKHACHHANG, u.UNITCODE FROM V_VTCT_CONGNO u WHERE u.UNITCODE IS NOT NULL AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.MAKHACHHANG IS NOT NULL AND u.LOAICHUNGTU IN (''CNKH'',''XBAN'') AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') '||P_EXPRESSION||' ORDER BY u.MAKHACHHANG';
    OPEN CN_CUR FOR QUERY_STR;
    LOOP
         FETCH CN_CUR INTO I_MAKHACHHANG, I_UNITCODE;
         EXIT WHEN CN_CUR%NOTFOUND;    
         --CALCULATE 'TONDAUKY' FOR 'I_AMMOUNT'
         I_PAYBEFORE :=0;
         I_BORROWBEFORE :=0;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGTHU FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNKH'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_PAYBEFORE;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGBAN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''XBAN'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_BORROWBEFORE;

         I_AMMOUNT := NVL(I_BORROWBEFORE,0) - NVL(I_PAYBEFORE,0);
         I_STT := I_STT +1;
         --INSERT MAKHACHHANG,UNITCODE 'TONDAUKY'
         INSERT_STR:= 'INSERT INTO TEMP_CONGNO (STT, UNITCODE, MAKHACHHANG, TIENNO) VALUES ('||I_STT||','''||I_UNITCODE||''', '''||I_MAKHACHHANG||''', to_number('''||I_AMMOUNT||'''))';

         EXECUTE IMMEDIATE INSERT_STR;
         --CALCULATE AMMOUNT EACH RECORD. THEN INSERT...
         SUB_QUERY_STR := 'SELECT u.MACHUNGTU, u.LOAICHUNGTU, u.NGAYCT, u.MAKHACHHANG, u.UNITCODE, 0 AS TIENTHU, u.THANHTIEN AS TIENBAN FROM V_VTCT_CONGNO u WHERE u.LOAICHUNGTU =''XBAN''
                AND u.UNITCODE = '''||I_UNITCODE||''' AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') 
         UNION ALL 
                SELECT u.MACHUNGTU, u.LOAICHUNGTU, u.NGAYCT, u.MAKHACHHANG, u.UNITCODE, u.THANHTIEN AS TIENTHU, 0 AS TIENBAN FROM V_VTCT_CONGNO u WHERE u.LOAICHUNGTU =''CNKH''
                AND u.UNITCODE = '''||I_UNITCODE||''' AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')';
        OPEN SUB_CUR FOR SUB_QUERY_STR;
        LOOP
             FETCH SUB_CUR INTO C_MACHUNGTU, C_LOAICHUNGTU, C_NGAYCT, C_MAKHACHHANG, C_UNITCODE, C_PAYNOW, C_BORROW_NOW;
             EXIT WHEN SUB_CUR%NOTFOUND;
             I_AMMOUNT := I_AMMOUNT + C_BORROW_NOW - C_PAYNOW ;
             I_STT := I_STT +1;
             EXECUTE IMMEDIATE 'INSERT INTO TEMP_CONGNO(STT, UNITCODE, MAKHACHHANG, NGAYCT, MACHUNGTU, LOAICHUNGTU, TIENTHU, TIENBAN, TIENNO) 
                            VALUES ('||I_STT||','''||C_UNITCODE||''', '''||C_MAKHACHHANG||''',TO_DATE('''||C_NGAYCT||''',''DD/MM/YY''),'''||C_MACHUNGTU||''','''||C_LOAICHUNGTU||''',TO_NUMBER('''||C_PAYNOW||'''),TO_NUMBER('''||C_BORROW_NOW||'''),TO_NUMBER('''||I_AMMOUNT||'''))';
        END LOOP;
        CLOSE SUB_CUR;
    END LOOP;
    CLOSE CN_CUR;
 BEGIN
 -- RESULT...
QUERY_STR:= 'SELECT T.UNITCODE, T.MAKHACHHANG, KH.TENKH, T.NGAYCT, T.MACHUNGTU, T.TIENTHU, T.TIENBAN, T.TIENNO FROM TEMP_CONGNO T INNER JOIN DM_KHACHHANG KH ON T.MAKHACHHANG = KH.MAKH AND SUBSTR(T.UNITCODE,0,3) = SUBSTR(KH.UNITCODE,0,3) ORDER BY STT';
OPEN CUR FOR QUERY_STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (QUERY_STR || SQLERRM);  
END;
END BAOCAO_CNKH_CHITIET;