create or replace PROCEDURE            "BAOCAO_CNNCC_TONGHOP" (P_UNITCODE IN VARCHAR2, P_MANHACUNGCAP IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,  cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';

BEGIN

IF TRIM(P_MANHACUNGCAP) IS NOT NULL THEN
    P_EXPRESSION := P_EXPRESSION || 'AND u.MANHACUNGCAP IN ('||P_MANHACUNGCAP||')';
END IF;
QUERY_STR:='
 SELECT X.MANHACUNGCAP, X.UNITCODE, Y.TENNCC , SUM(X.BORROW_BEFORE) - SUM(X.PAY_BEFORE) AS NO_DAUKY, SUM(X.PAY_NOW) AS TRA_TRONGKY, SUM(X.BORROW_NOW) AS NO_TRONGKY, SUM(X.BORROW_NOW) - SUM(X.PAY_NOW) + SUM(X.BORROW_BEFORE) - SUM(X.PAY_BEFORE) AS NO_CUOIKY FROM(
     SELECT (CASE
      WHEN A.MANHACUNGCAP IS NOT NULL THEN A.MANHACUNGCAP 
      WHEN B.MANHACUNGCAP IS NOT NULL THEN B.MANHACUNGCAP 
      WHEN C.MANHACUNGCAP IS NOT NULL THEN C.MANHACUNGCAP 
      WHEN D.MANHACUNGCAP IS NOT NULL THEN D.MANHACUNGCAP END) AS MANHACUNGCAP,
      (CASE
      WHEN A.UNITCODE IS NOT NULL THEN A.UNITCODE 
      WHEN B.UNITCODE IS NOT NULL THEN B.UNITCODE 
      WHEN C.UNITCODE IS NOT NULL THEN C.UNITCODE 
      WHEN D.UNITCODE IS NOT NULL THEN D.UNITCODE END) AS UNITCODE,
     NVL(A.THANHTIEN,0) AS PAY_BEFORE, NVL(B.THANHTIEN,0) AS BORROW_BEFORE, NVL(C.THANHTIEN,0) AS PAY_NOW, NVL(D.THANHTIEN,0) AS BORROW_NOW 
     FROM 
         (SELECT u.MANHACUNGCAP, u.UNITCODE, SUM(NVL(u.THANHTIEN,0)) AS THANHTIEN FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNNCC'' AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') '||P_EXPRESSION||'
         GROUP BY u.MANHACUNGCAP, u.UNITCODE ) A
         FULL JOIN 
         (SELECT u.MANHACUNGCAP, u.UNITCODE, SUM(u.THANHTIEN) AS THANHTIEN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''NMUA'' AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND  u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') '||P_EXPRESSION||'
         GROUP BY u.MANHACUNGCAP, u.UNITCODE) B ON A.MANHACUNGCAP = B.MANHACUNGCAP AND A.UNITCODE = B.UNITCODE
         FULL JOIN  
         (SELECT u.MANHACUNGCAP, u.UNITCODE, SUM(u.THANHTIEN) AS THANHTIEN FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNNCC'' AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') '||P_EXPRESSION||'
         GROUP BY u.MANHACUNGCAP, u.UNITCODE) C ON A.MANHACUNGCAP = C.MANHACUNGCAP AND A.UNITCODE = C.UNITCODE
         FULL JOIN 
         (SELECT u.MANHACUNGCAP, u.UNITCODE, SUM(u.THANHTIEN) AS THANHTIEN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''NMUA'' AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') '||P_EXPRESSION||'
         GROUP BY u.MANHACUNGCAP, u.UNITCODE) D ON A.MANHACUNGCAP = D.MANHACUNGCAP AND A.UNITCODE = D.UNITCODE
     ) X      
     LEFT JOIN DM_NHACUNGCAP Y ON X.MANHACUNGCAP = Y.MANCC AND SUBSTR(X.UNITCODE,0,3)= SUBSTR(Y.UNITCODE,0,3)
     GROUP BY X.MANHACUNGCAP, X.UNITCODE, Y.TENNCC
     ORDER BY X.MANHACUNGCAP';
 BEGIN
--DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (QUERY_STR || SQLERRM);  
END;
END BAOCAO_CNNCC_TONGHOP;
 