create or replace PROCEDURE            "BAOCAO_CNKH_TONGHOP" (P_UNITCODE IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,  cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
SUB_QUERY_STR VARCHAR(32767);
P_EXPRESSION VARCHAR(32767):= '';
INSERT_STR VARCHAR(32767);
SUB_INSERT_STR VARCHAR(32767);
CREATE_TABLE VARCHAR(32767);
CHECK_EXIST_TABLE NUMBER;
CN_CUR SYS_REFCURSOR;
SUB_CUR SYS_REFCURSOR;
I_MAKHACHHANG VARCHAR(20);
I_UNITCODE VARCHAR(20);
I_AMMOUNT NUMBER(18,2) :=0;
I_PAYBEFORE NUMBER(18,2) :=0;
I_BORROWBEFORE NUMBER(18,2) :=0;
I_PAYNOW NUMBER(18,2);
I_BORROWNOW NUMBER(18,2);
BEGIN
--QUERY FOR KILL SESSION

 --SELECT INST_ID,SID,SERIAL# FROM gv$session WHERE SID = (SELECT SID FROM v$lock WHERE TYPE = 'TO' AND ID1
 --= (SELECT OBJECT_ID FROM DBA_OBJECTS WHERE OBJECT_NAME = 'TEMP_CONGNO'));
 --ALTER SYSTEM KILL SESSION 'sid,serial#,@inst_id';

    --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TEMP_CONGNO" 
   (	
   "STT" NUMBER(18,2) DEFAULT 0,
   "UNITCODE" NVARCHAR2(20), 
	"MAKHACHHANG" NVARCHAR2(20), 
	"MANHACUNGCAP" NVARCHAR2(20), 
	"NGAYCT" DATE, 
	"MACHUNGTU" NVARCHAR2(50), 
    "LOAICHUNGTU" NVARCHAR2(20),
	"TIENTHU" NUMBER(18,2) DEFAULT 0, 
	"TIENBAN" NUMBER(18,2) DEFAULT 0, 
	"TIENNO" NUMBER(18,2) DEFAULT 0
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''TEMP_CONGNO''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM TEMP_CONGNO';
   --BEGIN...
    IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
        P_EXPRESSION := P_EXPRESSION || 'AND u.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
    END IF;

    --GET ALL MAKHACHHANG, UNITCODE
    QUERY_STR := 'SELECT DISTINCT u.MAKHACHHANG, u.UNITCODE FROM V_VTCT_CONGNO u WHERE u.UNITCODE IS NOT NULL AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.MAKHACHHANG IS NOT NULL AND u.LOAICHUNGTU IN (''CNKH'',''XBAN'') '||P_EXPRESSION||' ORDER BY u.MAKHACHHANG';
    OPEN CN_CUR FOR QUERY_STR;
    LOOP
         FETCH CN_CUR INTO I_MAKHACHHANG, I_UNITCODE;
         EXIT WHEN CN_CUR%NOTFOUND;    
         --CALCULATE 'TONDAUKY' FOR 'I_AMMOUNT'
         I_PAYBEFORE :=0; I_BORROWBEFORE :=0; I_PAYNOW :=0; I_BORROWNOW :=0;

         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGTHU FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNKH'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_PAYBEFORE;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGBAN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''XBAN'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_BORROWBEFORE;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGTHU FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNKH'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')  AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_PAYNOW;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGBAN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''XBAN'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND u.MAKHACHHANG = '''||I_MAKHACHHANG||''' ' INTO I_BORROWNOW;
         --INSERT MAKHACHHANG,UNITCODE 'TONDAUKY'
         I_AMMOUNT := NVL(I_BORROWBEFORE,0) - NVL(I_PAYBEFORE,0) + NVL(I_BORROWNOW,0) - NVL(I_PAYNOW,0);
         INSERT_STR:= 'INSERT INTO TEMP_CONGNO (UNITCODE, MAKHACHHANG,  TIENTHU, TIENBAN, TIENNO) VALUES ('''||I_UNITCODE||''', '''||I_MAKHACHHANG||''', TO_NUMBER('''||I_PAYNOW||'''), TO_NUMBER('''||I_BORROWNOW||'''), TO_NUMBER('''||I_AMMOUNT||'''))';
         EXECUTE IMMEDIATE INSERT_STR;

    END LOOP;
    CLOSE CN_CUR;
 BEGIN
 -- RESULT...
QUERY_STR:= 'SELECT T.UNITCODE, T.MAKHACHHANG, KH.TENKH AS TENKHACHHANG, T.TIENNO +  T.TIENTHU - T.TIENBAN AS NO_DAUKY, T.TIENTHU AS TRA_TRONGKY , T.TIENBAN  AS NO_TRONGKY, T.TIENNO AS NO_CUOIKY FROM TEMP_CONGNO T LEFT JOIN DM_KHACHHANG KH ON T.MAKHACHHANG = KH.MAKH AND SUBSTR(T.UNITCODE,0,3) = SUBSTR(KH.UNITCODE,0,3) ORDER BY STT';
OPEN CUR FOR QUERY_STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (QUERY_STR || SQLERRM);
END;
END BAOCAO_CNKH_TONGHOP;
 