create or replace PROCEDURE THONGKE_DOANHTHU_LOAIHANG 
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_DENNGAY IN DATE 
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
BEGIN
    QUERY_STR :='SELECT MAVATTU, TENVATTU, THANHTIEN FROM 
    (SELECT VT.MALOAIVATTU AS MAVATTU, LVT.TENLOAIVT AS TENVATTU, SUM( CASE WHEN P.LOAIGIAODICH = 1 THEN NVL(C.TTIENCOVAT,0) ELSE (-1 * NVL(C.TTIENCOVAT,0)) END) AS THANHTIEN
    , RANK() OVER(ORDER BY SUM(C.TTIENCOVAT) DESC) AS RNK FROM NVGDQUAY_ASYNCCLIENT P
        INNER JOIN NVHANGGDQUAY_ASYNCCLIENT C ON P.MAGIAODICHQUAYPK = C.MAGDQUAYPK
        INNER JOIN DM_VATTU VT ON C.MAVATTU = VT.MAVATTU AND C.MADONVI = VT.UNITCODE
        INNER JOIN DM_LOAIVATTU LVT ON VT.MALOAIVATTU = LVT.MALOAIVATTU AND C.MADONVI = LVT.UNITCODE
        WHERE P.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
            AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') 
        GROUP BY VT.MALOAIVATTU, LVT.TENLOAIVT) A WHERE RNK <=10';
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END THONGKE_DOANHTHU_LOAIHANG;
/
create or replace PROCEDURE THONGKE_DOANHTHU_NHOMHANG 
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_DENNGAY IN DATE 
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
BEGIN
    QUERY_STR :='SELECT MAVATTU, TENVATTU, THANHTIEN FROM 
    (SELECT VT.MANHOMVATTU AS MAVATTU, NVT.TENNHOMVT AS TENVATTU, SUM( CASE WHEN P.LOAIGIAODICH = 1 THEN NVL(C.TTIENCOVAT,0) ELSE (-1 * NVL(C.TTIENCOVAT,0)) END) AS THANHTIEN
    , RANK() OVER(ORDER BY SUM(C.TTIENCOVAT) DESC) AS RNK FROM NVGDQUAY_ASYNCCLIENT P
        INNER JOIN NVHANGGDQUAY_ASYNCCLIENT C ON P.MAGIAODICHQUAYPK = C.MAGDQUAYPK
        INNER JOIN DM_VATTU VT ON C.MAVATTU = VT.MAVATTU AND C.MADONVI = VT.UNITCODE
        INNER JOIN DM_NHOMVATTU NVT ON VT.MANHOMVATTU = NVT.MANHOMVTU AND C.MADONVI = NVT.UNITCODE
        WHERE P.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
            AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') 
        GROUP BY VT.MANHOMVATTU, NVT.TENNHOMVT) A WHERE RNK <=10';
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END THONGKE_DOANHTHU_NHOMHANG;
/
create or replace PROCEDURE THONGKE_KIEMTRATONHANG
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_MAVATTU IN VARCHAR2
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
P_KY NUMBER(4,0);
P_NAM NUMBER(4,0);
BEGIN
    SELECT KY, NAM INTO P_KY,P_NAM FROM DM_KYKETOAN WHERE TUNGAY = TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE=P_UNITCODE;
    QUERY_STR :='SELECT XNT.MAVATTU, VT.TENVATTU, XNT.TONCUOIKYSL AS SOLUONG,XNT.MAKHO, K.TENKHO ,XNT.UNITCODE FROM XNT_'||P_NAM||'_KY_'||P_KY||' XNT 
            INNER JOIN DM_VATTU VT ON XNT.UNITCODE = VT.UNITCODE AND XNT.MAVATTU = VT.MAVATTU
            INNER JOIN DM_KHO K ON XNT.MAKHO = K.MAKHO AND XNT.UNITCODE = K.UNITCODE
            WHERE XNT.UNITCODE = '''||P_UNITCODE||''' AND XNT.MAVATTU = '''||P_MAVATTU||''' ';
        DBMS_OUTPUT.PUT_LINE(QUERY_STR);
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END THONGKE_KIEMTRATONHANG;
/
create or replace PROCEDURE THONGKE_NMUA_XBAN 
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_DENNGAY IN DATE 
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
SUB_QUERY VARCHAR2(32767);
CREATE_TABLE VARCHAR2(32767);
INSERT_STR VARCHAR2(32767);
AMMOUNT NUMBER(18,2) := 0;
CHECK_EXIST_TABLE NUMBER;
BEGIN
    --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TEMP_THONGKE" 
   (	
    "UNITCODE" NVARCHAR2(20), 
    "LOAINHAPXUAT" NVARCHAR2(2), 
	"LOAICHUNGTU" NVARCHAR2(20), 
	"TENCHUNGTU" NVARCHAR2(50), 
    "NGAYCHUNGTU" DATE, 
	"SOTIEN" NUMBER(18,2) DEFAULT 0 
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''TEMP_THONGKE''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM TEMP_THONGKE';
    -- LOAINHAPXUAT: NHAP - 1, XUAT - 2  
    --NMUA:
    SUB_QUERY := 'SELECT UNITCODE,''1'' AS LOAINHAPXUAT,LOAICHUNGTU,''Nhập mua'' AS TENCHUNGTU, NGAYDUYETPHIEU AS NGAYCHUNGTU, SUM(NVL(THANHTIENSAUVAT,0)) AS SOTIEN FROM VATTUCHUNGTU WHERE UNITCODE = '''||P_UNITCODE||''' 
    AND LOAICHUNGTU = ''NMUA'' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND TRANGTHAI = 10
                 GROUP BY UNITCODE, LOAICHUNGTU,NGAYDUYETPHIEU';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;
    --DCN:
    SUB_QUERY := 'SELECT UNITCODE,''1'' AS LOAINHAPXUAT,LOAICHUNGTU,''Điều chuyển nhận'' AS TENCHUNGTU, NGAYDUYETPHIEU AS NGAYCHUNGTU, SUM(NVL(THANHTIENSAUVAT,0)) AS SOTIEN FROM VATTUCHUNGTU WHERE UNITCODE = '''||P_UNITCODE||''' 
    AND LOAICHUNGTU = ''DCN'' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND TRANGTHAI = 10
                  GROUP BY UNITCODE, LOAICHUNGTU,NGAYDUYETPHIEU';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;
    --NHBANTL:
    SUB_QUERY := 'SELECT UNITCODE,''1'' AS LOAINHAPXUAT,LOAICHUNGTU,''Nhập Bán buôn trả lại'' AS TENCHUNGTU, NGAYDUYETPHIEU AS NGAYCHUNGTU, SUM(NVL(THANHTIENSAUVAT,0)) AS SOTIEN FROM VATTUCHUNGTU WHERE UNITCODE = '''||P_UNITCODE||''' 
    AND LOAICHUNGTU = ''NHBANTL'' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND TRANGTHAI = 10
                  GROUP BY UNITCODE, LOAICHUNGTU,NGAYDUYETPHIEU';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;        
    -- NHẬP BÁN LẺ TRẢ LẠI:
    SUB_QUERY := 'SELECT MADONVI AS UNITCODE,''1'' AS LOAINHAPXUAT,''NBLETL'' AS LOAICHUNGTU,''Nhập Bán lẻ trả lại'' AS TENCHUNGTU, NGAYPHATSINH AS NGAYCHUNGTU, SUM(NVL(TTIENCOVAT,0)) AS SOTIEN FROM NVGDQUAY_ASYNCCLIENT 
    WHERE MADONVI = '''||P_UNITCODE||''' AND LOAIGIAODICH = 2 AND TO_DATE(NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')  AND TO_DATE(NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
                    GROUP BY MADONVI, NGAYPHATSINH';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;  
    -- XBANLE:
    SUB_QUERY := 'SELECT MADONVI AS UNITCODE,''2'' AS LOAINHAPXUAT,''XBANLE'' AS LOAICHUNGTU,''Xuất Bán lẻ'' AS TENCHUNGTU, NGAYPHATSINH AS NGAYCHUNGTU, SUM(NVL(TTIENCOVAT,0)) AS SOTIEN FROM NVGDQUAY_ASYNCCLIENT 
    WHERE MADONVI = '''||P_UNITCODE||''' AND LOAIGIAODICH = 1 AND TO_DATE(NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')  AND TO_DATE(NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
                    GROUP BY MADONVI, NGAYPHATSINH';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;  
    -- XBAN
    SUB_QUERY := 'SELECT UNITCODE,''2'' AS LOAINHAPXUAT,LOAICHUNGTU,''Xuất bán buôn'' AS TENCHUNGTU, NGAYDUYETPHIEU AS NGAYCHUNGTU, SUM(NVL(THANHTIENSAUVAT,0)) AS SOTIEN FROM VATTUCHUNGTU WHERE UNITCODE = '''||P_UNITCODE||''' 
    AND LOAICHUNGTU = ''XBAN'' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND TRANGTHAI = 10
                  GROUP BY UNITCODE, LOAICHUNGTU,NGAYDUYETPHIEU';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;  
    -- DCX
    SUB_QUERY := 'SELECT UNITCODE,''2'' AS LOAINHAPXUAT,LOAICHUNGTU,''Điều chuyển xuất'' AS TENCHUNGTU, NGAYDUYETPHIEU AS NGAYCHUNGTU, SUM(NVL(THANHTIENSAUVAT,0)) AS SOTIEN FROM VATTUCHUNGTU WHERE UNITCODE = '''||P_UNITCODE||''' 
    AND LOAICHUNGTU = ''DCX'' AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND TO_DATE(NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND TRANGTHAI = 10
                  GROUP BY UNITCODE, LOAICHUNGTU,NGAYDUYETPHIEU';
    INSERT_STR:= 'INSERT INTO TEMP_THONGKE (UNITCODE, LOAINHAPXUAT, LOAICHUNGTU, TENCHUNGTU, NGAYCHUNGTU, SOTIEN) '||SUB_QUERY||'';
    EXECUTE IMMEDIATE INSERT_STR;  

    QUERY_STR :='SELECT * FROM TEMP_THONGKE ORDER BY NGAYCHUNGTU DESC';
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END THONGKE_NMUA_XBAN;
/
create or replace PROCEDURE THONGKE_VATTU_BANCHAM
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_DENNGAY IN DATE
, P_SOLUONG IN NUMBER
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
P_KY NUMBER(4,0);
P_NAM NUMBER(4,0);
BEGIN
    SELECT KY, NAM INTO P_KY,P_NAM FROM DM_KYKETOAN WHERE TUNGAY = TO_DATE(P_TUNGAY,'DD/MM/YY') AND UNITCODE=P_UNITCODE;
    QUERY_STR :='SELECT MAVATTU, TENVATTU, SOLUONG FROM (SELECT VT.MAVATTU, VT.TENVATTU AS TENVATTU, SUM(C.SOLUONG) AS SOLUONG, RANK() OVER(ORDER BY SUM(C.SOLUONG) ASC) AS RNK 
        FROM NVGDQUAY_ASYNCCLIENT P
        INNER JOIN NVHANGGDQUAY_ASYNCCLIENT C ON P.MAGIAODICHQUAYPK = C.MAGDQUAYPK
        RIGHT JOIN DM_VATTU VT ON P.MADONVI = VT.UNITCODE AND C.MAVATTU = VT.MAVATTU
        INNER JOIN XNT_'||P_NAM||'_KY_'||P_KY||' XNT ON P.MADONVI = XNT.UNITCODE AND C.MAVATTU = XNT.MAVATTU AND XNT.MAKHO = '''||P_UNITCODE||'-K2''
        WHERE P.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
            AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND P.LOAIGIAODICH = 1 AND C.SOLUONG < '||P_SOLUONG||' AND XNT.TONCUOIKYSL >0
        GROUP BY VT.MAVATTU, VT.TENVATTU) A WHERE ROWNUM < 20';
        DBMS_OUTPUT.PUT_LINE(QUERY_STR);
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END THONGKE_VATTU_BANCHAM;
/

 create or replace PROCEDURE THONGKE_VATTU_BANCHAY 
(
  P_UNITCODE IN VARCHAR2 
, P_TUNGAY IN DATE 
, P_DENNGAY IN DATE 
, CUR  OUT SYS_REFCURSOR
) AS 
QUERY_STR VARCHAR2(32767);
BEGIN
    QUERY_STR :='SELECT MAVATTU, TENVATTU, THANHTIEN FROM (SELECT C.MAVATTU, C.TENDAYDU AS TENVATTU, SUM(C.TTIENCOVAT) AS THANHTIEN, RANK() OVER(ORDER BY SUM(C.TTIENCOVAT) DESC) AS RNK FROM NVGDQUAY_ASYNCCLIENT P
        INNER JOIN NVHANGGDQUAY_ASYNCCLIENT C ON P.MAGIAODICHQUAYPK = C.MAGDQUAYPK
        WHERE P.MADONVI = '''||P_UNITCODE||''' AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') 
            AND TO_DATE(P.NGAYPHATSINH,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'') AND P.LOAIGIAODICH = 1 
        GROUP BY C.MAVATTU, C.TENDAYDU) A WHERE RNK <=5';
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
        WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);
      
END THONGKE_VATTU_BANCHAY;

 /