create or replace package THUNGAN is

  -- Author  : ADMINISTRATOR
  -- Created : 14/12/2016 11:07:47 PM
  -- Purpose : Bao cao cho thu ngan
  PROCEDURE BC_TONGTIEN_GIAODICH_QUAY(P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_UNITCODE IN VARCHAR2, P_RESULT_CUSOR OUT SYS_REFCURSOR);

end THUNGAN;
create or replace package body THUNGAN is
PROCEDURE BC_TONGTIEN_GIAODICH_QUAY(P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_UNITCODE in VARCHAR2, P_RESULT_CUSOR OUT SYS_REFCURSOR) IS
  BEGIN
  OPEN P_RESULT_CUSOR FOR SELECT NGUOITAO, MAMAYBAN, SUM(TONGBAN) AS TONGBAN, SUM(TONGTRA) AS TONGTRA, (SUM(TONGBAN) - SUM(TONGTRA)) AS THUCTHU 
  FROM (
  SELECT NGUOITAO, MAMAYBAN,SUM(SOLUONG*DONGIA) AS TONGBAN, 0 AS TONGTRA
  FROM VIEW_VATTUGD_XNT WHERE NGAYCHUNGTU BETWEEN  TO_DATE(P_TUNGAY,'DD/MM/YY') AND TO_DATE(P_DENNGAY,'DD/MM/YY') AND LOAICHUNGTU='XBAN' AND TRANGTHAI = 10 AND UNITCODE = P_UNITCODE
  GROUP BY NGUOITAO, MAMAYBAN
  UNION ALL
  SELECT NGUOITAO, MAMAYBAN,0 AS TONGBAN, SUM(SOLUONG*DONGIA) AS TONGTRA
  FROM VIEW_VATTUGD_XNT WHERE NGAYCHUNGTU BETWEEN  TO_DATE(P_TUNGAY,'DD/MM/YY') AND TO_DATE(P_DENNGAY,'DD/MM/YY') AND LOAICHUNGTU='NHBANTL' AND TRANGTHAI = 10 AND UNITCODE = P_UNITCODE
  GROUP BY NGUOITAO, MAMAYBAN) GROUP BY NGUOITAO, MAMAYBAN;
  END;
end THUNGAN;
