create or replace PROCEDURE            "BAOCAO_XKHAC_TONGHOP" (P_GROUPBY IN VARCHAR2,P_PTHUCXUAT IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_TAX||')';
END IF;  
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MA AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MADONVINHAN, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MADONVI AS Ma, c.TENDONVI AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MADONVINHAN AS MA,t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.MA = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.VAT, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAITHUE AS Ma, c.LOAITHUE AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.VAT AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' LEFT JOIN DM_LOAITHUE c ON a.MA = c.MALOAITHUE';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHOXUAT, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten,a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.MA = c.MAKHO AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.MA = c.MANHOMVTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.MA = c.MALOAIVATTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.MA = c.MANCC AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MAKH AS Ma, c.TENKH AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHACHHANG AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHACHHANG c ON a.MA = c.MAKH AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.USERNAME AS Ma, c.TENNHANVIEN AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.I_CREATE_BY AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON a.MA = c.USERNAME AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.MA AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA , t.UNITCODE ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU, t.UNITCODE ';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN, t.UNITCODE ';
P_TABLE_GROUPBY:= '  ';
END;
END IF;

QUERY_STR := 'select (a.SOLUONGBAN) as SOLUONGBAN,(a.VON) as VON,(a.TIENTHUE) AS TIENTHUE,(a.DOANHTHU) AS DOANHTHU,(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, (a.TIENCHIETKHAU) AS TIENCHIETKHAU,(a.DOANHTHU + a.TIENTHUE - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.DONGIA,0)) AS VON
                          ,ROUND(SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END),2) as TIENCHIETKHAU
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0)) as DOANHTHU 
                          ,SUM(NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0) * (NVL(g.TYGIA,0)/100)) as TIENTHUE
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XKHAC'' AND t.MALYDOKHAC = '''||P_PTHUCXUAT||'''
INNER JOIN V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND b.MADONVI= t.UNITCODE
LEFT JOIN DM_LOAITHUE g on g.MALOAITHUE = ct.VAT
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE ''%'||P_UNITCODE||'%''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	group by  '||P_COLUMNS_GROUPBY||') a
 '||P_TABLE_GROUPBY;
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_XKHAC_TONGHOP;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_XKHAC_TONGHOP
--------------------------------------------------------