--ANH PT 
--CREATE TABLE TEMP   
  CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TMP_REPORT_CUSTOMER" 
   (	"NGAYPHATSINH" DATE, 
	"MAGIAODICHQUAYPK" NVARCHAR2(50), 
	"TENKHACHHANG" NVARCHAR2(50), 
	"MAVATTU" NVARCHAR2(50), 
	"SOLUONG" NUMBER(17,4) DEFAULT 0, 
	"DONGIA" NUMBER(17,4) DEFAULT 0, 
	"THANHTIEN" NUMBER(17,4) DEFAULT 0, 
	"CHIETKHAU" NUMBER(17,4) DEFAULT 0, 
	"DIENTHOAI" NVARCHAR2(50), 
	"MAKHO" NVARCHAR2(50)
   ) ON COMMIT DELETE ROWS ;
 /
   -- END
create or replace PACKAGE CUSTOMERCARE AS 
--Author: HUYNQ
--Modified Date: 09/09/2017 19:00
PROCEDURE REPORT_LOYAL_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER, P_MATHE IN VARCHAR2,P_DIACHI IN VARCHAR2, XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE CUSTOMER_LEVELUP(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE REPORT_CUSTOMER_LEVELUP(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE NOTBUY_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE REPORT_NOTBUY_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR);
PROCEDURE REPORT_BUY_ONETIME(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_WAREHOUSECODES IN VARCHAR2, CUR_BUY_ONETIME OUT SYS_REFCURSOR);
PROCEDURE REPORT_BUY_CUSTOMER_NEW(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_WAREHOUSECODES IN VARCHAR2, CUR_BUY_CUSTOMER_NEW OUT SYS_REFCURSOR);
PROCEDURE REPORT_BUY_DETAILS_NEW(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_WAREHOUSECODES IN VARCHAR2, P_MADONVI IN NVARCHAR2,CUR_BUY_DETAILS_NEW OUT SYS_REFCURSOR);
END CUSTOMERCARE;
/
create or replace PACKAGE BODY CUSTOMERCARE AS 
--Author: HUYNQ
--Modified Date: 09/09/2017 19:00
--Description: Thêm Procedure:NOTBUY CUSTOMER
PROCEDURE REPORT_LOYAL_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER, P_MATHE IN VARCHAR2,P_DIACHI IN VARCHAR2, XTNCOLLECTION OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';

           IF TRIM(P_MATHE) IS NOT NULL THEN
           DK_WHERE := DK_WHERE ||' AND MATHE = '''||P_MATHE||'';
           END IF;

           IF TRIM(P_DIACHI) IS NOT NULL THEN
           DK_WHERE := DK_WHERE || ' AND DIACHI LIKE ''%'||P_DIACHI||'%''';
           END IF;
            IF TRIM(P_STATETYPEMONEY) IS NOT NULL  AND P_STATETYPEMONEY = 2 THEN     
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA < '||P_TOMONEY||'';
                    END IF;
                END;
            ELSE
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN < '||P_TOMONEY||'';
                    END IF;
                END;
            END IF;

           QUERY_STR:= 'SELECT * FROM DMKHACHHANG WHERE  UNITCODE LIKE '''||P_UNITCODE||'''
                        AND I_CREATE_DATE >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                        AND I_CREATE_DATE <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')
                        '||DK_WHERE||'';
       BEGIN
            DBMS_OUTPUT.PUT_LINE(QUERY_STR);
            OPEN XTNCOLLECTION FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_LOYAL_CUSTOMER;
PROCEDURE CUSTOMER_LEVELUP(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';
            IF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 1 THEN     
                DK_WHERE := DK_WHERE || ' AND (ISCARE = 0 OR ISCARE IS NULL)';
            ELSIF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 2 THEN     
                DK_WHERE := DK_WHERE || ' AND ISCARE = 1';
            END IF;
            IF TRIM(P_STATETYPEMONEY) IS NOT NULL  AND P_STATETYPEMONEY = 1 THEN     
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA < '||P_TOMONEY||'';
                    END IF;
                END;
            ELSE
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN < '||P_TOMONEY||'';
                    END IF;
                END;
            END IF;

           QUERY_STR:= 'SELECT * FROM DMKHACHHANG WHERE  UNITCODE LIKE ''%'||P_UNITCODE||'%''
                        AND I_CREATE_DATE >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                        AND I_CREATE_DATE <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')
                        '||DK_WHERE||'
                        ORDER BY TONGTIEN DESC
                        ';
       BEGIN
            DBMS_OUTPUT.PUT_LINE(QUERY_STR);
            OPEN XTNCOLLECTION FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END CUSTOMER_LEVELUP;
PROCEDURE REPORT_CUSTOMER_LEVELUP(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';
            IF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 1 THEN     
                DK_WHERE := DK_WHERE || ' AND (ISCARE = 0 OR ISCARE IS NULL)';
            ELSIF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 2 THEN     
                DK_WHERE := DK_WHERE || ' AND ISCARE = 1';
            END IF;

            IF TRIM(P_STATETYPEMONEY) IS NOT NULL  AND P_STATETYPEMONEY = 1 THEN     
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA < '||P_TOMONEY||'';
                    END IF;
                END;
            ELSE
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN < '||P_TOMONEY||'';
                    END IF;
                END;
            END IF;

           QUERY_STR:= 'SELECT * FROM DMKHACHHANG WHERE  UNITCODE LIKE ''%'||P_UNITCODE||'%''
                        AND NGAYCHAMSOC >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                        AND NGAYCHAMSOC <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')
                        '||DK_WHERE||'
                        ORDER BY NGAYCHAMSOC DESC
                        ';
       BEGIN
            DBMS_OUTPUT.PUT_LINE(QUERY_STR);
            OPEN XTNCOLLECTION FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_CUSTOMER_LEVELUP;
PROCEDURE NOTBUY_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';
            IF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 1 THEN     
                DK_WHERE := DK_WHERE || ' AND (ISCARE = 0 OR ISCARE IS NULL)';
            ELSIF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 2 THEN     
                DK_WHERE := DK_WHERE || ' AND ISCARE = 1';
            END IF;
            IF TRIM(P_STATETYPEMONEY) IS NOT NULL  AND P_STATETYPEMONEY = 1 THEN     
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA < '||P_TOMONEY||'';
                    END IF;
                END;
            ELSE
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN < '||P_TOMONEY||'';
                    END IF;
                END;
            END IF;

           QUERY_STR:= 'SELECT * FROM DMKHACHHANG WHERE  UNITCODE LIKE ''%'||P_UNITCODE||'%''
                        AND (NGAYMUAHANG < TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                        OR NGAYMUAHANG >= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY''))
                        '||DK_WHERE||'
                        ORDER BY TONGTIEN DESC
                        ';
       BEGIN
            DBMS_OUTPUT.PUT_LINE(QUERY_STR);
            OPEN XTNCOLLECTION FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END NOTBUY_CUSTOMER;
PROCEDURE REPORT_NOTBUY_CUSTOMER(P_UNITCODE IN NVARCHAR2,P_WAREHOUSECODES IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_STATETYPEMONEY IN NUMBER, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_STATECUSTOMERCARE IN NUMBER, XTNCOLLECTION OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';
            IF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 1 THEN     
                DK_WHERE := DK_WHERE || ' AND (ISCARE = 0 OR ISCARE IS NULL)';
            ELSIF TRIM(P_STATECUSTOMERCARE) IS NOT NULL  AND TRIM(P_STATECUSTOMERCARE) = 2 THEN     
                DK_WHERE := DK_WHERE || ' AND ISCARE = 1';
            END IF;

            IF TRIM(P_STATETYPEMONEY) IS NOT NULL  AND P_STATETYPEMONEY = 1 THEN     
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TIENNGUYENGIA < '||P_TOMONEY||'';
                    END IF;
                END;
            ELSE
                BEGIN
                    IF TRIM(P_FROMMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN >= '||P_FROMMONEY||'';
                    END IF;
                    IF TRIM(P_TOMONEY) IS NOT NULL THEN
                        DK_WHERE := DK_WHERE || ' AND TONGTIEN < '||P_TOMONEY||'';
                    END IF;
                END;
            END IF;

           QUERY_STR:= 'SELECT * FROM DMKHACHHANG WHERE  UNITCODE LIKE ''%'||P_UNITCODE||'%''
                        AND (NGAYMUAHANG < TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                        OR NGAYMUAHANG >= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY''))
                        '||DK_WHERE||'
                        ORDER BY NGAYCHAMSOC DESC
                        ';
       BEGIN
            DBMS_OUTPUT.PUT_LINE(QUERY_STR);
            OPEN XTNCOLLECTION FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_NOTBUY_CUSTOMER;
  
  PROCEDURE REPORT_BUY_ONETIME(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_FROMMONEY IN NUMBER, P_TOMONEY IN NUMBER,P_WAREHOUSECODES IN VARCHAR2, CUR_BUY_ONETIME OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      QUERY_STR1  VARCHAR2(32767);
      QUERY_JOIN VARCHAR2(32767);
      QUERY_WHERE  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      EXCUTE_INSERT VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';          
            QUERY_WHERE := '';
            EXCUTE_INSERT := '';
          
            IF P_FROMMONEY IS NOT NULL THEN QUERY_WHERE := QUERY_WHERE || ' AND b.TTIENCOVAT > '||P_FROMMONEY||' ';
            END IF;
            IF P_TOMONEY IS NOT NULL THEN QUERY_WHERE := QUERY_WHERE || ' AND b.TTIENCOVAT < '||P_TOMONEY||' ';
            END IF;
            IF P_WAREHOUSECODES IS NOT NULL THEN QUERY_WHERE := QUERY_WHERE || ' AND b.MAKHOHANG IN ('||P_WAREHOUSECODES||' )';
            END IF;
            QUERY_STR := 'INSERT INTO TMP_REPORT_CUSTOMER(NGAYPHATSINH,MAGIAODICHQUAYPK,TENKHACHHANG,MAVATTU,SOLUONG,DONGIA,THANHTIEN,CHIETKHAU,DIENTHOAI,MAKHO) (
                SELECT a.NGAYPHATSINH,a.MAGIAODICHQUAYPK AS MAGIAODICHQUAYPK,c.TENKH AS TENKHACHHANG,b.MAVATTU,b.SOLUONG,b.GIABANLECOVAT AS DONGIA,
                                b.TTIENCOVAT AS THANHTIEN,b.TIENKHUYENMAI AS CHIETKHAU,c.DIENTHOAI,b.MAKHOHANG AS MAKHO
                                FROM NVGDQUAY_ASYNCCLIENT a 
                                INNER JOIN NVHANGGDQUAY_ASYNCCLIENT b
                                ON a.MAGIAODICHQUAYPK=b.MAGDQUAYPK INNER JOIN DMKHACHHANG c ON a.MAKHACHHANG = c.MAKH';
                                
            DECLARE
            CURSOR CUSTOMER IS SELECT a.MAKHACHHANG FROM NVGDQUAY_ASYNCCLIENT a WHERE TO_DATE(a.NGAYPHATSINH, 'DD/MM/YY') 
            BETWEEN TO_DATE(''||P_TUNGAY||'', 'DD/MM/YY') AND TO_DATE(''||P_DENNGAY||'', 'DD/MM/YY') AND a.MADONVI = ''||P_UNITCODE||'' GROUP BY a.MAKHACHHANG HAVING COUNT(a.MAKHACHHANG) = 1;
            BEGIN
                FOR CUS IN CUSTOMER LOOP
                    DBMS_OUTPUT.PUT_LINE(CUS.MAKHACHHANG);
                    BEGIN
                        QUERY_JOIN := '  AND a.MAKHACHHANG = ''' ||  CUS.MAKHACHHANG || ''' ';
                        QUERY_STR1 := QUERY_STR || QUERY_JOIN || ' WHERE 1=1 ' || QUERY_WHERE || ')';
                        DBMS_OUTPUT.PUT_LINE(QUERY_STR1);
                        EXECUTE IMMEDIATE QUERY_STR1;
                    END;
                END LOOP;
            END;
       BEGIN
            OPEN CUR_BUY_ONETIME FOR SELECT * FROM TMP_REPORT_CUSTOMER;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_BUY_ONETIME;
  
  PROCEDURE REPORT_BUY_CUSTOMER_NEW(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_WAREHOUSECODES IN VARCHAR2, CUR_BUY_CUSTOMER_NEW OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      QUERY_STR1  VARCHAR2(32767);
      QUERY_WHERE  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      EXCUTE_INSERT VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';          
            QUERY_WHERE := '';
            EXCUTE_INSERT := '';
            IF P_WAREHOUSECODES IS NOT NULL THEN DK_WHERE := DK_WHERE || ' AND a.MAKHOHANG IN ('||P_WAREHOUSECODES||' )';
            END IF;                    
            QUERY_STR := 'SELECT y.MADONVI,SUM(y.SOKHACH) AS SOKHACH,SUM(y.SOGIAODICH) AS SOGIAODICH,SUM(DOANHTHU) AS DOANHTHU,SUM(TRALAI) AS TRALAI,SUM(CHIETKHAU) AS CHIETKHAU,SUM(THUCTHU) AS THUCTHU FROM (
                        SELECT x.MADONVI,x.SOKHACH,x.SOGIAODICH,x.DOANHTHU,x.TRALAI,x.CHIETKHAU,(x.DOANHTHU+x.TRALAI-x.CHIETKHAU) AS THUCTHU FROM (
                        SELECT a.MADONVI,COUNT(a.MAKHACHHANG) AS SOKHACH,COUNT(a.MAGIAODICHQUAYPK) AS SOGIAODICH,
                        (SELECT NVL(SUM(NVL(c.TTIENCOVAT,0)),0) FROM NVGDQUAY_ASYNCCLIENT c WHERE c.LOAIGIAODICH = 1 AND TO_DATE(c.NGAYPHATSINH,''DD-MM-YY'') >  TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND TO_DATE(c.NGAYPHATSINH,''DD-MM-YY'') <  TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND c.MADONVI LIKE '''||P_UNITCODE||'%'') AS DOANHTHU,
                        (SELECT NVL(SUM(NVL(d.TTIENCOVAT,0)),0) FROM NVGDQUAY_ASYNCCLIENT d WHERE d.LOAIGIAODICH = 2 AND TO_DATE(d.NGAYPHATSINH,''DD-MM-YY'') >  TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND TO_DATE(d.NGAYPHATSINH,''DD-MM-YY'') <  TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND d.MADONVI LIKE '''||P_UNITCODE||'%'') AS TRALAI,
                        SUM(NVL(b.TIENKHUYENMAI,0)) + SUM(NVL(a.TIENVOUCHER,0)) AS CHIETKHAU
                        FROM NVGDQUAY_ASYNCCLIENT a INNER JOIN NVHANGGDQUAY_ASYNCCLIENT b ON a.MAGIAODICHQUAYPK = b.MAGDQUAYPK  AND TO_DATE(a.NGAYPHATSINH,''DD-MM-YY'') >  TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND TO_DATE(a.NGAYPHATSINH,''DD-MM-YY'') <  TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND a.MADONVI LIKE '''||P_UNITCODE||'%'' GROUP BY a.MADONVI,a.MAKHACHHANG,a.MAGIAODICHQUAYPK,b.MAGDQUAYPK
                         ) x GROUP BY x.MADONVI,x.SOKHACH,x.SOGIAODICH,x.DOANHTHU,x.TRALAI,x.CHIETKHAU
                    ) y
                    GROUP BY MADONVI';
            DECLARE
            
       BEGIN
        DBMS_OUTPUT.put_line (QUERY_STR); 
            OPEN CUR_BUY_CUSTOMER_NEW FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_BUY_CUSTOMER_NEW;
  
  PROCEDURE REPORT_BUY_DETAILS_NEW(P_UNITCODE IN NVARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_WAREHOUSECODES IN VARCHAR2, P_MADONVI IN NVARCHAR2,CUR_BUY_DETAILS_NEW OUT SYS_REFCURSOR)
IS
      QUERY_STR  VARCHAR2(32767);
      QUERY_STR1  VARCHAR2(32767);
      QUERY_WHERE  VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767) ;
      EXCUTE_INSERT VARCHAR2(32767) ;
      BEGIN
            DK_WHERE := '';
            QUERY_STR :='';          
            QUERY_WHERE := '';
            EXCUTE_INSERT := '';
            IF P_WAREHOUSECODES IS NOT NULL THEN DK_WHERE := DK_WHERE || ' AND a.MAKHOHANG IN ('||P_WAREHOUSECODES||' )';
            END IF;                    
            QUERY_STR := 'SELECT DISTINCT a.NGAYPHATSINH, a.MAKHACHHANG, b.TENKH , b.DIENTHOAI, b.NGAYSINH, b.NGAYDACBIET, b.EMAIL, b.MATHE, b.NGAYCAPTHE, b.NGAYHETHAN, a.MADONVI
                                FROM NVGDQUAY_ASYNCCLIENT a INNER JOIN DMKHACHHANG b ON a.MAKHACHHANG=b.MAKH AND b.UNITCODE LIKE SUBSTR('''||P_UNITCODE||''',0,3) || ''%''
                                WHERE TO_DATE(a.NGAYPHATSINH,''DD-MM-YY'') >  TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND TO_DATE(a.NGAYPHATSINH,''DD-MM-YY'') <  TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND
                                      TO_DATE(b.I_CREATE_DATE,''DD-MM-YY'') >  TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND TO_DATE(b.I_CREATE_DATE,''DD-MM-YY'') <  TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'') AND a.MADONVI = '''||P_MADONVI||'''';
            
            DECLARE
            
       BEGIN
        DBMS_OUTPUT.put_line (QUERY_STR); 
            OPEN CUR_BUY_DETAILS_NEW FOR QUERY_STR;
            EXCEPTION
                WHEN OTHERS
                  THEN
                        DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
       END;
  END REPORT_BUY_DETAILS_NEW;
  

END CUSTOMERCARE;
/