create or replace PROCEDURE            "BAOCAO_GIAODICHQUAY" (P_TUNGAY IN DATE, P_DENNGAY IN DATE,P_UNITCODE IN NVARCHAR2,P_MAMAYBAN IN VARCHAR2,P_NGUOIDUNG IN VARCHAR2,XTNCOLLECTION OUT SYS_REFCURSOR) IS
      P_SQL_CLEAR  VARCHAR2(32767);
      P_SQL_INSERT_BAN  VARCHAR2(32767);
      P_SQL_INSERT_BANBUON  VARCHAR2(32767);
      QUERY_STR  VARCHAR2(32767);
      P_SQL_INSERT_TRA_LAI VARCHAR2(32767);
      DK_WHERE VARCHAR2(32767):='';
      DK_WHERE_V_VTGD_XNT VARCHAR2(32767) := '';
      DK_GROUPBY VARCHAR2(32767):= '';
      BEGIN

            IF TRIM(P_MAMAYBAN) IS NOT NULL THEN
           DK_WHERE := DK_WHERE || ' AND MAQUAYBAN IN ('''||P_MAMAYBAN||''')';
           DK_GROUPBY := DK_GROUPBY || ',MAQUAYBAN';
           END IF;
           IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
           DK_WHERE := DK_WHERE || ' AND MANGUOITAO IN ('''||P_NGUOIDUNG||''')';
           DK_GROUPBY := DK_GROUPBY || ',MANGUOITAO';
           END IF;
           
           IF TRIM(P_MAMAYBAN) IS NOT NULL THEN
           DK_WHERE_V_VTGD_XNT := DK_WHERE_V_VTGD_XNT || ' AND MAMAYBAN IN ('''||P_MAMAYBAN||''')';
           END IF;
           IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
           DK_WHERE_V_VTGD_XNT := DK_WHERE_V_VTGD_XNT || ' AND NGUOITAO IN ('''||P_NGUOIDUNG||''')';
           END IF;

         P_SQL_CLEAR:= 'DELETE FROM TEMP_GDQ';
          P_SQL_INSERT_BAN := 'INSERT INTO TEMP_GDQ a(a.MADONVI,a.MANGUOITAO,a.MAQUAYBAN,a.NGUOITAO,a.TONGBAN,a.STT_TEMP)
              (SELECT TO_NCHAR(MADONVI) AS MADONVI,
                TO_NCHAR(MANGUOITAO) AS MANGUOITAO,
                TO_NCHAR(MAQUAYBAN) AS MAQUAYBAN,
                TO_NCHAR(NGUOITAO) AS NGUOITAO, 
                SUM(TTIENCOVAT) AS TONGBAN,1
                            FROM V_GDQUAY_HANGQUAY 
                            WHERE MADONVI LIKE '''||P_UNITCODE||'%'' AND LOAIGIAODICH = 1 AND NGAYPHATSINH >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') AND  NGAYPHATSINH <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')  '||DK_WHERE||'
                            group by MADONVI,NGUOITAO,MANGUOITAO,MAQUAYBAN )';
           P_SQL_INSERT_BANBUON := 'INSERT INTO TEMP_GDQ a(a.MADONVI,a.MANGUOITAO,a.MAQUAYBAN,a.NGUOITAO,a.TONGBAN,a.STT_TEMP)
           (SELECT TO_NCHAR(UNITCODE) AS MADONVI,
                TO_NCHAR(NGUOITAO) AS MANGUOITAO,
                TO_NCHAR(''QUAYBANBUON'') AS MAQUAYBAN, 
                '''' AS NGUOITAO,
                SUM(THANHTIEN) AS TONGBAN,1
              FROM VIEW_VATTUGD_XNT
          WHERE  UNITCODE LIKE '''||P_UNITCODE||'%'' 
          AND NGAYCHUNGTU >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
          AND NGAYCHUNGTU <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')
          AND TRANGTHAI = 10 AND LOAICHUNGTU=''XBAN'' '||DK_WHERE_V_VTGD_XNT||'
          GROUP BY UNITCODE,NGUOITAO)';
            P_SQL_INSERT_TRA_LAI := 'UPDATE  TEMP_GDQ a SET TONGTRALAI =(SELECT sum(ttiencovat) as TONGTRALAI
                                    FROM V_GDQUAY_HANGQUAY
                                    WHERE MADONVI LIKE '''||P_UNITCODE||'%'' AND LOAIGIAODICH = 2 AND NGAYPHATSINH >= TO_DATE('''||P_TUNGAY||''',''DD-MM-YY'') 
                                    AND NGAYPHATSINH <= TO_DATE('''||P_DENNGAY||''',''DD-MM-YY'')  '||DK_WHERE||' AND MAQUAYBAN = a.MAQUAYBAN AND MANGUOITAO = a.MANGUOITAO
                                    group by MADONVI,MANGUOITAO,MAQUAYBAN)'; 
           QUERY_STR := 'SELECT * FROM TEMP_GDQ';     
       BEGIN
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_BAN);
            DBMS_OUTPUT.PUT_LINE('------------------');
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_BANBUON);
            DBMS_OUTPUT.PUT_LINE('------------------');
            DBMS_OUTPUT.PUT_LINE(P_SQL_INSERT_TRA_LAI); 
            EXECUTE IMMEDIATE P_SQL_CLEAR;
            EXECUTE IMMEDIATE P_SQL_INSERT_BAN;
            EXECUTE IMMEDIATE P_SQL_INSERT_BANBUON;
            EXECUTE IMMEDIATE P_SQL_INSERT_TRA_LAI;
            OPEN XTNCOLLECTION FOR QUERY_STR;
       END;
  END BAOCAO_GIAODICHQUAY;