create or replace PROCEDURE  "BAOCAO_XBAN_CHITIET" (P_GROUPBY IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2, P_UNITUSER IN VARCHAR2, P_TAX IN VARCHAR2, P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2, P_MAKHACHHANG IN VARCHAR2, P_XUATXU IN VARCHAR2, P_UNITCODE  IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,P_ISPAY IN VARCHAR2 , cur  OUT SYS_REFCURSOR) IS
  P_EXPRESSION VARCHAR(3232);
  QUERY_STR VARCHAR(32767);
  P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
  BEGIN
IF TRIM(P_ISPAY) IS NOT NULL AND P_ISPAY <> 3 THEN
P_EXPRESSION := P_EXPRESSION||' AND t.TRANGTHAITHANHTOAN = '||P_ISPAY||'';
END IF;
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_XUATXU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAXUATXU IN ('||P_XUATXU||')';
END IF; 
IF TRIM(P_MAKHACHHANG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_MAKHACHHANG||')';
END IF;  
IF TRIM(P_UNITUSER) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MADONVINHAN IN ('||P_UNITUSER||')';
END IF;  
IF TRIM(P_TAX) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_TAX||')';
END IF; 
IF P_GROUPBY = 'MADONVIXUAT' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.UNITCODE,t.NGAYCHUNGTU';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.GROUPCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.UNITCODE AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.GROUPCODE = c.MADONVI';
END; 
ELSIF P_GROUPBY = 'MADONVINHAN' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MADONVINHAN,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MADONVI AS MaCha,  c.TENDONVI  AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MADONVINHAN AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.GROUPCODE = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,ct.VAT,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MALOAITHUE AS MaCha,  c.LOAITHUE AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , ct.VAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' LEFT JOIN DM_LOAITHUE c ON a.GROUPCODE = c.MALOAITHUE AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, t.MAKHOXUAT,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAKHO AS MaCha, c.TENKHO AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE , t.MAKHOXUAT AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.GROUPCODE = c.MAKHO AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MANHOMVATTU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT  ';
P_SELECT_COLUMNS_IN_GROUPBY:= 'b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE, b.MANHOMVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MALOAIVATTU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MALOAIVATTU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,  b.MAKHACHHANG,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MANCC AS MaCha, c.TENNCC AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.GROUPCODE = c.MANCC AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MAKHACHHANG,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.MAKH AS MaCha, c.TENKH AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MAKHACHHANG AS GROUPCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHACHHANG c ON a.GROUPCODE = c.MAKH AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.I_CREATE_BY,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, c.USERNAME AS MaCha, c.TENNHANVIEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.I_CREATE_BY AS GROUPCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON a.GROUPCODE = c.USERNAME AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAXUATXU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE, b.MAXUATXU,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,c.MAXUATXU AS MaCha, c.TENXUATXU AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, b.MAXUATXU AS GROUPCODE,t.NGAYCHUNGTU AS NGAYCHUNGTU, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DMXUATXU c ON a.GROUPCODE = c.MAXUATXU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MAGIAODICH' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.MACHUNGTUPK,t.NOIDUNG, t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE, a.MACHUNGTUPK AS MaCha, a.NOIDUNG AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN,b.BARCODE AS BARCODE, t.MACHUNGTUPK AS MACHUNGTUPK, t.NOIDUNG, t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU, b.TENVATTU,b.BARCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS MaCon, a.TEN AS TenCon,a.BARCODE AS BARCODE,  a.MA AS MaCha, a.TEN AS TenCha,a.NGAYCHUNGTU AS NgayGiaoDich, a.UNITCODE AS MADONVIXUAT';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ,b.BARCODE AS BARCODE,t.NGAYCHUNGTU, t.UNITCODE';
P_TABLE_GROUPBY:= ' ';
END;
END IF;

QUERY_STR := 'select a.SOLUONGBAN as SOLUONGBAN, a.VON, a.VON_COVAT, ROUND(a.TIENTHUE) AS TIENTHUE,
                     a.DOANHTHU, ROUND(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, a.TIENCHIETKHAU, ROUND(a.DOANHTHU - a.VON) AS LAIBANLE, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
FROM (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(NVL(ct.SOLUONG,0)) as SOLUONGBAN
                          ,SUM(NVL(ct.GIAVON,0) * NVL(ct.SOLUONG,0)) AS VON
                          ,SUM(NVL(ct.GIAVON * (1 + (g.TYGIA / 100)), 0) * NVL(ct.SOLUONG, 0)) AS VON_COVAT
                          ,ROUND(SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) > 0 AND NVL(t.THANHTIENTRUOCVAT,0) > 0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END),2) as TIENCHIETKHAU
                          ,ROUND(SUM((NVL(ct.SOLUONG,0) * NVL(ct.DONGIA,0))/(1+ NVL(g.TYGIA,0) /100))) as DOANHTHU                         
                          ,SUM(((NVL(g.TYGIA,0) / 100)*(NVL(ct.SOLUONG,0) *NVL(ct.DONGIA,0)))/(1+ NVL(g.TYGIA,0) /100)) as TIENTHUE
FROM VATTUCHUNGTUCHITIET ct 
INNER JOIN VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''XBAN''
INNER JOIN V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND b.MADONVI= t.UNITCODE
LEFT JOIN DM_LOAITHUE g on g.MALOAITHUE = ct.VAT
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE '''||P_UNITCODE||'%''
    AND TO_DATE(t.NGAYDUYETPHIEU,''DD/MM/YY'') <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND TO_DATE(t.NGAYDUYETPHIEU,''DD/MM/YY'') >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||'
	GROUP BY '||P_COLUMNS_GROUPBY||' order by t.NGAYCHUNGTU DESC) a  '||P_TABLE_GROUPBY || ' ORDER BY a.MA';   
    DBMS_OUTPUT.put_line (QUERY_STR);  
    OPEN CUR FOR QUERY_STR;
    EXCEPTION
                WHEN NO_DATA_FOUND THEN
                 NULL;
                   WHEN OTHERS THEN
          NULL;

  END BAOCAO_XBAN_CHITIET;
--------------------------------------------------------
--  DDL for Procedure BAOCAO_XBAN_CHITIET
--------------------------------------------------------
 