create or replace PROCEDURE            "BAOCAO_CNNCC_CHITIET" (P_UNITCODE IN VARCHAR2, P_MANHACUNGCAP IN VARCHAR2, P_TUNGAY IN DATE,P_DENNGAY IN DATE,  cur  OUT SYS_REFCURSOR) IS
QUERY_STR VARCHAR(32767);
SUB_QUERY_STR VARCHAR(32767);
P_EXPRESSION VARCHAR(32767):= '';
INSERT_STR VARCHAR(32767);
SUB_INSERT_STR VARCHAR(32767);
CREATE_TABLE VARCHAR(32767);
CHECK_EXIST_TABLE NUMBER;
CN_CUR SYS_REFCURSOR;
SUB_CUR SYS_REFCURSOR;
I_MANHACUNGCAP VARCHAR(20);
I_UNITCODE VARCHAR(20);
I_AMMOUNT NUMBER(18,2) :=0;
I_PAYBEFORE NUMBER(18,2) :=0;
I_BORROWBEFORE NUMBER(18,2) :=0;
C_MACHUNGTU VARCHAR2(50);
C_LOAICHUNGTU VARCHAR2(20);
C_NGAYCT DATE;
C_MANHACUNGCAP VARCHAR2(50);
C_UNITCODE VARCHAR2(20);
C_PAYNOW NUMBER(18,2);
C_BORROW_NOW NUMBER(18,2);
I_STT NUMBER(18,2) :=0;
I_SUM NUMBER(18,2) :=0;
BEGIN
    --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TEMP_CONGNO" 
   (	
   "STT" NUMBER(18,2) DEFAULT 0,
   "UNITCODE" NVARCHAR2(20), 
	"MAKHACHHANG" NVARCHAR2(20), 
	"MANHACUNGCAP" NVARCHAR2(20), 
	"NGAYCT" DATE, 
	"MACHUNGTU" NVARCHAR2(50), 
    "LOAICHUNGTU" NVARCHAR2(20),
	"TIENTHU" NUMBER(18,2) DEFAULT 0, 
	"TIENBAN" NUMBER(18,2) DEFAULT 0, 
	"TIENNO" NUMBER(18,2) DEFAULT 0
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''TEMP_CONGNO''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM TEMP_CONGNO';
   --BEGIN...
    IF TRIM(P_MANHACUNGCAP) IS NOT NULL THEN
        P_EXPRESSION := P_EXPRESSION || 'AND u.MANHACUNGCAP IN ('||P_MANHACUNGCAP||')';
    END IF;
    --GET ALL MANHACUNGCAP, UNITCODE
    I_STT :=0;
    QUERY_STR := 'SELECT DISTINCT u.MANHACUNGCAP, u.UNITCODE FROM V_VTCT_CONGNO u WHERE u.UNITCODE IS NOT NULL AND u.UNITCODE LIKE '''||P_UNITCODE||'%'' AND u.MANHACUNGCAP IS NOT NULL AND u.LOAICHUNGTU IN (''CNNCC'',''NMUA'') '||P_EXPRESSION||' ORDER BY u.MANHACUNGCAP';
    OPEN CN_CUR FOR QUERY_STR;
    LOOP
         FETCH CN_CUR INTO I_MANHACUNGCAP, I_UNITCODE;
         EXIT WHEN CN_CUR%NOTFOUND;    
         --CALCULATE 'TONDAUKY' FOR 'I_AMMOUNT'
         I_PAYBEFORE :=0;
         I_BORROWBEFORE :=0;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGTHU FROM V_VTCT_CONGNO u
         WHERE u.LOAICHUNGTU = ''CNNCC'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MANHACUNGCAP = '''||I_MANHACUNGCAP||''' ' INTO I_PAYBEFORE;
         EXECUTE IMMEDIATE 'SELECT SUM(NVL(u.THANHTIEN,0)) AS TONGBAN FROM V_VTCT_CONGNO u 
         WHERE u.LOAICHUNGTU = ''NMUA'' AND u.UNITCODE = '''||I_UNITCODE||''' AND u.NGAYCT < TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.MANHACUNGCAP = '''||I_MANHACUNGCAP||''' ' INTO I_BORROWBEFORE;

         I_AMMOUNT := NVL(I_BORROWBEFORE,0) - NVL(I_PAYBEFORE,0);
         I_STT := I_STT +1;
         --INSERT MANHACUNGCAP,UNITCODE 'TONDAUKY'
         INSERT_STR:= 'INSERT INTO TEMP_CONGNO (STT, UNITCODE, MANHACUNGCAP, TIENNO) VALUES ('||I_STT||','''||I_UNITCODE||''', '''||I_MANHACUNGCAP||''', '||I_AMMOUNT||')';
         EXECUTE IMMEDIATE INSERT_STR;
         --CALCULATE AMMOUNT EACH RECORD. THEN INSERT...
         SUB_QUERY_STR := 'SELECT u.MACHUNGTU, u.LOAICHUNGTU, u.NGAYCT, u.MANHACUNGCAP, u.UNITCODE, 0 AS TIENTHU, u.THANHTIEN AS TIENBAN FROM V_VTCT_CONGNO u WHERE u.LOAICHUNGTU =''NMUA''
                AND u.UNITCODE = '''||I_UNITCODE||''' AND u.MANHACUNGCAP = '''||I_MANHACUNGCAP||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
         UNION ALL 
                SELECT u.MACHUNGTU, u.LOAICHUNGTU, u.NGAYCT, u.MANHACUNGCAP, u.UNITCODE, u.THANHTIEN AS TIENTHU, 0 AS TIENBAN FROM V_VTCT_CONGNO u WHERE u.LOAICHUNGTU =''CNNCC''
                AND u.UNITCODE = '''||I_UNITCODE||''' AND u.MANHACUNGCAP = '''||I_MANHACUNGCAP||''' AND u.NGAYCT >= TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND u.NGAYCT <= TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')';
        OPEN SUB_CUR FOR SUB_QUERY_STR;
        LOOP
             FETCH SUB_CUR INTO C_MACHUNGTU, C_LOAICHUNGTU, C_NGAYCT, C_MANHACUNGCAP, C_UNITCODE, C_PAYNOW, C_BORROW_NOW;
             EXIT WHEN SUB_CUR%NOTFOUND;
             I_AMMOUNT := I_AMMOUNT + C_BORROW_NOW - C_PAYNOW ;
             I_STT := I_STT +1;
             EXECUTE IMMEDIATE 'INSERT INTO TEMP_CONGNO(STT, UNITCODE, MANHACUNGCAP, NGAYCT, MACHUNGTU, LOAICHUNGTU, TIENTHU, TIENBAN, TIENNO) 
                            VALUES ('||I_STT||', '''||C_UNITCODE||''', '''||C_MANHACUNGCAP||''',TO_DATE('''||C_NGAYCT||''',''DD/MM/YY''),'''||C_MACHUNGTU||''','''||C_LOAICHUNGTU||''','||C_PAYNOW||','||C_BORROW_NOW||' ,'||I_AMMOUNT||')';
        END LOOP;
        CLOSE SUB_CUR;
        I_SUM := I_SUM + I_AMMOUNT;
    END LOOP;
    EXECUTE IMMEDIATE 'INSERT INTO TEMP_CONGNO(TIENNO) VALUES ('''||I_SUM||''')';
    CLOSE CN_CUR;
 BEGIN
 -- RESULT...
QUERY_STR:= 'SELECT T.UNITCODE, T.MANHACUNGCAP, NCC.TENNCC, T.NGAYCT, T.MACHUNGTU, T.TIENTHU, T.TIENBAN, T.TIENNO FROM TEMP_CONGNO T LEFT JOIN DM_NHACUNGCAP NCC ON T.MANHACUNGCAP = NCC.MANCC AND SUBSTR(T.UNITCODE,0,3) = SUBSTR(NCC.UNITCODE,0,3) ORDER BY STT';
OPEN CUR FOR QUERY_STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (QUERY_STR || SQLERRM);  
END;
END BAOCAO_CNNCC_CHITIET;