
  CREATE OR REPLACE FORCE VIEW "TBNETERP"."V_CHUONGTRINH_KHUYENMAI" ("MACHUONGTRINH", "TUNGAY", "DENNGAY", "TUGIO", "DENGIO", "GIATRIKHUYENMAI", "TYLEKHUYENMAI", "TYLEBATDAU", "MAKHOKHUYENMAI", "LOAIKHUYENMAI", "TIENBATDAU", "TIENKETTHUC", "MAGIAMGIA", "NOIDUNG", "UNITCODE", "TRANGTHAI", "MAVATTU", "HANGKMCHINH", "MAHANG_KHUYENMAI", "SOLUONG_KHUYENMAI", "TYLEKHUYENMAICHILDREN", "GIATRIKHUYENMAICHILDREN", "SOLUONG", "MAHANG_KM_BUY1GET1", "TENHANG_KM_BUY1GET1", "SOLUONG_KM_BUY1GET1") AS 
  SELECT E."MACHUONGTRINH",E."TUNGAY",E."DENNGAY",E."TUGIO",E."DENGIO",E."GIATRIKHUYENMAI",E."TYLEKHUYENMAI",E.TYLEBATDAU,E."MAKHOKHUYENMAI",E."LOAIKHUYENMAI",E."TIENBATDAU",E."TIENKETTHUC",E."MAGIAMGIA",E."NOIDUNG",E."UNITCODE",E."TRANGTHAI",E."MAVATTU",E."HANGKMCHINH",E."MAHANG_KHUYENMAI",E."SOLUONG_KHUYENMAI",E."TYLEKHUYENMAICHILDREN",E."GIATRIKHUYENMAICHILDREN",E."SOLUONG",F.MAHANG AS MAHANG_KM_BUY1GET1,F.TENHANG AS TENHANG_KM_BUY1GET1,NVL(F.SOLUONG,0) AS SOLUONG_KM_BUY1GET1 FROM
  (SELECT A.MACHUONGTRINH,
    A.TUNGAY AS TuNgay,
    A.DENNGAY AS DenNgay,
    A.TUGIO AS TuGio,
    A.DENGIO AS DenGio,
    NVL(A.GIATRIKHUYENMAI,0) AS GiaTriKhuyenMai,
    NVL(A.TYLEKHUYENMAI,0) AS TyLeKhuyenMai,
    NVL(A.TYLEBATDAU,0) AS TyLeBatDau,
    A.MAKHOKHUYENMAI AS MaKhoKhuyenMai,
    A.LOAIKHUYENMAI AS LoaiKhuyenMai,
    NVL(A.TIENBATDAU,0) AS TienBatDau,
    NVL(A.TIENKETTHUC,0) AS TienKetThuc,
    A.MAGIAMGIA AS MaGiamGia,
    A.NOIDUNG AS NoiDung,
    A.UNITCODE AS UnitCode,
    A.TRANGTHAI AS TrangThai,
    B.MAHANG AS MaVatTu,
    NVL(B.HANGKMCHINH,0) AS HangKmChinh,
    B.MAHANG_KHUYENMAI AS MaHang_KhuyenMai,
    NVL(B.SOLUONG_KHUYENMAI,0) AS SoLuong_KhuyenMai,
    NVL(B.TYLEKHUYENMAI,0) AS TyLeKhuyenMaiChildren,
    NVL(B.GIATRIKHUYENMAI,0) AS GiaTriKhuyenMaiChildren,
    NVL(B.SOLUONG,0) AS SoLuong FROM NV_CT_KHUYENMAI A INNER JOIN NV_CT_KHUYENMAI_CHITIET B ON A.MACHUONGTRINH = B.MACHUONGTRINH AND A.TRANGTHAI = 10 ) E 
    LEFT JOIN NV_CT_KHUYENMAI_HANGKM F ON E.MACHUONGTRINH = F.MACHUONGTRINH;
 
