--ANHPT VIEW_VATTUGD_XNT LAST VERSION
  CREATE OR REPLACE FORCE VIEW "TBNETERP"."VIEW_VATTUGD_XNT" ("ID", "UNITCODE", "TRANGTHAI", "LOAICHUNGTU", "NGAYCHUNGTU", "MAVATTU", "MAKHOXUAT", "MAKHONHAP", "MADONVINHAN", "MADONVIXUAT", "SOLUONG", "DONGIA", "THANHTIEN", "NGUOITAO", "MAMAYBAN") AS 
  SELECT VATTUCHUNGTU.ID, UNITCODE,
	   TRANGTHAI,
       LOAICHUNGTU,
       TO_DATE(NGAYDUYETPHIEU,'DD/MM/YY') AS NGAYCHUNGTU,
	   VATTUCHUNGTUCHITIET.MAHANG as MAVATTU,
       MAKHOXUAT,
       MAKHONHAP,
       MADONVINHAN,
       MADONVIXUAT,
       SOLUONG,
       DONGIA,
       THANHTIEN,
	   I_CREATE_BY AS NGUOITAO,
	   TO_NCHAR('') AS MAMAYBAN
  FROM VATTUCHUNGTU
       INNER JOIN VATTUCHUNGTUCHITIET
          ON (VATTUCHUNGTU.MACHUNGTUPK = VATTUCHUNGTUCHITIET.MACHUNGTUPK)
          WHERE TRANGTHAI=10
UNION ALL
SELECT a.ID AS ID, TO_NCHAR(a.MADONVI) AS UNITCODE,
	   10 AS TRANGTHAI,
       TO_NCHAR(LOAIGIAODICH) AS LOAICHUNGTU,
       TO_DATE(a.NGAYPHATSINH,'DD/MM/YY') AS NGAYCHUNGTU,
	   ct.MAVATTU AS MAVATTU,
       TO_NCHAR(ct.MAKHOHANG) AS MAKHOXUAT,
       TO_NCHAR(ct.MAKHOHANG) AS MAKHONHAP,
       TO_NCHAR(a.MADONVI) as MADONVINHAN,
       TO_NCHAR(a.MADONVI) as MADONVIXUAT,
       ct.SOLUONG AS SOLUONG,
       ct.GIABANLECOVAT/(1 + VATBAN/100) DONGIA,
       ct.TTIENCOVAT AS THANHTIEN,
        TO_NCHAR(a.NGUOITAO) AS NGUOITAO,
	   TO_NCHAR(a.MAQUAYBAN) AS MAMAYBAN
  FROM NVGDQUAY_ASYNCCLIENT a
       INNER JOIN NVHANGGDQUAY_ASYNCCLIENT ct
          ON (a.MAGIAODICHQUAYPK = ct.MAGDQUAYPK)
  UNION ALL
SELECT kkct.ID AS ID, TO_NCHAR(kkct.MADONVI) AS UNITCODE,kk.TRANGTHAI AS TRANGTHAI,
    TO_NCHAR(SUBSTR(kk.MAPHIEUKIEMKE,0,4)) AS LOAICHUNGTU, TO_DATE(kk.NGAYDUYETPHIEU,'DD/MM/YY') AS NGAYCHUNGTU,
    kkct.MAVATTU AS MAVATTU, TO_NCHAR(kkct.KHOKIEMKE) AS MAKHOXUAT, TO_NCHAR(kk.KHOKIEMKE) AS MAKHONHAP,
    TO_NCHAR(kkct.MADONVI) AS MADONVINHAN, TO_NCHAR(kkct.MADONVI) AS MADONVIXUAT,
    kkct.SOLUONGCHENHLECH AS SOLUONG, kkct.GIAVON AS DONGIA, kkct.TIENCHENHLECH AS THANHTIEN,
    TO_NCHAR(kk.NGUOITAO) AS NGUOITAO, TO_NCHAR('KEKIEMKE') AS MAMAYBAN
    FROM NVKIEMKE kk INNER JOIN NVKIEMKECHITIET kkct 
    ON (kk.MAPHIEUKIEMKE = kkct.MAPHIEUKIEMKE);
 
/