create or replace PROCEDURE  "NHAPBANBUONTRALAITONGHOP" (P_LOAICHUNGTU IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_WAREHOUSE IN VARCHAR2, 
P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2,
P_NHACUNGCAP IN VARCHAR2,P_UNITCODE  IN VARCHAR2, P_MATHUE  IN VARCHAR2,
P_TUNGAY IN DATE,P_DENNGAY IN DATE, cur  OUT SYS_REFCURSOR) AS

P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);

BEGIN
IF TRIM(P_UNITCODE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.UNITCODE = '''||P_UNITCODE||''' ';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;
IF TRIM(P_MATHUE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_MATHUE||')';
END IF; 

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP, c.TENKHO';
P_SELECT_COLUMNS_GROUPBY:= ' a.MAKHO AS MaCha, a.TENKHO AS TenCha ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON t.MAKHONHAP = c.MAKHO AND c.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='t.MAKHONHAP AS MAKHO,c.TENKHO AS TENKHO';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE, c.TENDONVI';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MADONVI, ''NULL'')  as MaCha, NVL(a.TENDONVI, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON t.UNITCODE = c.MADONVI AND c.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='t.UNITCODE AS MADONVI,c.TENDONVI AS TENDONVI';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DM_NHOMVATTU kh on b.MANHOMVATTU = kh.MANHOMVTU AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:=' b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MAKHACHHANG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG , kh.TENKH';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join DM_KHACHHANG kh on t.MAKHACHHANG = kh.MAKH AND kh.LOAIKHACHHANG =1 AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:=' t.MAKHACHHANG AS MAKHACHHANG,kh.TENKH as TENKH';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY , kh.TENNHANVIEN';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.USERNAME, ''NULL'')  as MaCha, NVL(a.TENNHANVIEN, ''NULL'') as TenCha ';
P_TABLE_GROUPBY:= ' inner join AU_NGUOIDUNG kh on t.I_CREATE_BY = kh.USERNAME AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:=' t.I_CREATE_BY AS USERNAME,kh.TENNHANVIEN as TENNHANVIEN';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY ='MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= ' lt.MALOAITHUE ,lt.LOAITHUE';
P_SELECT_COLUMNS_GROUPBY:= 'a.MaCha , a.TenCha';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:='lt.MALOAITHUE as MaCha , lt.LOAITHUE as TenCha';
P_SELECT:= '';
END;
ELSIF P_GROUPBY ='MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= ' ncc.MANCC ,ncc.TENNCC';
P_SELECT_COLUMNS_GROUPBY:= 'a.MaCha , a.TenCha';
P_TABLE_GROUPBY:= 'inner join DM_NHACUNGCAP ncc on ncc.MANCC = b.MAKHACHHANG AND b.UNITCODE = '''||P_UNITCODE||''' ';
P_SELECT2:='ncc.MANCC as MaCha , ncc.TENNCC as TenCha';
P_SELECT:= '';
END;
ELSIF P_GROUPBY ='PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= ' t.MACHUNGTU, t.MACHUNGTUPK';
P_SELECT_COLUMNS_GROUPBY:= 'a.MaCha , a.TenCha';
P_SELECT2:='t.MACHUNGTU as MaCha , t.MACHUNGTUPK as TenCha';
P_SELECT:= '';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,b.GIABANBUON,b.GiaBanLeVat';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon ';
P_TABLE_GROUPBY:= ' AND b.UNITCODE = '''||P_UNITCODE||''' ';
P_SELECT2:=' b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= 'b.GIABANBUON as DONGIANHAP,b.GiaBanLeVat as GiaBanLeVat ,';
END;
END IF;
QUERY_STR:= 'select (a.SOLUONG) as SoLuong, (a.TIENHANG) as TienHang, (a.TIENVAT) as TienVat, (a.TIENCHIETKHAU) as TienChietKhau, (a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,'||P_SELECT_COLUMNS_GROUPBY||'
from (
SELECT   '||P_SELECT2||',
          SUM(ct.SOLUONG) as SOLUONG, 
          SUM(ct.SOLUONG*ROUND(NVL(ct.DONGIA,0))) AS TIENHANG ,
          '||P_SELECT||' 
          ROUND(SUM(ROUND(NVL(ct.DONGIA,0))*NVL(lt.TYGIA/100,0)*ct.SOLUONG)) AS TIENVAT, 
          SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END) as TIENCHIETKHAU
from VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
LEFT JOIN DM_LOAITHUE lt on lt.MALOAITHUE = ct.VAT
inner join V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND b.UNITCODE = '''||P_UNITCODE||'''
'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' group by '||P_COLUMNS_GROUPBY||') a';
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPBANBUONTRALAITONGHOP;
--------------------------------------------------------
--  DDL for Procedure NHAPBANBUONTRALAITONGHOP
--------------------------------------------------------