CREATE GLOBAL TEMPORARY TABLE "TBNETERP"."TAB_TONGHOPBC_TMP" 
   (	"SOCT" NVARCHAR2(50), 
	"NGAYCT" NVARCHAR2(10), 
	"NOIDUNG" NVARCHAR2(500), 
	"TAIKHOAN" NVARCHAR2(10), 
	"TAIKHOANDOI" NVARCHAR2(10), 
	"NO" NUMBER, 
	"CO" NUMBER, 
	"STT" NVARCHAR2(200)
   ) ON COMMIT DELETE ROWS ;
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."SOCT" IS 'So chung tu';
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."NOIDUNG" IS 'Noi dung';
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."TAIKHOAN" IS 'Tai khoan';
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."NO" IS 'Tien No';
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."CO" IS 'Tien Co';
   COMMENT ON COLUMN "TBNETERP"."TAB_TONGHOPBC_TMP"."STT" IS 'So thu tu sap xep';
   COMMENT ON TABLE "TBNETERP"."TAB_TONGHOPBC_TMP"  IS 'NhuanNH - Tong hop so lieu len bao cao';
