create or replace PROCEDURE            "BAOCAO_NHHHH_CHITIET" (P_GROUPBY IN VARCHAR2, P_MALOAI IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, P_NHACUNGCAP IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_TUNGAY IN DATE, P_DENNGAY IN DATE, P_NHH IN VARCHAR2, P_SYNTAX IN VARCHAR2, CUR  OUT SYS_REFCURSOR) AS
QUERY_STR VARCHAR(32767);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_JOIN_DKIEN VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_EXPRESSION  VARCHAR(32767):= '';
P_EXPRESSION2  VARCHAR(32767):= '';
BEGIN
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND dmvt.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND dmvt.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MANHACUNGCAP IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_NHH) IS NOT NULL THEN
P_EXPRESSION2 := 'AND (TO_DATE(ct.NGAYHETHAN) - TO_DATE(SYSDATE))' || P_SYNTAX ||P_NHH;
END IF;
IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= '';
P_SELECT_COLUMNS_OUT_GROUPBY:= '  c.MADONVI AS MaCha, c.TENDONVI  AS TenCha, a.GROUPCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS GROUPCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.GROUPCODE = c.MADONVI';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'dmvt.MANHOMVATTU,';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS MaCha, c.TENNHOMVT AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' dmvt.MANHOMVATTU AS GROUPCODE, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.GROUPCODE = c.MANHOMVTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'dmvt.MALOAIVATTU,';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS MaCha, c.TENLOAIVT AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' dmvt.MALOAIVATTU AS GROUPCODE, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.GROUPCODE = c.MALOAIVATTU AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.MANHACUNGCAP,';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANCC AS MaCha, c.TENNCC AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.MANHACUNGCAP AS GROUPCODE, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.GROUPCODE = c.MANCC AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY,';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.USERNAME AS MaCha, c.TENNHANVIEN AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.I_CREATE_BY AS GROUPCODE, t.UNITCODE ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON a.GROUPCODE = c.USERNAME AND c.UNITCODE = a.UNITCODE';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAPHIEU, t.NOIDUNG,';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.GROUPCODE AS MaCha, a.NOIDUNG AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAPHIEU AS GROUPCODE, t.UNITCODE, t.NOIDUNG ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= '';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' a.MA AS MaCha, a.TEN AS TenCha, a.UNITCODE AS MADONVI ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE ';
P_TABLE_GROUPBY:= '  ';
END;
END IF;

QUERY_STR := 'select 
                a.CONLAI_NGAYBAO as CONLAI_NGAYBAO, 
                a.CONLAI_NGAYHETHAN as CONLAI_NGAYHETHAN, 
                a.NGAYSANXUAT as NGAYSANXUAT, 
                a.NGAYHETHAN as NGAYHETHAN, 
                a.BARCODE AS BARCODE, 
                a.SOLUONG AS SOLUONG,
                a.NGAYBAODATE AS NGAYBAODATE,
                a.MA AS MaCon, a.TEN AS TenCon,
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
from (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,dmvt.MAVATTU AS MA
                          ,dmvt.TENVATTU AS TEN
                          ,dmvt.BARCODE AS BARCODE
                          ,t.NGAYBAODATE AS NGAYBAODATE
                          ,ct.NGAYHETHAN as NGAYHETHAN
                          ,ct.NGAYSANXUAT as NGAYSANXUAT
                          ,ct.CONLAI_NGAYBAO as CONLAI_NGAYBAO
                          ,ct.SOLUONG AS SOLUONG
                          ,(TO_DATE(ct.NGAYHETHAN) - TO_DATE(SYSDATE)) as CONLAI_NGAYHETHAN
from NVHETHAN_HANGHOA_CHITIET ct 
inner join NVHETHAN_HANGHOA t on t.MAPHIEUPK = ct.MAPHIEUPK
INNER JOIN DM_VATTU dmvt on dmvt.MAVATTU = ct.MAVATTU
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE LIKE '''||P_UNITCODE||'%''
    AND t.NGAYBAODATE <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYBAODATE >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
    '||P_EXPRESSION2||'
	'||P_EXPRESSION||'
	group by '||P_COLUMNS_GROUPBY||'
            dmvt.MAVATTU, dmvt.TENVATTU, dmvt.BARCODE, t.NGAYBAODATE, t.UNITCODE,ct.CONLAI_NGAYBAO, ct.SOLUONG
            ,ct.NGAYHETHAN, ct.NGAYSANXUAT order by t.NGAYBAODATE DESC) a '||P_TABLE_GROUPBY|| ' ORDER BY a.MA';
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_NHHHH_CHITIET;