create or replace PROCEDURE   "BAOCAO_DCN_TONGHOP" (P_TABLE_NAME IN VARCHAR2,P_GROUPBY IN VARCHAR2, P_PTHUCNHAN IN VARCHAR2, 
P_MAKHO IN VARCHAR2, P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2, 
P_NHACUNGCAP IN VARCHAR2, P_UNITCODE IN VARCHAR2, P_MATHUE IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2,
P_TUNGAY IN DATE, P_DENNGAY IN DATE, CUR  OUT SYS_REFCURSOR) AS

QUERY_STR VARCHAR(3000);
P_SELECT_COLUMNS_IN_GROUPBY VARCHAR(3000);
P_SELECT_COLUMNS_OUT_GROUPBY VARCHAR(3000);
P_TABLE_GROUPBY VARCHAR(3000);
P_COLUMNS_GROUPBY VARCHAR(3000);
P_EXPRESSION  VARCHAR(3000):= '';
P_WHERE_PTNHAN VARCHAR(3000):= '';
P_NOTNULL VARCHAR(1000):= '';
BEGIN
IF P_PTHUCNHAN = 'NHANCHUYENKHO' THEN
    P_WHERE_PTNHAN := ' AND NVL(t.MADONVIXUAT,'''') = NVL(t.UNITCODE,'''') ';
ELSE 
    P_WHERE_PTNHAN := ' AND NVL(t.MADONVIXUAT,'''') <> NVL(t.UNITCODE,'''') ';
END IF;
IF TRIM(P_MAKHO) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHOXUAT IN ('||P_MAKHO||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAVATTU IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;  
IF TRIM(P_MATHUE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_MATHUE||')';
END IF;

IF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MAKHO AS Ma, c.TENKHO AS Ten , a.MAKHOXUAT , a.MAKHONHAP';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MAKHOXUAT AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON a.MA = c.MAKHO AND c.UNITCODE = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND t.MAKHOXUAT IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MADONVI AS Ma, c.TENDONVI AS Ten,a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.UNITCODE AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON a.MA = c.MADONVI AND c.MADONVI = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND t.UNITCODE IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= ' c.MANHOMVTU AS Ma, c.TENNHOMVT AS Ten, a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MANHOMVATTU AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU c ON a.MA = c.MANHOMVTU AND c.UNITCODE = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND b.MANHOMVATTU IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAIVATTU AS Ma, c.TENLOAIVT AS Ten, a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MALOAIVATTU as MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU c ON a.MA = c.MALOAIVATTU AND c.UNITCODE = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND b.MALOAIVATTU IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAKHACHHANG,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MANCC AS Ma, c.TENNCC AS Ten , a.MAKHOXUAT , a.MAKHONHAP';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAKHACHHANG AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP c ON a.MA = c.MANCC AND c.UNITCODE = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND b.MAKHACHHANG IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.USERNAME AS Ma, c.TENNHANVIEN AS Ten, a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.I_CREATE_BY AS MA ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON a.MA = c.USERNAME AND c.UNITCODE = '''||P_UNITCODE||'''';
END;
ELSIF P_GROUPBY = 'MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.VAT ,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'c.MALOAITHUE AS Ma, c.LOAITHUE AS Ten, a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' ct.VAT AS MA ';
P_TABLE_GROUPBY:= ' LEFT JOIN DM_LOAITHUE c ON a.MA = c.MALOAITHUE AND c.UNITCODE = '''||P_UNITCODE||'''';
P_NOTNULL := ' AND ct.VAT IS NOT NULL ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK, t.UNITCODE, t.NOIDUNG,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten,a.UNITCODE AS MADONVI , a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' t.MACHUNGTUPK AS MA , t.NOIDUNG AS TEN, t.UNITCODE ';
P_TABLE_GROUPBY:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,t.MAKHONHAP,t.MAKHOXUAT';
P_SELECT_COLUMNS_OUT_GROUPBY:= 'a.MA AS Ma, a.TEN AS Ten, a.MAKHOXUAT , a.MAKHONHAP ';
P_SELECT_COLUMNS_IN_GROUPBY:= ' b.MAVATTU AS MA, b.TENVATTU AS TEN ';
P_TABLE_GROUPBY:= '';
P_NOTNULL := ' AND b.MAVATTU IS NOT NULL ';
END;
END IF;

QUERY_STR := 'select ROUND(a.SOLUONGBAN,2) as SOLUONGBAN, a.DONGIANHAP, ROUND(a.TIENTHUE,2) AS TIENTHUE,ROUND(a.DOANHTHU,2) AS DOANHTHU,
(a.DOANHTHU + a.TIENTHUE) AS TONGBAN, a.TIENCHIETKHAU, 
'||P_SELECT_COLUMNS_OUT_GROUPBY||'
FROM (
SELECT  '||P_SELECT_COLUMNS_IN_GROUPBY||'
                          ,SUM(ct.SOLUONG) as SOLUONGBAN
                          ,ROUND(SUM(ct.DONGIA),2) as DONGIANHAP
                          ,ROUND(SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END),2) as TIENCHIETKHAU
                          ,ROUND(SUM(ct.SOLUONG * ct.DONGIA),2) as DOANHTHU 
                          ,(SUM(ROUND((NVL(g.TYGIA,0) / 100)*(ct.SOLUONG *ct.DONGIA)))) as TIENTHUE
                          ,t.MAKHONHAP AS MAKHONHAP,t.MAKHOXUAT AS MAKHOXUAT
FROM VATTUCHUNGTUCHITIET ct 
inner join VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK AND t.LOAICHUNGTU = ''DCN'' '||P_WHERE_PTNHAN||'
INNER JOIN DM_VATTU b on b.MAVATTU = ct.MAHANG
LEFT JOIN DM_LOAITHUE g on g.MALOAITHUE = ct.VAT
WHERE
    t.TRANGTHAI = 10
    AND t.UNITCODE = '''||P_UNITCODE||'''
    AND t.NGAYDUYETPHIEU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYDUYETPHIEU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'')
	'||P_EXPRESSION||' '||P_NOTNULL||' GROUP BY  '||P_COLUMNS_GROUPBY||' ORDER BY '||P_COLUMNS_GROUPBY||' ) a 
 '||P_TABLE_GROUPBY ||'';
BEGIN
DBMS_OUTPUT.put_line (QUERY_STR);  
OPEN CUR FOR QUERY_STR;
EXCEPTION
            WHEN NO_DATA_FOUND THEN
             NULL;
               WHEN OTHERS THEN
      NULL;
END;
END BAOCAO_DCN_TONGHOP;
--------------------------------------------------------
--BAOCAO_DCN_TONGHOP---
--------------------------------------------------------
 