// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20180617_addColQuyen_nhomquyen_Anhpt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180617_addColQuyen_nhomquyen_Anhpt));
        
        string IMigrationMetadata.Id
        {
            get { return "201806171122550_20180617_addColQuyen_nhomquyen_Anhpt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
