// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01042018_addColTienNoCu_VatTuChungTu_HuyNQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01042018_addColTienNoCu_VatTuChungTu_HuyNQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201804010508178_01042018_addColTienNoCu_VatTuChungTu_HuyNQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
