// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _24012018_InitializeDatabase_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24012018_InitializeDatabase_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201801241212356_24012018_InitializeDatabase_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
