// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05_04_2018_Update_VatTuChungTuChiTiet_Hieu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05_04_2018_Update_VatTuChungTuChiTiet_Hieu));
        
        string IMigrationMetadata.Id
        {
            get { return "201804050756163_05_04_2018_Update_VatTuChungTuChiTiet_Hieu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
