// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30012018_AddFielNvDatHang_HuyNQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30012018_AddFielNvDatHang_HuyNQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201801300300445_30012018_AddFielNvDatHang_HuyNQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
