// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _21032018_dropTableNvCongNo_HuyNQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21032018_dropTableNvCongNo_HuyNQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201803210220549_21032018_dropTableNvCongNo_HuyNQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
