// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07032018_NullableTrangThaiCon_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07032018_NullableTrangThaiCon_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201803070347333_07032018_NullableTrangThaiCon_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
