// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _29_03_2018_CreateNvHetHanHangHoa_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29_03_2018_CreateNvHetHanHangHoa_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201803290227275_29_03_2018_CreateNvHetHanHangHoa_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
