// <auto-generated />
namespace BTS.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _04062018_alterTableVtct_congno_HuyNQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04062018_alterTableVtct_congno_HuyNQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201806031857556_04062018_alterTableVtct_congno_HuyNQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
