create or replace PROCEDURE "NHAPMUACHITIET" (P_LOAICHUNGTU IN VARCHAR2, P_GROUPBY IN VARCHAR2,P_WAREHOUSE IN VARCHAR2, 
P_MALOAI IN VARCHAR2,  P_MANHOM IN VARCHAR2,P_MAVATTU IN VARCHAR2,P_NHACUNGCAP IN VARCHAR2,
P_UNITCODE  IN VARCHAR2, P_NGUOIDUNG IN VARCHAR2,
P_TUNGAY IN DATE,P_DENNGAY IN DATE,
P_MATHUE IN VARCHAR2,
cur  OUT SYS_REFCURSOR) AS
P_EXPRESSION VARCHAR(3232);
QUERY_STR VARCHAR(32767);
P_TABLE_GROUPBY VARCHAR(32767);
P_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT_COLUMNS_GROUPBY VARCHAR(32767);
P_SELECT VARCHAR(3232);
P_SELECT2 VARCHAR(3232);
BEGIN
IF TRIM(P_WAREHOUSE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHONHAP IN ('||P_WAREHOUSE||')';
END IF;
IF TRIM(P_MALOAI) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MALOAIVATTU IN ('||P_MALOAI||')';
END IF;
IF TRIM(P_MANHOM) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND b.MANHOMVATTU IN ('||P_MANHOM||')';
END IF;
IF TRIM(P_NGUOIDUNG) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.I_CREATE_BY IN ('||P_NGUOIDUNG||')';
END IF;
IF TRIM(P_MAVATTU) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.MAHANG IN ('||P_MAVATTU||')';
END IF;    
IF TRIM(P_NHACUNGCAP) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND t.MAKHACHHANG IN ('||P_NHACUNGCAP||')';
END IF;
IF TRIM(P_MATHUE) IS NOT NULL THEN
P_EXPRESSION := P_EXPRESSION||' AND ct.VAT IN ('||P_MATHUE||')';
END IF;   
IF P_GROUPBY = 'MADONVI' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.UNITCODE, c.TENDONVI,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MADONVI, ''NULL'')  as MaCha, NVL(a.TENDONVI, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU  ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_DONVI c ON t.UNITCODE = c.MADONVI AND c.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP,t.NGAYCHUNGTU as NGAYCHUNGTU,t.UNITCODE AS MADONVI,c.TENDONVI AS TENDONVI,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MAKHO' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHONHAP, c.TENKHO,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHO, ''NULL'')  as MaCha, NVL(a.TENKHO, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU  ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_KHO c ON t.MAKHONHAP = c.MAKHO AND c.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP,t.NGAYCHUNGTU as NGAYCHUNGTU,t.MAKHONHAP AS MAKHO,c.TENKHO AS TENKHO,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MANHOMVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MANHOMVATTU,kh.TENNHOMVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU ,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MANHOMVATTU, ''NULL'')  as MaCha, NVL(a.TENNHOMVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHOMVATTU kh on b.MANHOMVATTU = kh.MANHOMVTU AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP,t.NGAYCHUNGTU as NGAYCHUNGTU, b.MANHOMVATTU AS MANHOMVATTU,kh.TENNHOMVT as TENNHOMVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'MALOAIVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MALOAIVATTU,kh.TENLOAIVT,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP ';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAIVATTU, ''NULL'')  as MaCha, NVL(a.TENLOAIVT, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_LOAIVATTU kh ON b.MALOAIVATTU = kh.MALOAIVATTU AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP, t.NGAYCHUNGTU as NGAYCHUNGTU,b.MALOAIVATTU AS MALOAIVATTU,kh.TENLOAIVT as TENLOAIVT,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';

P_SELECT:= ' ';

END;
ELSIF P_GROUPBY = 'MANHACUNGCAP' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MAKHACHHANG,kh.TENNCC,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAKHACHHANG, ''NULL'')  as MaCha, NVL(a.TENKH, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' INNER JOIN DM_NHACUNGCAP kh on t.MAKHACHHANG = kh.MANCC  AND kh.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP, t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MAKHACHHANG AS MAKHACHHANG,kh.TENNCC as TENKH,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'PHIEU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.MACHUNGTUPK,t.MACHUNGTU,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MACHUNGTU, ''NULL'')  as MaCha, NVL(a.MACHUNGTUPK, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NgayChungTu ';
P_TABLE_GROUPBY:= ' AND t.UNITCODE = '''||P_UNITCODE||''' ';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP, t.NGAYCHUNGTU as NGAYCHUNGTU ,t.MACHUNGTUPK AS MACHUNGTUPK,t.MACHUNGTU AS MACHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY ='MALOAITHUE' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'ct.VAT, lt.LOAITHUE,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MALOAITHUE, ''NULL'')  as MaCha, NVL(a.LOAITHUE, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU  ';
P_TABLE_GROUPBY:= ' ';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP,t.NGAYCHUNGTU as NGAYCHUNGTU,ct.VAT AS MALOAITHUE,lt.LOAITHUE AS LOAITHUE,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSIF P_GROUPBY = 'NGUOIDUNG' THEN
BEGIN
P_COLUMNS_GROUPBY:= 't.I_CREATE_BY, c.TENNHANVIEN,b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.USERNAME, ''NULL'')  as MaCha, NVL(a.TENNHANVIEN, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU as NGAYCHUNGTU  ';
P_TABLE_GROUPBY:= ' INNER JOIN AU_NGUOIDUNG c ON t.I_CREATE_BY = c.USERNAME AND c.UNITCODE = '''||P_UNITCODE||'''';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP,t.NGAYCHUNGTU as NGAYCHUNGTU,t.I_CREATE_BY AS USERNAME,c.TENNHANVIEN AS TENNHANVIEN,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
ELSE --ELSIF P_GROUPBY = 'MAVATTU' THEN
BEGIN
P_COLUMNS_GROUPBY:= 'b.MAVATTU,b.TENVATTU,ct.DONGIA,b.GiaBanLeVat,t.NGAYCHUNGTU,b.TENNHACUNGCAP';
P_SELECT_COLUMNS_GROUPBY:= ' NVL(a.MAVATTU, ''NULL'')  as MaCha, NVL(a.TENVATTU, ''NULL'') as TenCha,a.MAVATTU as MaCon,a.TENVATTU as TenCon,a.NGAYCHUNGTU AS NgayChungTu ';
P_TABLE_GROUPBY:= ' AND b.UNITCODE = '''||P_UNITCODE||''' ';
P_SELECT2:='b.TENNHACUNGCAP as TENNHACUNGCAP, t.NGAYCHUNGTU as NGAYCHUNGTU,b.MAVATTU as MAVATTU,b.TENVATTU as TENVATTU';
P_SELECT:= ' ';
END;
END IF;
QUERY_STR:= 'select a.BARCODE,(a.SOLUONG) as SoLuong,(a.DONGIANHAP) as DonGiaNhap,a.GiaBanLeVat as GiaBan, (a.TIENHANG) as TienHang, (a.TIENVAT) as TienVat, (a.TIENCHIETKHAU) as TienChietKhau, (a.TIENHANG - a.TIENCHIETKHAU + a.TIENVAT) AS TongTien ,a.TENNHACUNGCAP,'||P_SELECT_COLUMNS_GROUPBY||'
FROM (
SELECT '||P_SELECT2||',
SUM(ct.SOLUONG) as SOLUONG, 
ROUND(SUM(ct.SOLUONG*ROUND(NVL(ct.DONGIA,0)))) AS TIENHANG ,
ROUND(SUM(ROUND(NVL(ct.DONGIA,0))*NVL(lt.TYGIA/100,0)*ct.SOLUONG)) AS TIENVAT, 
ROUND(SUM(CASE WHEN NVL(t.TIENCHIETKHAU,0) >0 AND NVL(t.THANHTIENTRUOCVAT,0)>0 THEN ct.THANHTIEN *(NVL(t.TIENCHIETKHAU,0)/t.THANHTIENTRUOCVAT) ELSE 0 END),2) as TIENCHIETKHAU,
ROUND(NVL(ct.DONGIA,0)) as DONGIANHAP,
ROUND(NVL(b.GiaBanLeVat,0)) as GiaBanLeVat,
b.BARCODE AS BARCODE
FROM VATTUCHUNGTUCHITIET ct 
INNER JOIN VATTUCHUNGTU t on t.MACHUNGTUPK = ct.MACHUNGTUPK 
LEFT JOIN DM_LOAITHUE lt ON lt.MALOAITHUE = ct.VAT
INNER JOIN V_VATTU_GIABAN b on b.MAVATTU = ct.MAHANG AND b.UNITCODE = '''||P_UNITCODE||'''
'||P_TABLE_GROUPBY||'
WHERE
    t.TRANGTHAI = 10
    AND t.NGAYCHUNGTU <=TO_DATE('''||P_DENNGAY||''',''DD/MM/YY'')
    AND t.NGAYCHUNGTU >=TO_DATE('''||P_TUNGAY||''',''DD/MM/YY'') AND t.UNITCODE = '''||P_UNITCODE||''' AND t.LOAICHUNGTU ='''||P_LOAICHUNGTU||''' '||P_EXPRESSION||' GROUP BY '||P_COLUMNS_GROUPBY||',b.BARCODE
    ORDER BY '||P_COLUMNS_GROUPBY||' ) a';
 DBMS_OUTPUT.put_line (QUERY_STR);     
OPEN CUR FOR QUERY_STR;
  EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
         DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM);     
END NHAPMUACHITIET;
--------------------------------------------------------
--  DDL for Procedure NHAPMUACHITIET
--------------------------------------------------------
 